'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import {ReportPanel,type ReportStudent} from '@/components/report-card'
type Assignment={assignment_id:string;subject_name:string;title:string;description:string|null;due_at:string|null;attachment_url:string|null}
export default function ParentPortalPage(){
 const [children,setChildren]=useState<ReportStudent[]>([]),[childId,setChildId]=useState(''),[assignments,setAssignments]=useState<Assignment[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{let active=true;createClient().rpc('family_bulletin_data').then(({data,error})=>{if(!active)return;if(error)setError('Impossible de charger les enfants.');else{setChildren(data?.students||[]);setChildId(data?.students?.[0]?.id||'')}setLoading(false)});return()=>{active=false}},[])
 useEffect(()=>{let active=true;setAssignments([]);if(childId)createClient().rpc('family_child_activity',{p_student:childId}).then(({data,error})=>{if(!active)return;if(error)setError('Impossible de charger les devoirs.');else{setError('');setAssignments(data?.assignments||[])}});return()=>{active=false}},[childId])
 async function openAttachment(path:string){const {data,error}=await createClient().storage.from('assignment-files').createSignedUrl(path,60);if(error)setError(error.message);else if(data?.signedUrl)window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 return <main className="mx-auto max-w-5xl p-6"><header className="print:hidden"><Link href="/dashboard">← Tableau de bord</Link><h1 className="my-3 text-3xl font-bold">Portail parent</h1><p>Consultez les bulletins publiés, les examens et la présence de vos enfants.</p></header>{error&&<p role="alert" className="my-4 text-red-700">{error}</p>}{loading?<p>Chargement…</p>:!children.length?<p>Aucun enfant lié à ce compte.</p>:<><label className="my-5 block print:hidden">Enfant<select value={childId} onChange={e=>setChildId(e.target.value)} className="ml-2 rounded border p-3">{children.map(c=><option key={c.id} value={c.id}>{c.first_name} {c.last_name} · {c.atechos_id}</option>)}</select></label><ReportPanel key={childId} studentId={childId}/><section className="mt-6 print:hidden"><h2 className="text-2xl font-bold">Devoirs</h2>{assignments.map(a=><article key={a.assignment_id} className="my-3 rounded border bg-white p-4"><h3 className="font-bold">{a.title}</h3><p>{a.subject_name} · {a.due_at?new Date(a.due_at).toLocaleString('fr-HT',{timeZone:'America/Port-au-Prince'}):'Sans date limite'}</p><p className="whitespace-pre-wrap">{a.description}</p>{a.attachment_url&&<button className="mt-2 text-blue-700 underline" onClick={()=>openAttachment(a.attachment_url!)}>Ouvrir la pièce jointe</button>}</article>)}{!assignments.length&&<p>Aucun devoir actuel.</p>}</section></>}</main>
}
