export const DASHBOARD_ROLES=['school_admin','director','secretary','teacher','accountant','censeur','surveillant','parent','student'] as const
export type DashboardRole=typeof DASHBOARD_ROLES[number]
export type DashboardEventKind='enrollment'|'school_start'|'courses'|'exams'|'bulletins'|'council'|'holidays'|'year_end'
export type DashboardContext={schoolId:string|null;academicYearId:string|null;dashboard:DashboardRole;roles:readonly string[];capabilities:readonly string[];today:string}
export type DashboardEvent={id:string;schoolId:string;academicYearId:string;kind:DashboardEventKind;startsOn:string;endsOn:string;priority:number;audienceRoles?:readonly string[];upcomingWindowDays?:number}
export type DashboardWidget<T=unknown>={id:string;schoolId:string|null;academicYearId:string|null;dashboard:DashboardRole;requiredRoles?:readonly string[];requiredCapabilities?:readonly string[];eventKinds?:readonly DashboardEventKind[];dueOn?:string|null;deadlineWindowDays?:number;baseOrder:number;content:T}
export type RankedDashboardWidget<T=unknown>=DashboardWidget<T>&{priority:number;reasons:string[]}
function dayNumber(value:string):number|null{if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return null;const [y,m,d]=value.split('-').map(Number),date=new Date(Date.UTC(y,m-1,d));if(date.getUTCFullYear()!==y||date.getUTCMonth()!==m-1||date.getUTCDate()!==d)return null;return Math.floor(date.getTime()/86400000)}
function eventWindow(event:DashboardEvent,today:string):'active'|'upcoming'|null{const now=dayNumber(today),start=dayNumber(event.startsOn),end=dayNumber(event.endsOn);if(now===null||start===null||end===null||end<start)return null;if(now>=start&&now<=end)return'active';if(start>now&&start-now<=Math.max(0,event.upcomingWindowDays||0))return'upcoming';return null}
function deadlinePriority(widget:DashboardWidget,today:string):number|null{if(!widget.dueOn)return null;const now=dayNumber(today),due=dayNumber(widget.dueOn);if(now===null||due===null)return null;const delta=due-now;if(delta<0)return 20;if(delta===0)return 30;if(delta<=Math.max(0,widget.deadlineWindowDays??7))return 40;return null}
export function resolveDashboardWidgets<T>(widgets:readonly DashboardWidget<T>[],events:readonly DashboardEvent[],context:DashboardContext):RankedDashboardWidget<T>[] {
 return widgets.filter(w=>w.schoolId===context.schoolId&&w.academicYearId===context.academicYearId&&w.dashboard===context.dashboard&&(!w.requiredRoles?.length||w.requiredRoles.some(r=>context.roles.includes(r)))&&(!w.requiredCapabilities?.length||w.requiredCapabilities.every(c=>context.capabilities.includes(c))))
 .map(widget=>{let priority=100+widget.baseOrder;const reasons=['default_order'];for(const event of events){if(event.schoolId!==context.schoolId||event.academicYearId!==context.academicYearId||event.audienceRoles?.length&&!event.audienceRoles.some(r=>context.roles.includes(r))||!widget.eventKinds?.includes(event.kind))continue;const window=eventWindow(event,context.today);if(!window)continue;const score=event.priority+(window==='upcoming'?10:0);if(score<priority)priority=score;reasons.push(`event:${event.kind}:${window}`)}const due=deadlinePriority(widget,context.today);if(due!==null){if(due<priority)priority=due;reasons.push(due===20?'deadline:overdue':due===30?'deadline:today':'deadline:soon')}return{...widget,priority,reasons}})
 .sort((a,b)=>a.priority-b.priority||a.baseOrder-b.baseOrder||a.id.localeCompare(b.id))
}
