export type NavigationGroup='overview'|'people'|'preschool'|'school_life'|'teaching'|'results'|'finance'|'followup'|'administration'|'family_portals'
export type NavigationItem={label:string;href:string;icon:string;roles:string[];group:NavigationGroup}
const administration=['school_admin','director','secretary']
export const navigation:NavigationItem[]=[
 {label:'Dashboard',href:'/dashboard',icon:'dashboard',roles:['*'],group:'overview'},
 {label:'Students',href:'/dashboard/students',icon:'students',roles:[...administration,'teacher','surveillant'],group:'people'},
 {label:'Parents',href:'/dashboard/parents',icon:'parents',roles:administration,group:'people'},
 {label:'Subjects & Teachers',href:'/dashboard/subjects',icon:'teachers',roles:administration,group:'teaching'},
 {label:'Classes',href:'/dashboard/classes',icon:'classes',roles:administration,group:'teaching'},
 {label:'Attendance',href:'/dashboard/attendance',icon:'attendance',roles:[...administration,'teacher','surveillant'],group:'school_life'},
 {label:'Kindergarten pickup',href:'/dashboard/attendance/kindergarten-pickup',icon:'attendance',roles:[...administration,'surveillant','censeur'],group:'preschool'},
 {label:'Student Badges',href:'/dashboard/badges',icon:'badge',roles:[...administration,'surveillant'],group:'people'},
 {label:'Exams and school calendar',href:'/dashboard/calendar',icon:'calendar',roles:[...administration,'teacher','surveillant','censeur'],group:'school_life'},
 {label:'Grading periods',href:'/dashboard/grading-periods',icon:'calendar',roles:administration,group:'results'},
 {label:'Grades',href:'/dashboard/grades',icon:'grades',roles:[...administration,'teacher'],group:'results'},
 {label:'Publication des bulletins',href:'/dashboard/publication',icon:'publication',roles:['school_admin','director','censeur','secretary'],group:'results'},
 {label:'Bulletins',href:'/dashboard/bulletins',icon:'reports',roles:[...administration,'surveillant'],group:'results'},
 {label:'Preschool competency bulletins',href:'/dashboard/preschool',icon:'reports',roles:[...administration,'teacher','censeur'],group:'preschool'},
 {label:'Assignments',href:'/dashboard/assignments',icon:'assignments',roles:[...administration,'teacher'],group:'teaching'},
 {label:'Exam submissions',href:'/dashboard/exam-submissions',icon:'assignments',roles:['school_admin','director','secretary','censeur','teacher'],group:'teaching'},
 {label:'Academic progression',href:'/dashboard/progression',icon:'progression',roles:['school_admin','director'],group:'results'},
 {label:'Finance & Accounting',href:'/dashboard/finance',icon:'finance',roles:['school_admin','director','secretary','accountant'],group:'finance'},
 {label:'Payments',href:'/dashboard/finance/payments',icon:'finance',roles:['school_admin','director','secretary','accountant'],group:'finance'},
 {label:'Finance settings',href:'/dashboard/finance/settings',icon:'settings',roles:['school_admin','director','secretary','accountant'],group:'finance'},
 {label:'Access approvals',href:'/dashboard/approvals',icon:'requests',roles:['school_admin','director','censeur'],group:'followup'},
 {label:'Teacher requests',href:'/dashboard/teacher-requests',icon:'requests',roles:['school_admin','director'],group:'followup'},
 {label:'Users & staff',href:'/dashboard/staff',icon:'users',roles:['school_admin'],group:'administration'},
 {label:'Settings',href:'/dashboard/settings',icon:'settings',roles:['school_admin','director'],group:'administration'},
 {label:'Student follow-up cases',href:'/dashboard/guard',icon:'requests',roles:[...administration,'surveillant','parent'],group:'followup'},
 {label:'Sanctions and departures',href:'/dashboard/sanctions',icon:'requests',roles:administration,group:'followup'},
 {label:'Student Badges',href:'/dashboard/parent-badges',icon:'badge',roles:['parent'],group:'family_portals'},
 {label:'Parent Portal',href:'/dashboard/parent-portal',icon:'parents',roles:['parent'],group:'family_portals'},
 {label:'Family bulletins',href:'/dashboard/family-bulletins',icon:'reports',roles:['parent'],group:'family_portals'},
]
export function permittedNavigation(roles:string[],owner=false){const capabilities=roles.includes('censeur')?[...roles,'surveillant']:roles;return navigation.filter(n=>n.roles.includes('*')||n.roles.some(r=>capabilities.includes(r))||(owner&&!n.roles.includes('parent')))}
