import type {Locale} from './i18n'
import {extraTranslations} from './translations-extra'
export const translations:Record<string,[string,string]> = {
 ...extraTranslations,
 'Dashboard':['Tableau de bord','Tablo kontwòl'],'Logout':['Déconnexion','Dekonekte'],'Sign in':['Se connecter','Konekte'],'Sign up':['Créer un compte','Kreye kont'],'Continue':['Continuer','Kontinye'],
 'Students':['Élèves','Elèv'],'Classes':['Classes','Klas'],'Subjects':['Matières','Matyè'],'Grades':['Notes','Nòt'],'Parents':['Parents','Paran'],'Parent Portal':['Portail parent','Pòtal paran'],'Assignments':['Devoirs','Devwa'],'Staff':['Personnel','Anplwaye'],'Attendance':['Présences','Prezans'],'Attendance Kiosk':['Borne de présence','Kiosk prezans'],'Student Badges':['Cartes élèves','Badge elèv'],'Bulletins':['Bulletins','Biltin'],'Family bulletins':['Bulletins de la famille','Biltin fanmi an'],'Student portal':['Portail élève','Pòtal elèv'],
 'Grading periods':['Périodes d’examen','Peryòd egzamen'],'Grading settings':['Paramètres des notes','Paramèt nòt'],'Academic progression':['Passage de classe','Pasaj klas'],'Teacher requests':['Demandes des enseignants','Demann pwofesè'],'School access':['Accès à l’école','Aksè lekòl'],'Users & staff':['Utilisateurs et personnel','Itilizatè ak anplwaye'],
 'Save':['Enregistrer','Anrejistre'],'Cancel':['Annuler','Anile'],'Close':['Fermer','Fèmen'],'Approve':['Approuver','Apwouve'],'Reject':['Refuser','Refize'],'Loading...':['Chargement…','Ap chaje…'],'Saving...':['Enregistrement…','Ap anrejistre…'],'Active':['Actif','Aktif'],'Inactive':['Inactif','Inaktif'],
 'First name':['Prénom','Prenon'],'Last name':['Nom','Non'],'Full name':['Nom complet','Non konplè'],'Date of birth':['Date de naissance','Dat nesans'],'Place of birth':['Lieu de naissance','Kote nesans'],'Address':['Adresse','Adrès'],'Sex':['Sexe','Sèks'],'Email':['Adresse e-mail','Imel'],'Password':['Mot de passe','Modpas'],'Phone (optional)':['Téléphone (facultatif)','Telefòn (opsyonèl)'],
 'Add student':['Ajouter un élève','Ajoute elèv'],'Save student':['Enregistrer l’élève','Anrejistre elèv'],'Edit / assign class':['Modifier / affecter la classe','Modifye / asiyen klas'],'Profile':['Fiche','Fich'],'Invite parent':['Inviter un parent','Envite paran'],'Add / invite parent':['Ajouter / inviter un parent','Ajoute / envite paran'],'Parent full name':['Nom complet du parent','Non konplè paran'],'Save and invite parent':['Enregistrer et inviter','Anrejistre epi envite paran'],'Private invitation link':['Lien privé d’invitation','Lyen envitasyon prive'],'Copy link':['Copier le lien','Kopye lyen'],
 'Class':['Classe','Klas'],'Student':['Élève','Elèv'],'Subject':['Matière','Matyè'],'Teacher':['Enseignant','Pwofesè'],'Period':['Période','Peryòd'],'Code':['Code','Kòd'],'Name':['Nom','Non'],'Status':['Statut','Estati'],'Notes':['Remarques','Remak'],'Score':['Note','Nòt'],'Weight':['Coefficient','Pwa'],'Max score':['Note maximale','Nòt maksimòm'],'Average / 10':['Moyenne / 10','Mwayèn / 10'],
 'Academic year':['Année scolaire','Ane akademik'],'Academic years':['Années scolaires','Ane akademik yo'],'Classes & Academic Years':['Classes et années scolaires','Klas ak ane akademik'],'Activate school sections':['Activer les sections','Aktive seksyon lekòl la'],'Activate classes':['Activer les classes','Aktive klas yo'],'Deactivate':['Désactiver','Dezaktive'],'Activate':['Activer','Aktive'],'Grade structure':['Structure des classes','Estrikti klas yo'],'+ Academic year':['+ Année scolaire','+ Ane akademik'],'+ Class':['+ Classe','+ Klas'],
 'Subjects & Teachers':['Matières et enseignants','Matyè ak pwofesè'],'+ Subject':['+ Matière','+ Matyè'],'+ Assign subject':['+ Affecter une matière','+ Asiyen matyè'],'Create subject':['Créer une matière','Kreye matyè'],'Other — add a subject':['Autre — ajouter une matière','Lòt — ajoute matyè'],'Class subject assignments':['Affectation des matières','Matyè ki asiyen nan klas'],'Start date':['Date de début','Dat kòmansman'],'End date':['Date de fin','Dat finisman'],'Sections using this period':['Sections concernées','Seksyon ki sèvi ak peryòd sa a'],'Activate period':['Activer la période','Aktive peryòd la'],
 'Print / Save PDF':['Imprimer / Enregistrer en PDF','Enprime / Anrejistre PDF'],'Print badge':['Imprimer la carte','Enprime badge'],'Badge preview':['Aperçu de la carte','Apèsi badge'],'Scan':['Scanner','Eskane'],'Scan QR with camera':['Scanner le QR avec la caméra','Eskane QR ak kamera'],'Stop camera':['Arrêter la caméra','Fèmen kamera'],'Control / assessment':['Contrôle / évaluation','Kontwòl / evalyasyon'],'Save grades':['Enregistrer les notes','Anrejistre nòt'],'Load existing':['Charger les notes existantes','Chaje nòt ki deja la'],'Grade history':['Historique des notes','Istwa nòt'],'Publish class bulletin for this period':['Publier les bulletins de cette période','Pibliye biltin klas la pou peryòd sa a'],
 'Connect to your school':['Rejoindre votre école','Konekte ak lekòl ou'],'Your account is ready. Choose how you will use AtechOS.':['Votre compte est prêt. Choisissez votre accès.','Kont ou pare. Chwazi fason ou vle sèvi ak AtechOS.'],'Open my school dashboard':['Ouvrir le tableau de bord','Ouvri tablodbò lekòl mwen'],'School owner':['Propriétaire de l’école','Pwopriyetè lekòl'],'Teacher, staff member, parent or student':['Enseignant, personnel, parent ou élève','Pwofesè, anplwaye, paran oswa elèv'],'Teacher — request school access':['Enseignant — demander un accès','Pwofesè — mande aksè lekòl'],'School code':['Code de l’école','Kòd lekòl'],'Request access':['Demander un accès','Mande aksè'],'Student login with AtechOS ID':['Connexion élève avec AtechOS ID','Koneksyon elèv ak AtechOS ID'],
 'Previous year':['Année précédente','Ane anvan an'],'New year':['Nouvelle année','Nouvo ane'],'Prepare promotion list':['Préparer la liste de passage','Prepare lis pasaj'],'Current class':['Classe actuelle','Klas aktyèl'],'Decision':['Décision','Desizyon'],'Confirm selected placements':['Valider les décisions sélectionnées','Valide desizyon ki chwazi yo'],'Leave unchanged / review later':['Sans changement / revoir plus tard','Pa chanje / revize pita'],'Ailleurs — left school (archive only)':['Ailleurs — école quittée (archives)','Ailleurs — kite lekòl la (achiv sèlman)'],'Child':['Enfant','Pitit'],
 'No published bulletin available for this child.':['Aucun bulletin publié pour cet enfant.','Pa gen biltin pibliye pou pitit sa a.'],'Only your linked children and their published grades appear here.':['Seuls vos enfants liés et leurs notes publiées apparaissent ici.','Se sèlman pitit ki lye ak kont ou ak nòt pibliye yo ki parèt la.'],'Student portal activation':['Activation du portail élève','Aktivasyon pòtal elèv'],'Create / reset activation code':['Créer / réinitialiser le code d’activation','Kreye / reyinisyalize kòd aktivasyon'],
}
export function translate(text:string,locale:Locale){const value=translations[text.trim()];return locale==='en'||!value?text:value[locale==='fr'?0:1]}
