-- Isolated fixtures: the deliberate final exception rolls back this entire
-- subtransaction. Any failed assertion propagates and aborts the migration.
do $test$
declare owner_a uuid:=gen_random_uuid(); owner_b uuid:=gen_random_uuid(); teacher uuid:=gen_random_uuid(); guardian uuid:=gen_random_uuid(); learner uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid();
 activation text; device jsonb; payload jsonb; next_year uuid; next_class uuid; request_id uuid; a uuid; b uuid; yr uuid; cls uuid; other_cls uuid; subject uuid; child1 uuid; child2 uuid; other_child uuid; member uuid; invitation jsonb; invited jsonb; pid uuid; period uuid; n integer; rowcount integer; old_id text; failed boolean;
begin
 begin
  insert into auth.users(id,email,email_confirmed_at,role,aud) select id,id::text||'@example.invalid',now(),'authenticated','authenticated' from unnest(array[owner_a,owner_b,teacher,guardian,learner,outsider])id;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  set local role authenticated;
  a:=public.create_school_onboarding('Verification A',gen_random_uuid()::text);
  if not exists(select 1 from public.schools where id=a and owner_user_id=owner_a) then raise exception 'TEST owner creation'; end if;
  yr:=public.create_academic_year('Verification',date '2026-01-01',date '2026-12-31',true);
  perform public.activate_school_section(yr,'preschool');
  perform public.activate_school_section(yr,'preschool');
  if (select count(*) from public.classes where school_id=a and academic_year_id=yr)<>3 then raise exception 'TEST section activation duplicated classes'; end if;
  perform public.activate_school_section(yr,'preschool',false);
  if exists(select 1 from public.classes where school_id=a and enabled) then raise exception 'TEST section deactivation'; end if;
  period:=public.activate_grading_period(yr,'Verification period','V1','2026-01-01','2026-03-31',array['fundamental']);
  if public.activate_grading_period(yr,'Verification period','V1','2026-01-01','2026-03-31',array['fundamental'])<>period then raise exception 'TEST period duplicated'; end if;
  cls:=public.create_class(yr,'Class A','AF7');
  update public.classes set student_portal_allowed=true where id=cls;
  other_cls:=public.create_class(yr,'Class B','AF2');
  subject:=public.create_subject('Verification Mathematics','VERIFY');
  child1:=public.save_student_record(jsonb_build_object('first_name','Child','last_name','One','class_id',cls,'guardian_name','Guardian','guardian_email',guardian::text||'@example.invalid'));
  child2:=public.save_student_record(jsonb_build_object('first_name','Child','last_name','Two','class_id',cls,'guardian_name','Guardian','guardian_email',guardian::text||'@example.invalid'));
  other_child:=public.save_student_record(jsonb_build_object('first_name','Other','last_name','Child','class_id',other_cls));
  if (select count(*) from public.parents where school_id=a)<>1 then raise exception 'TEST guardian deduplication'; end if;
  select atechos_id into old_id from public.students where id=child1;
  perform public.save_student_record(jsonb_build_object('first_name','Corrected','last_name','One','class_id',cls,'date_of_birth','2013-02-10','place_of_birth','Verification city','address','Verification address','sex','F'),child1);
  if not exists(select 1 from public.students where id=child1 and date_of_birth='2013-02-10' and place_of_birth='Verification city' and address='Verification address' and sex='F') then raise exception 'TEST student demographics'; end if;
  if not exists(select 1 from public.students where id=child1 and atechos_id=old_id and photo_url is null) then raise exception 'TEST stable ID and optional photo'; end if;
  perform public.save_student_record(jsonb_build_object('first_name','Corrected','last_name','One','class_id',other_cls),child1);
  if not exists(select 1 from public.enrollments where student_id=child1 and class_id=cls and status='transferred') or not exists(select 1 from public.enrollments where student_id=child1 and class_id=other_cls and status='active') then raise exception 'TEST transfer did not move active class'; end if;
  perform public.save_student_record(jsonb_build_object('first_name','Corrected','last_name','One','class_id',cls,'date_of_birth','2013-02-10','place_of_birth','Verification city','address','Verification address','sex','F'),child1);
  if not exists(select 1 from public.students where id=child1 and date_of_birth='2013-02-10' and place_of_birth='Verification city' and address='Verification address' and sex='F') then raise exception 'TEST student demographics'; end if;
  if (select count(*) from public.enrollments where student_id=child1 and status='active')<>1 then raise exception 'TEST duplicate active class'; end if;
  if not exists(select 1 from public.get_student_records(child1) r where r ? 'nis') then raise exception 'TEST admin NIS access'; end if;
  invitation:=public.create_school_invitation(outsider::text||'@example.invalid','Director','director');
  perform set_config('request.jwt.claim.sub',outsider::text,true);
  perform public.accept_school_invitation(invitation->>'token');
  pid:=public.save_parent_for_student(child1,'Guardian',guardian::text||'@example.invalid');
  if public.save_parent_for_student(child2,'Guardian',guardian::text||'@example.invalid')<>pid then raise exception 'TEST duplicate parent'; end if;
  invitation:=public.create_school_invitation(guardian::text||'@example.invalid','Guardian','parent',null,pid);
  failed:=false; begin perform public.create_school_invitation(teacher::text||'@example.invalid','Teacher','teacher'); exception when others then failed:=true; end;
  if not failed then raise exception 'TEST director grants staff'; end if;
  perform set_config('request.jwt.claim.sub',guardian::text,true);
  perform public.accept_school_invitation(invitation->>'token');
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  invitation:=public.create_school_invitation(teacher::text||'@example.invalid','Teacher','teacher');
  perform set_config('request.jwt.claim.sub',outsider::text,true);
  failed:=false;
  begin perform public.accept_school_invitation(invitation->>'token'); exception when others then failed:=true; end;
  if not failed then raise exception 'TEST wrong email accepted'; end if;
  perform set_config('request.jwt.claim.sub',teacher::text,true);
  perform public.accept_school_invitation(invitation->>'token');
  failed:=false;
  begin perform public.accept_school_invitation(invitation->>'token'); exception when others then failed:=true; end;
  if not failed then raise exception 'TEST invitation replay'; end if;
  if exists(select 1 from public.students where school_id=a) then raise exception 'TEST unassigned teacher sees students'; end if;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  perform public.assign_subject_to_class(cls,subject,teacher);
  invitation:=public.create_school_invitation(guardian::text||'@example.invalid','Guardian','parent',null,(select id from public.parents where school_id=a));
  invited:=public.create_school_invitation(learner::text||'@example.invalid','Learner','student',child1);
  perform set_config('request.jwt.claim.sub',teacher::text,true);
  if (select count(*) from public.students where school_id=a)<>2 then raise exception 'TEST assigned teacher scope'; end if;
  failed:=false; begin perform nis from public.students where id=child1; exception when insufficient_privilege then failed:=true; end;
  if not failed then raise exception 'TEST teacher reads NIS'; end if;
  if exists(select 1 from public.get_student_records(child1) r where r ? 'nis') then raise exception 'TEST teacher RPC exposes NIS'; end if;
  failed:=false; begin perform public.publish_class_grades(cls,period); exception when others then failed:=true; end;
  if not failed then raise exception 'TEST teacher publishes grades'; end if;
  perform public.create_grade(child1,subject,cls,'Verification',8,10,null,period);
  failed:=false; begin update public.grades set published=true where student_id=child1; exception when others then failed:=true; end;
  if not failed then raise exception 'TEST teacher publishes directly'; end if;
  if not exists(select 1 from public.grades where student_id=child1) then raise exception 'TEST grade insert'; end if;
  failed:=false;
  begin perform public.create_grade(other_child,subject,other_cls,'Forbidden',8,10,null,null); exception when others then failed:=true; end;
  if not failed then raise exception 'TEST teacher crossed class'; end if;
  perform set_config('request.jwt.claim.sub',guardian::text,true);
  perform public.accept_school_invitation(invitation->>'token');
  if (select count(*) from public.students where school_id=a)<>2 then raise exception 'TEST parent multiple children'; end if;
  if exists(select 1 from public.grades where student_id=child1) then raise exception 'TEST unpublished grades exposed'; end if;
  update public.students set first_name='Forbidden' where id=child1;
  get diagnostics rowcount=row_count;
  if rowcount<>0 then raise exception 'TEST parent writes student'; end if;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  n:=public.publish_class_grades(cls,period);
  if n<>1 then raise exception 'TEST publish bulletin'; end if;
  failed:=false; begin perform public.create_grade(other_child,subject,other_cls,'Wrong section',8,10,null,period); exception when others then failed:=true; end;
  if not failed then raise exception 'TEST wrong section period accepted'; end if;

  -- A parent who is also a teacher must see only their own family in family mode.
  invitation:=public.create_school_invitation(guardian::text||'@example.invalid','Guardian teacher','teacher');
  perform set_config('request.jwt.claim.sub',guardian::text,true);
  perform public.accept_school_invitation(invitation->>'token');
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  perform public.assign_subject_to_class(other_cls,subject,guardian);
  perform public.create_grade(other_child,subject,other_cls,'Other family',7,10,null,null);
  update public.grades set published=true where student_id=other_child;
  perform set_config('request.jwt.claim.sub',guardian::text,true);
  payload:=public.family_bulletin_data();
  if jsonb_array_length(payload->'students')<>2 or jsonb_array_length(payload->'grades')<>1 or exists(select 1 from jsonb_array_elements(payload->'students') x where x->>'id'=other_child::text) then raise exception 'TEST mixed teacher-parent family data leak'; end if;
  failed:=false;begin perform public.family_child_activity(other_child);exception when others then failed:=true;end;
  if not failed then raise exception 'TEST parent activity exposes unrelated child'; end if;
  if jsonb_array_length(public.family_child_activity(child1)->'grades')<>1 then raise exception 'TEST linked child grades'; end if;
  -- Teacher applications never grant immediate access.
  select code into activation from public.schools where id=a;
  perform set_config('request.jwt.claim.sub',learner::text,true);
  perform public.request_teacher_access(activation);
  if exists(select 1 from public.school_members where user_id=learner and school_id=a and role='teacher') then raise exception 'TEST request self-approved'; end if;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  select id into request_id from public.teacher_join_requests where user_id=learner and school_id=a;
  perform public.review_teacher_request(request_id,false);
  if exists(select 1 from public.school_members where user_id=learner and school_id=a and role='teacher') then raise exception 'TEST rejected request granted access'; end if;
  perform set_config('request.jwt.claim.sub',learner::text,true);
  perform public.request_teacher_access(activation);
  failed:=false;begin perform public.review_teacher_request(request_id,true);exception when others then failed:=true;end;
  if not failed then raise exception 'TEST teacher approved own request'; end if;
  perform set_config('request.jwt.claim.sub',outsider::text,true);
  perform public.review_teacher_request(request_id,true);
  if not exists(select 1 from public.school_members where user_id=learner and school_id=a and role='teacher' and enabled) then raise exception 'TEST director approval failed'; end if;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  -- Staff cannot use the superseded attendance endpoint.
  failed:=false;begin perform public.scan_student_code(old_id,cls);exception when insufficient_privilege then failed:=true;end;
  if not failed then raise exception 'TEST legacy attendance still allowed';end if;
  activation:=public.issue_student_activation(child1);
  set local role anon;
  payload:=public.student_device_login(old_id,'Corrected One','wrong',null);
  if payload ? 'token' then raise exception 'TEST ID and name authenticate alone'; end if;
  device:=public.student_device_login(old_id,'Corrected One',activation,'648239');
  if not(device ? 'token') then raise exception 'TEST student activation failed %',device; end if;
  payload:=public.student_device_data(device->>'token');
  if payload->'student'->>'id'<>child1::text or jsonb_array_length(payload->'grades')<>1 then raise exception 'TEST student portal scope'; end if;
  if public.student_device_data('invalid') is not null then raise exception 'TEST forged student session'; end if;
  if public.student_device_login(old_id,'Corrected One',activation,null) ? 'token' then raise exception 'TEST activation replay'; end if;
  perform public.student_device_logout(device->>'token');
  if public.student_device_data(device->>'token') is not null then raise exception 'TEST student logout'; end if;
  device:=public.student_device_login(old_id,'Corrected One','648239',null);
  if not(device ? 'token') then raise exception 'TEST student PIN login'; end if;
  for n in 1..5 loop perform public.student_device_login(old_id,'Corrected One','wrong',null);end loop;
  if public.student_device_login(old_id,'Corrected One','648239',null) ? 'token' then raise exception 'TEST PIN lockout missing'; end if;
  reset role;
  update private.student_credentials set locked_until=now()-interval '1 minute' where student_id=child1;
  update private.student_sessions set expires_at=now()-interval '1 minute' where student_id=child1;
  set local role anon;
  if public.student_device_data(device->>'token') is not null then raise exception 'TEST expired student session'; end if;
  perform public.student_device_login(old_id,'Corrected One','wrong',null);
  device:=public.student_device_login(old_id,'Corrected One','648239',null);
  if not(device ? 'token') then raise exception 'TEST PIN lockout recovery'; end if;
  set local role authenticated;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  next_year:=public.create_academic_year('Next verification','2027-01-01','2027-12-31',false);
  perform public.activate_school_section(next_year,'fundamental');
  payload:=public.preview_student_progression(yr,next_year);
  if exists(select 1 from jsonb_array_elements(payload) x where x->>'id'=child1::text and x->>'recommended_grade' is not null) then raise exception 'TEST incomplete grades recommended promotion'; end if;
  perform public.update_grading_settings(1,5);
  payload:=public.preview_student_progression(yr,next_year);
  if not exists(select 1 from jsonb_array_elements(payload) x where x->>'id'=child1::text and x->>'recommended_grade'='AF8') then raise exception 'TEST promotion recommendation %',payload; end if;
  select id into next_class from public.classes where academic_year_id=next_year and grade_level='AF8';
  failed:=false;begin perform public.confirm_student_progression(yr,next_year,jsonb_build_array(jsonb_build_object('student_id',child2,'decision','departed'),jsonb_build_object('student_id',child1,'class_id',gen_random_uuid())));exception when others then failed:=true;end;
  if not failed or exists(select 1 from public.students where id=child2 and school_status='departed') then raise exception 'TEST progression partially applied'; end if;
  perform public.apply_student_progression(next_year,jsonb_build_array(jsonb_build_object('student_id',child1,'class_id',next_class)));
  if not exists(select 1 from public.enrollments where student_id=child1 and class_id=cls) or not exists(select 1 from public.enrollments where student_id=child1 and class_id=next_class and status='active') then raise exception 'TEST progression lost history'; end if;
  perform public.create_grade(child1,subject,next_class,'Next year private',9,10,null,null);
  update public.grades set published=true where student_id=child1 and class_id=next_class;
  perform public.confirm_student_progression(yr,next_year,jsonb_build_array(jsonb_build_object('student_id',child1,'decision','departed')));
  failed:=false;begin perform public.apply_student_progression(next_year,jsonb_build_array(jsonb_build_object('student_id',child1,'class_id',next_class)));exception when others then failed:=true;end;
  if not failed then raise exception 'TEST departed student re-enrolled'; end if;
  payload:=public.student_device_data(device->>'token');
  if jsonb_array_length(payload->'grades')<>1 or jsonb_array_length(payload->'assignments')<>0 then raise exception 'TEST departed archives'; end if;
  perform set_config('request.jwt.claim.sub',guardian::text,true);
  if exists(select 1 from public.grades where student_id=child1 and class_id=next_class) then raise exception 'TEST family direct access crossed archive cutoff'; end if;
  if jsonb_array_length(public.family_bulletin_data()->'grades')<>1 or jsonb_array_length(public.family_child_activity(child1)->'grades')<>1 then raise exception 'TEST family archives cutoff'; end if;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  delete from public.grades where student_id=child1 and class_id=next_class;
  -- Restore fixture eligibility for the existing student-invitation assertions.
  reset role;update public.students set school_status='active',departure_year_id=null where id=child1;
  update public.enrollments set status='active' where student_id=child1 and class_id=cls;
  set local role authenticated;
  select id into member from public.school_members where school_id=a and user_id=owner_a;
  failed:=false;
  begin perform public.manage_school_member(member,'remove'); exception when others then failed:=true; end;
  if not failed then raise exception 'TEST owner removed'; end if;
  failed:=false;
  begin update public.schools set owner_user_id=teacher where id=a; exception when insufficient_privilege then failed:=true; end;
  if not failed then raise exception 'TEST ownership changed through API'; end if;
  perform set_config('request.jwt.claim.sub',learner::text,true);
  perform public.accept_school_invitation(invited->>'token');
  if (select count(*) from public.students where school_id=a)<>1 then raise exception 'TEST student sees peers'; end if;
  if (select count(*) from public.grades where student_id=child1)<>1 then raise exception 'TEST published grade visibility'; end if;
  perform set_config('request.jwt.claim.sub',owner_b::text,true);
  b:=public.create_school_onboarding('Verification B',gen_random_uuid()::text);
  if exists(select 1 from public.schools where id=a) or exists(select 1 from public.students where school_id=a) then raise exception 'TEST school isolation'; end if;
  failed:=false;
  begin perform public.create_school_invitation(learner::text||'@example.invalid','Cross school','student',child1); exception when others then failed:=true; end;
  if not failed then raise exception 'TEST cross school invitation'; end if;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  select id into member from public.school_members where school_id=a and user_id=teacher;
  perform public.manage_school_member(member,'disable');
  perform set_config('request.jwt.claim.sub',teacher::text,true);
  if exists(select 1 from public.students where school_id=a) then raise exception 'TEST disabled teacher access'; end if;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  perform public.manage_school_member((select id from public.school_members where school_id=a and user_id=outsider),'disable');
  perform set_config('request.jwt.claim.sub',outsider::text,true);
  if exists(select 1 from public.students) or exists(select 1 from public.schools) then raise exception 'TEST user without membership'; end if;
  reset role;
  raise exception using errcode='ZX001',message='Fixture rollback';
 exception when sqlstate 'ZX001' then null;
 end;
end $test$;
