do $test$
declare owner_id uuid:=gen_random_uuid();guardian uuid:=gen_random_uuid();teacher uuid:=gen_random_uuid();outsider uuid:=gen_random_uuid();sid uuid;yr uuid;cls uuid;child uuid;pid uuid;other_child uuid;inv jsonb;qr text;replacement text;code text;payload jsonb;failed boolean;
begin begin
 insert into auth.users(id,email,email_confirmed_at,role,aud) select id,id::text||'@example.invalid',now(),'authenticated','authenticated' from unnest(array[owner_id,guardian,teacher,outsider]) id;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);set local role authenticated;
 sid:=public.create_school_onboarding('Badge verification',gen_random_uuid()::text);yr:=public.create_academic_year('Badge year','2026-01-01','2026-12-31',true);cls:=public.create_class(yr,'Badge class','PS1');
 child:=public.save_student_record(jsonb_build_object('first_name','Badge','last_name','Child','class_id',cls));other_child:=public.save_student_record(jsonb_build_object('first_name','Other','last_name','Child','class_id',cls));
 select r->>'atechos_id' into code from public.get_student_records(child) r;
 pid:=public.save_parent_for_student(child,'Guardian',guardian::text||'@example.invalid');inv:=public.create_school_invitation(guardian::text||'@example.invalid','Guardian','parent',null,pid);
 perform set_config('request.jwt.claim.sub',guardian::text,true);perform public.accept_school_invitation(inv->>'token');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);inv:=public.create_school_invitation(teacher::text||'@example.invalid','Teacher','teacher');
 perform set_config('request.jwt.claim.sub',teacher::text,true);perform public.accept_school_invitation(inv->>'token');
 failed:=false;begin perform public.badge_workspace(child);exception when others then failed:=true;end;if not failed then raise exception 'TEST teacher badge privacy';end if;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);qr:=public.get_student_badge_qr(child);
 if qr is null or qr<>public.get_student_badge_qr(child) then raise exception 'TEST stable reprint QR';end if;
 reset role;
 execute $mock$create or replace function private.kiosk_window(p_time time) returns text language sql immutable set search_path='' as 'select ''present''::text'$mock$;
 perform set_config('request.jwt.claim.sub','',true);set local role anon;
 if public.student_kiosk_badge(qr)->>'action'<>'check_in' then raise exception 'TEST QR check in without PIN';end if;
 if public.student_kiosk_badge(qr)->>'action'<>'duplicate_scan' then raise exception 'TEST duplicate toggles checkout';end if;
 reset role;perform set_config('request.jwt.claim.sub',guardian::text,true);set local role authenticated;
 if public.badge_workspace(child)->>'qr' is not null then raise exception 'TEST parent raw credential';end if;
 failed:=false;begin perform public.report_badge_lost(other_child,'Wrong child');exception when others then failed:=true;end;if not failed then raise exception 'TEST unrelated parent loss';end if;
 perform public.report_badge_lost(child,'Lost on journey');perform public.report_badge_lost(child,'Repeat declaration');
 reset role;perform set_config('request.jwt.claim.sub','',true);set local role anon;
 if public.student_kiosk_badge(qr)->>'error'<>'invalid_badge' then raise exception 'TEST lost badge accepted';end if;
 reset role;perform set_config('request.jwt.claim.sub',owner_id::text,true);set local role authenticated;
 if public.get_student_badge_qr(child) is not null then raise exception 'TEST view reactivates lost badge';end if;
 if (select count(*) from public.notifications where type='lost_badge')<>1 then raise exception 'TEST duplicate missing badge notice';end if;
 payload:=public.badge_workspace(child);
 if not exists(select 1 from jsonb_array_elements(payload->'badges') b where b->>'state'='lost') then raise exception 'TEST lost history';end if;
 replacement:=public.get_student_badge_qr(child,true);
 if qr=replacement or replacement is null then raise exception 'TEST replacement credential';end if;
 if not exists(select 1 from public.get_student_records(child) r where r->>'atechos_id'=code) then raise exception 'TEST permanent identity changed';end if;
 if has_function_privilege('authenticated','public.scan_student_badge(text,uuid,timestamptz,integer)','execute') then raise exception 'TEST legacy toggling endpoint accessible';end if;
 failed:=false;begin update public.student_badges set active=true where student_id=child;exception when insufficient_privilege then failed:=true;end;if not failed then raise exception 'TEST direct reactivation bypass';end if;
 reset role;perform set_config('request.jwt.claim.sub','',true);set local role anon;
 if public.student_kiosk_badge(qr)->>'error'<>'invalid_badge' then raise exception 'TEST old replacement credential accepted';end if;
 if public.student_kiosk_badge(replacement)->>'action'<>'duplicate_scan' then raise exception 'TEST replacement QR rejected';end if;
 reset role;perform set_config('request.jwt.claim.sub',owner_id::text,true);set local role authenticated;
 payload:=public.badge_workspace(child);
 if jsonb_array_length(payload->'scans')<>5 or not exists(select 1 from jsonb_array_elements(payload->'scans') r where r->>'result'='rejected_lost') then raise exception 'TEST scan history';end if;
 perform set_config('request.jwt.claim.sub',outsider::text,true);perform public.create_school_onboarding('Other badge school',gen_random_uuid()::text);
 failed:=false;begin perform public.badge_workspace(child);exception when others then failed:=true;end;if not failed then raise exception 'TEST cross tenant badge history';end if;

 perform set_config('request.jwt.claim.sub',guardian::text,true);
 failed:=false;begin perform public.revoke_student_badge(child,'Parent denied');exception when others then failed:=true;end;if not failed then raise exception 'TEST parent admin revoke';end if;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);perform public.revoke_student_badge(child,'Damaged badge');
 if public.student_kiosk_badge(replacement)->>'error'<>'invalid_badge' then raise exception 'TEST revoked badge scan';end if;
 if public.get_student_badge_qr(child) is not null then raise exception 'TEST revoked badge read reactivated';end if;
 reset role;raise exception using errcode='ZX004',message='fixtures passed';exception when sqlstate 'ZX004' then null;end;
end $test$;
select 'PASS badge lifecycle: permanent identity, QR/PIN separation, parent scope, immediate revocation, immutable history, unique replacement, duplicate scan, legacy endpoint blocked, notices isolated' as result;
