do $test$
declare owner_id uuid:=gen_random_uuid();reviewer uuid:=gen_random_uuid();guardian uuid:=gen_random_uuid();outsider uuid:=gen_random_uuid();
 sid uuid;yr uuid;prior_year uuid;cls uuid;sub uuid;child uuid;other_child uuid;period uuid;inv jsonb;pid uuid;g public.grades;doc jsonb;v1 uuid;v2 uuid;v3 uuid;correction uuid;failed boolean;activation text;device jsonb;code text;
begin begin
 insert into auth.users(id,email,email_confirmed_at,role,aud) select id,id::text||'@example.invalid',now(),'authenticated','authenticated' from unnest(array[owner_id,reviewer,guardian,outsider]) id;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);set local role authenticated;
 sid:=public.create_school_onboarding('Bulletin fixture',gen_random_uuid()::text);
 yr:=public.create_academic_year('Version year','2026-01-01','2026-12-31',true);cls:=public.create_class(yr,'Version class','AF7');
 update public.classes set student_portal_allowed=true where id=cls;
 period:=public.activate_grading_period(yr,'Version period','V1','2026-01-01','2026-12-31',array['fundamental']);
 sub:=public.create_subject('Version subject','VS');perform public.assign_subject_to_class(cls,sub,null);
 child:=public.save_student_record(jsonb_build_object('first_name','Original','last_name','Learner','class_id',cls));
 other_child:=public.save_student_record(jsonb_build_object('first_name','Other','last_name','Learner','class_id',cls));
 inv:=public.create_school_invitation(reviewer::text||'@example.invalid','Censeur Fixture','censeur');
 perform set_config('request.jwt.claim.sub',reviewer::text,true);perform public.accept_school_invitation(inv->>'token');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 pid:=public.save_parent_for_student(child,'Parent',guardian::text||'@example.invalid');inv:=public.create_school_invitation(guardian::text||'@example.invalid','Parent','parent',null,pid);
 perform set_config('request.jwt.claim.sub',guardian::text,true);perform public.accept_school_invitation(inv->>'token');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 failed:=false;begin perform public.publish_class_bulletins(cls,period,'No grades yet');exception when others then failed:=sqlerrm='no_published_grades';end;if not failed then raise exception 'TEST no grades publication';end if;
 g:=public.create_grade(child,sub,cls,'Period grade',7,10,null,period,100);perform public.submit_grades(array[g.id]);perform public.review_grades(array[g.id],'approve');perform public.publish_reviewed_grades(array[g.id]);
 if public.publish_class_bulletins(cls,period,'First official version')<>2 then raise exception 'TEST whole class publication';end if;
 doc:=public.get_report_card(child);v1:=(doc->'cards'->0->'document'->>'id')::uuid;
 if v1 is null or doc->'cards'->0->'document'->>'approver' is not null or (doc->'cards'->0->'document'->>'version')::int is distinct from 1 then raise exception 'TEST invented approval';end if;
 if not exists(select 1 from jsonb_array_elements(public.bulletin_class_preview(cls,period)) r where r->'student'->>'id'=other_child::text and r->'cards'->0->>'status'='incomplete') then raise exception 'TEST incomplete roster';end if;
 perform public.save_student_record(jsonb_build_object('first_name','Corrected','last_name','Learner'),child);
 doc:=public.get_report_card(child);
 if doc->'cards'->0->'identity'->>'first_name'<>'Original' then raise exception 'TEST old identity changed';end if;
 failed:=false;begin perform public.approve_bulletin_version(v1,'Owner is not Censeur');exception when others then failed:=sqlerrm='censeur_approval_required';end;if not failed then raise exception 'TEST fake Censeur authority';end if;
 perform set_config('request.jwt.claim.sub',reviewer::text,true);v2:=public.approve_bulletin_version(v1,'Reviewed exact document');
 doc:=public.get_report_card(child);
 if (doc->'cards'->0->'document'->>'approved_by')::uuid<>reviewer or doc->'cards'->0->'identity'->>'first_name'<>'Original' or jsonb_array_length(doc->'document_history') is distinct from 2 then raise exception 'TEST approval version contents';end if;
 failed:=false;begin perform public.approve_bulletin_version(v1,'Stale document');exception when others then failed:=sqlerrm='newer_bulletin_exists';end;if not failed then raise exception 'TEST stale approval';end if;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);perform public.publish_class_bulletins(cls,period,'Updated student information');
 doc:=public.get_report_card(child);v3:=(doc->'cards'->0->'document'->>'id')::uuid;
 if doc->'cards'->0->'identity'->>'first_name'<>'Corrected' or doc->'cards'->0->'document'->>'approver' is not null then raise exception 'TEST approval copied to changed version';end if;
 perform public.revise_grade(g.id,9,10,null,'Correct the official score');doc:=public.grade_history(g.id);correction:=(doc->'corrections'->0->>'id')::uuid;
 perform public.review_grade_correction(correction,'approve');perform public.review_grade_correction(correction,'publish');
 doc:=public.get_report_card(child);if (doc->'cards'->0->>'average')::numeric is distinct from 7::numeric then raise exception 'TEST correction mutated archived bulletin';end if;
 perform public.publish_class_bulletins(cls,period,'New score version');doc:=public.get_report_card(child);
 if (doc->'cards'->0->>'average')::numeric is distinct from 9::numeric then raise exception 'TEST revised document score';end if;
 failed:=false;begin update public.bulletin_versions set reason='changed' where id=v1;exception when insufficient_privilege then failed:=true;end;if not failed then raise exception 'TEST direct edit grants';end if;
 code:=doc->'student'->>'atechos_id';activation:=public.issue_student_activation(child);
 perform set_config('request.jwt.claim.sub',guardian::text,true);doc:=public.get_report_card(child);
 if jsonb_array_length(doc->'document_history') is distinct from 4 then raise exception 'TEST parent versions';end if;
 if not exists(select 1 from public.notifications where recipient_id=guardian and type='bulletins') then raise exception 'TEST family notification';end if;
 failed:=false;begin perform public.get_report_card(other_child);exception when others then failed:=true;end;if not failed then raise exception 'TEST other child disclosure';end if;
 failed:=false;begin perform public.bulletin_class_preview(cls,period);exception when others then failed:=true;end;if not failed then raise exception 'TEST parent preview';end if;
 failed:=false;begin perform public.publish_class_bulletins(cls,period,'Parent publishing');exception when others then failed:=true;end;if not failed then raise exception 'TEST parent publication';end if;
 set local role anon;device:=public.student_device_login(code,'Corrected Learner',activation,'648239');doc:=public.student_portal_overview(device->>'token');
 if jsonb_array_length(doc->'report'->'document_history') is distinct from 4 then raise exception 'TEST student token versions';end if;
 reset role;update public.grading_periods set sections=array['primary'] where id=period;
 perform set_config('request.jwt.claim.sub',guardian::text,true);set local role authenticated;doc:=public.get_report_card(child);
 if jsonb_array_length(doc->'document_history') is distinct from 4 or jsonb_array_length(doc->'cards') is distinct from 1 then raise exception 'TEST period edit erased historical access';end if;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);prior_year:=public.create_academic_year('Earlier departure','2025-01-01','2025-12-31',false);
 reset role;update public.students set departure_year_id=prior_year where id=child;
 perform set_config('request.jwt.claim.sub',guardian::text,true);set local role authenticated;doc:=public.get_report_card(child);
 if jsonb_array_length(doc->'document_history') is distinct from 0 or jsonb_array_length(doc->'cards') is distinct from 0 then raise exception 'TEST post-departure year disclosure';end if;
 reset role;update public.students set departure_year_id=yr where id=child;
 set local role authenticated;doc:=public.get_report_card(child);
 if jsonb_array_length(doc->'document_history') is distinct from 4 then raise exception 'TEST departure lost own historical year';end if;
 set local role authenticated;perform set_config('request.jwt.claim.sub',outsider::text,true);perform public.create_school_onboarding('Other school',gen_random_uuid()::text);
 failed:=false;begin perform public.publish_class_bulletins(cls,period,'Cross school');exception when others then failed:=true;end;if not failed then raise exception 'TEST cross school publish';end if;
 reset role;
 failed:=false;begin update public.bulletin_versions set reason='changed' where id=v1;exception when others then failed:=sqlerrm='bulletin_version_immutable';end;if not failed then raise exception 'TEST immutable trigger';end if;
 if (select payload from public.bulletin_versions where id=v1) is distinct from (select payload from public.bulletin_versions where id=v2) then raise exception 'TEST endorsement altered contents';end if;
 raise exception using errcode='ZX004',message='fixtures passed';exception when sqlstate 'ZX004' then null;end;
end $test$;
select 'PASS immutable class bulletins, incomplete status, actual Censeur endorsement/new version, frozen identity, no copied approval, stale approval denial, parent/session/cross-school isolation and immutable database history; fixtures rolled back' as result;
