do $test$
declare owner_id uuid:=gen_random_uuid();teacher uuid:=gen_random_uuid();guardian uuid:=gen_random_uuid();reviewer uuid:=gen_random_uuid();outsider uuid:=gen_random_uuid();
 sid uuid;yr uuid;cls uuid;cls2 uuid;su uuid;su2 uuid;child uuid;other_child uuid;period uuid;v1 uuid;v2 uuid;v3 uuid;v4 uuid;other_v uuid;ex uuid;inv jsonb;payload jsonb;token text;failed boolean;parent_id uuid;
begin begin
 insert into auth.users(id,email,email_confirmed_at,role,aud) select id,id::text||'@example.invalid',now(),'authenticated','authenticated' from unnest(array[owner_id,teacher,guardian,reviewer,outsider]) id;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);set local role authenticated;
 sid:=public.create_school_onboarding('Exam verification',gen_random_uuid()::text);
 yr:=public.create_academic_year('2026 test','2026-01-01','2026-12-31',true);cls:=public.create_class(yr,'Class A','AF7');cls2:=public.create_class(yr,'Class B','AF7');
 su:=public.create_subject('Subject A','XA');su2:=public.create_subject('Subject B','XB');
 inv:=public.create_school_invitation(teacher::text||'@example.invalid','Teacher','teacher');perform set_config('request.jwt.claim.sub',teacher::text,true);perform public.accept_school_invitation(inv->>'token');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);inv:=public.create_school_invitation(reviewer::text||'@example.invalid','Censeur','censeur');perform set_config('request.jwt.claim.sub',reviewer::text,true);perform public.accept_school_invitation(inv->>'token');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);perform public.assign_subject_to_class(cls,su,teacher);perform public.assign_subject_to_class(cls,su2,null);perform public.assign_subject_to_class(cls2,su,null);
 child:=public.save_student_record(jsonb_build_object('first_name','Exam','last_name','Child','class_id',cls));other_child:=public.save_student_record(jsonb_build_object('first_name','Other','last_name','Child','class_id',cls2));
 parent_id:=public.save_parent_for_student(child,'Guardian',guardian::text||'@example.invalid');inv:=public.create_school_invitation(guardian::text||'@example.invalid','Guardian','parent',null,parent_id);
 perform set_config('request.jwt.claim.sub',guardian::text,true);perform public.accept_school_invitation(inv->>'token');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);period:=public.activate_grading_period(yr,'Exam period','EX','2026-09-01','2026-09-30',array['fundamental']);
 v1:=public.save_exam(cls,su,period,'2026-09-25 08:00 America/Port-au-Prince','2026-09-25 10:00 America/Port-au-Prince','Initial exam',null,'2026-09-14','2026-09-18');
 payload:=public.exam_schedule_workspace();ex:=(payload->'versions'->0->>'exam_id')::uuid;
 failed:=false;begin perform public.publish_exam_version(v1);exception when others then failed:=sqlerrm='censeur_publication_required';end;if not failed then raise exception 'TEST admin bypasses censeur publication';end if;
 perform set_config('request.jwt.claim.sub',guardian::text,true);payload:=public.school_calendar(child);if jsonb_array_length(payload->'exams')<>0 then raise exception 'TEST draft visible to parent';end if;
 perform set_config('request.jwt.claim.sub',reviewer::text,true);perform public.publish_exam_version(v1);
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 v2:=public.save_exam(cls,su,period,'2026-09-25 09:00 America/Port-au-Prince','2026-09-25 10:00 America/Port-au-Prince','Reschedule one hour',ex,'2026-09-14','2026-09-18');
 perform set_config('request.jwt.claim.sub',guardian::text,true);payload:=public.school_calendar(child);if (payload->'exams'->0->>'version')::integer<>1 then raise exception 'TEST draft replaced official';end if;
 perform set_config('request.jwt.claim.sub',reviewer::text,true);perform public.publish_exam_version(v2);
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 v3:=public.save_exam(cls,su,period,'2026-09-25 09:30 America/Port-au-Prince','2026-09-25 10:00 America/Port-au-Prince','Return this change',ex);perform public.return_exam_version(v3,'Keep official time');
 payload:=public.school_calendar();if (payload->'exams'->0->>'version')::integer<>2 then raise exception 'TEST returned changed official';end if;
 other_v:=public.save_exam(cls,su2,period,'2026-09-25 09:30 America/Port-au-Prince','2026-09-25 10:30 America/Port-au-Prince','Conflict fixture');
 perform set_config('request.jwt.claim.sub',reviewer::text,true);failed:=false;begin perform public.publish_exam_version(other_v);exception when others then failed:=sqlerrm='exam_time_conflict';end;if not failed then raise exception 'TEST overlapping publication';end if;
 perform public.return_exam_version(other_v,'Conflicting time');
 other_v:=public.save_exam(cls,su2,period,'2026-09-25 10:00 America/Port-au-Prince','2026-09-25 11:00 America/Port-au-Prince','Second subject');perform public.publish_exam_version(other_v);
 other_v:=public.save_exam(cls2,su,period,'2026-09-25 08:00 America/Port-au-Prince','2026-09-25 10:00 America/Port-au-Prince','Other class');perform public.publish_exam_version(other_v);
 perform set_config('request.jwt.claim.sub',owner_id::text,true);perform public.save_school_closure('2026-09-28','School closed');
 failed:=false;begin perform public.save_exam(cls,su,period,'2026-09-28 08:00 America/Port-au-Prince','2026-09-28 10:00 America/Port-au-Prince','Closed day');exception when others then failed:=sqlerrm='school_closed';end;if not failed then raise exception 'TEST closed day';end if;
 failed:=false;begin perform public.save_exam(cls,su,period,'2026-10-01 08:00 America/Port-au-Prince','2026-10-01 10:00 America/Port-au-Prince','Outside period');exception when others then failed:=sqlerrm='invalid_exam_scope_or_date';end;if not failed then raise exception 'TEST outside period';end if;
 reset role;
 token:=encode(extensions.gen_random_bytes(32),'hex');update public.students set portal_enabled=true where id=child;insert into private.student_sessions(student_id,token_hash,expires_at) values(child,encode(extensions.digest(token,'sha256'),'hex'),now()+interval '1 hour');
 perform private.capture_exam_presence(child,cls,'2026-09-25 07:30 America/Port-au-Prince');perform private.capture_exam_presence(child,cls,'2026-09-25 07:40 America/Port-au-Prince');perform private.capture_exam_presence(other_child,cls,'2026-09-25 07:30 America/Port-au-Prince');
 if (select count(*) from public.exam_presence where student_id=child)<>2 or exists(select 1 from public.exam_presence where student_id=other_child) then raise exception 'TEST class exam presence';end if;
 if (select scanned_at from public.exam_presence where exam_id=ex and student_id=child)<>'2026-09-25 07:30 America/Port-au-Prince'::timestamptz then raise exception 'TEST first scan changed';end if;
 set local role anon;perform set_config('request.jwt.claim.sub','',true);payload:=public.school_calendar(other_child,token);
 if jsonb_array_length(payload->'exams')<>2 or (payload->>'can_manage')::boolean or (payload->>'can_publish')::boolean then raise exception 'TEST student scope';end if;
 failed:=false;begin perform public.school_calendar(child,'invalid');exception when others then failed:=true;end;if not failed then raise exception 'TEST forged session';end if;
 failed:=false;begin perform * from public.exam_schedule_versions;exception when insufficient_privilege then failed:=true;end;if not failed then raise exception 'TEST private versions leak';end if;
 reset role;set local role authenticated;perform set_config('request.jwt.claim.sub',teacher::text,true);payload:=public.school_calendar();
 if jsonb_array_length(payload->'exams')<>1 or payload->'exams'->0->>'subject'<>'Subject A' then raise exception 'TEST teacher scope';end if;
 failed:=false;begin perform public.exam_schedule_workspace();exception when others then failed:=true;end;if not failed then raise exception 'TEST teacher draft access';end if;
 perform set_config('request.jwt.claim.sub',guardian::text,true);if jsonb_array_length(public.school_calendar(child)->'exams')<>2 then raise exception 'TEST parent own calendar';end if;
 failed:=false;begin perform public.school_calendar(other_child);exception when others then failed:=true;end;if not failed then raise exception 'TEST unrelated child';end if;
 if not exists(select 1 from public.notifications where recipient_id=guardian and type='exams') then raise exception 'TEST family publication notifications';end if;
 perform set_config('request.jwt.claim.sub',outsider::text,true);perform public.create_school_onboarding('Other school',gen_random_uuid()::text);if jsonb_array_length(public.school_calendar()->'exams')<>0 then raise exception 'TEST tenant calendar';end if;
 failed:=false;begin perform public.return_exam_version(v2,'Cross tenant');exception when others then failed:=true;end;if not failed then raise exception 'TEST tenant write';end if;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);v4:=public.save_exam(cls,su,period,'2026-09-25 09:00 America/Port-au-Prince','2026-09-25 10:00 America/Port-au-Prince','Cancellation fixture',ex,null,null,true);
 if exists(select 1 from jsonb_array_elements(public.school_calendar()->'exams') e where (e->>'id')::uuid=ex and (e->>'cancelled')::boolean) then raise exception 'TEST pending cancel published';end if;
 perform set_config('request.jwt.claim.sub',reviewer::text,true);perform public.publish_exam_version(v4);
 if not exists(select 1 from jsonb_array_elements(public.school_calendar()->'exams') e where (e->>'id')::uuid=ex and (e->>'cancelled')::boolean) then raise exception 'TEST cancellation missing';end if;
 reset role;
 if not exists(select 1 from public.exam_presence where exam_id=ex and version_id=v2 and student_id=child) then raise exception 'TEST cancellation destroyed presence';end if;
 if not exists(select 1 from public.exam_schedule_events where exam_id=ex and action='published' and old_value->>'id'=v1::text and new_value->>'id'=v2::text) then raise exception 'TEST version audit';end if;
 raise exception using errcode='ZX002',message='fixtures passed';exception when sqlstate 'ZX002' then null;end;
end $test$;
select 'PASS exam drafts/official versions/Censeur republication, admin cannot auto-publish, rejection/cancellation history, family/session/teacher/tenant isolation, notifications, closures/conflicts/period dates and versioned kiosk first arrival; fixtures rolled back' as result;
