-- Isolated fixtures: the deliberate final exception rolls back this entire
-- subtransaction. Any failed assertion propagates and aborts the migration.
do $test$
declare owner_a uuid:=gen_random_uuid(); owner_b uuid:=gen_random_uuid(); teacher uuid:=gen_random_uuid(); guardian uuid:=gen_random_uuid(); learner uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid();
 spare uuid; other_subject uuid; grade_id uuid; activation text; device jsonb; payload jsonb; next_year uuid; next_class uuid; request_id uuid; a uuid; b uuid; yr uuid; cls uuid; other_cls uuid; subject uuid; child1 uuid; child2 uuid; other_child uuid; member uuid; invitation jsonb; invited jsonb; pid uuid; period uuid; n integer; rowcount integer; old_id text; failed boolean;
begin
 begin
  insert into auth.users(id,email,email_confirmed_at,role,aud) select id,id::text||'@example.invalid',now(),'authenticated','authenticated' from unnest(array[owner_a,owner_b,teacher,guardian,learner,outsider])id;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  set local role authenticated;
  a:=public.create_school_onboarding('Verification A',gen_random_uuid()::text);
  if not exists(select 1 from public.schools where id=a and owner_user_id=owner_a) then raise exception 'TEST owner creation'; end if;
  yr:=public.create_academic_year('Verification',date '2026-01-01',date '2026-12-31',true);
  perform public.activate_school_section(yr,'preschool');
  perform public.activate_school_section(yr,'preschool');
  if (select count(*) from public.classes where school_id=a and academic_year_id=yr)<>3 then raise exception 'TEST section activation duplicated classes'; end if;
  perform public.activate_school_section(yr,'preschool',false);
  if exists(select 1 from public.classes where school_id=a and enabled) then raise exception 'TEST section deactivation'; end if;
  period:=public.activate_grading_period(yr,'Verification period','V1','2026-01-01','2026-03-31',array['fundamental']);
  if public.activate_grading_period(yr,'Verification period','V1','2026-01-01','2026-03-31',array['fundamental'])<>period then raise exception 'TEST period duplicated'; end if;
  cls:=public.create_class(yr,'Class A','AF7');
  update public.classes set student_portal_allowed=true where id=cls;
  other_cls:=public.create_class(yr,'Class B','AF2');
  subject:=public.create_subject('Verification Mathematics','VERIFY');
  child1:=public.save_student_record(jsonb_build_object('first_name','Child','last_name','One','class_id',cls,'guardian_name','Guardian','guardian_email',guardian::text||'@example.invalid'));
  child2:=public.save_student_record(jsonb_build_object('first_name','Child','last_name','Two','class_id',cls,'guardian_name','Guardian','guardian_email',guardian::text||'@example.invalid'));
  other_child:=public.save_student_record(jsonb_build_object('first_name','Other','last_name','Child','class_id',other_cls));
  if (select count(*) from public.parents where school_id=a)<>1 then raise exception 'TEST guardian deduplication'; end if;
  select atechos_id into old_id from public.students where id=child1;
  perform public.save_student_record(jsonb_build_object('first_name','Corrected','last_name','One','class_id',cls,'date_of_birth','2013-02-10','place_of_birth','Verification city','address','Verification address','sex','F'),child1);
  if not exists(select 1 from public.students where id=child1 and date_of_birth='2013-02-10' and place_of_birth='Verification city' and address='Verification address' and sex='F') then raise exception 'TEST student demographics'; end if;
  if not exists(select 1 from public.students where id=child1 and atechos_id=old_id and photo_url is null) then raise exception 'TEST stable ID and optional photo'; end if;
  perform public.save_student_record(jsonb_build_object('first_name','Corrected','last_name','One','class_id',other_cls),child1);
  if not exists(select 1 from public.enrollments where student_id=child1 and class_id=cls and status='transferred') or not exists(select 1 from public.enrollments where student_id=child1 and class_id=other_cls and status='active') then raise exception 'TEST transfer did not move active class'; end if;
  perform public.save_student_record(jsonb_build_object('first_name','Corrected','last_name','One','class_id',cls,'date_of_birth','2013-02-10','place_of_birth','Verification city','address','Verification address','sex','F'),child1);
  if not exists(select 1 from public.students where id=child1 and date_of_birth='2013-02-10' and place_of_birth='Verification city' and address='Verification address' and sex='F') then raise exception 'TEST student demographics'; end if;
  if (select count(*) from public.enrollments where student_id=child1 and status='active')<>1 then raise exception 'TEST duplicate active class'; end if;
  if not exists(select 1 from public.get_student_records(child1) r where r ? 'nis') then raise exception 'TEST admin NIS access'; end if;
  invitation:=public.create_school_invitation(outsider::text||'@example.invalid','Director','director');
  perform set_config('request.jwt.claim.sub',outsider::text,true);
  perform public.accept_school_invitation(invitation->>'token');
  pid:=public.save_parent_for_student(child1,'Guardian',guardian::text||'@example.invalid');
  if public.save_parent_for_student(child2,'Guardian',guardian::text||'@example.invalid')<>pid then raise exception 'TEST duplicate parent'; end if;
  invitation:=public.create_school_invitation(guardian::text||'@example.invalid','Guardian','parent',null,pid);
  failed:=false; begin perform public.create_school_invitation(teacher::text||'@example.invalid','Teacher','teacher'); exception when others then failed:=true; end;
  if not failed then raise exception 'TEST director grants staff'; end if;
  perform set_config('request.jwt.claim.sub',guardian::text,true);
  perform public.accept_school_invitation(invitation->>'token');
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  invitation:=public.create_school_invitation(teacher::text||'@example.invalid','Teacher','teacher');
  perform set_config('request.jwt.claim.sub',outsider::text,true);
  failed:=false;
  begin perform public.accept_school_invitation(invitation->>'token'); exception when others then failed:=true; end;
  if not failed then raise exception 'TEST wrong email accepted'; end if;
  perform set_config('request.jwt.claim.sub',teacher::text,true);
  perform public.accept_school_invitation(invitation->>'token');
  failed:=false;
  begin perform public.accept_school_invitation(invitation->>'token'); exception when others then failed:=true; end;
  if not failed then raise exception 'TEST invitation replay'; end if;
  if exists(select 1 from public.students where school_id=a) then raise exception 'TEST unassigned teacher sees students'; end if;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  perform public.assign_subject_to_class(cls,subject,teacher);
  invitation:=public.create_school_invitation(guardian::text||'@example.invalid','Guardian','parent',null,(select id from public.parents where school_id=a));
  invited:=public.create_school_invitation(learner::text||'@example.invalid','Learner','student',child1);
  perform set_config('request.jwt.claim.sub',teacher::text,true);
  if (select count(*) from public.students where school_id=a)<>2 then raise exception 'TEST assigned teacher scope'; end if;
  failed:=false; begin perform nis from public.students where id=child1; exception when insufficient_privilege then failed:=true; end;
  if not failed then raise exception 'TEST teacher reads NIS'; end if;
  if exists(select 1 from public.get_student_records(child1) r where r ? 'nis') then raise exception 'TEST teacher RPC exposes NIS'; end if;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  other_subject:=public.create_subject('Unassigned subject','UNASSIGNED');
  insert into public.class_subjects(school_id,class_id,subject_id) values(a,cls,other_subject);
  perform set_config('request.jwt.claim.sub',teacher::text,true);
  if exists(select 1 from public.subjects where id=other_subject) or exists(select 1 from public.class_subjects where subject_id=other_subject) then raise exception 'TEST teacher sees another subject in own class'; end if;
  if not exists(select 1 from public.subjects where id=subject) then raise exception 'TEST assigned subject hidden'; end if;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  delete from public.class_subjects where subject_id=other_subject;
  perform set_config('request.jwt.claim.sub',teacher::text,true);


  perform public.create_grade(child1,subject,cls,'Verification',8,10,null,period);
  select id into grade_id from public.grades where student_id=child1 and subject_id=subject and grading_period_id=period;
  failed:=false;begin perform public.grade_publication_review();exception when others then failed:=true;end;
  if not failed then raise exception 'TEST teacher reviews school grades';end if;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  perform public.set_category_grade_deadline(period,'fundamental',now()-interval '1 minute','2026-02-01','2026-02-05');
  perform set_config('request.jwt.claim.sub',teacher::text,true);
  failed:=false;begin perform public.create_grade(child1,subject,cls,'Blocked',9,10,null,period);exception when others then if sqlerrm='grade_deadline_passed' then failed:=true;else raise;end if;end;
  if not failed then raise exception 'TEST teacher ignores deadline';end if;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  select id into member from public.school_members where school_id=a and user_id=teacher and role='teacher';
  perform public.manage_school_member(member,'role','secretary');
  perform set_config('request.jwt.claim.sub',teacher::text,true);
  payload:=public.grade_publication_review();
  if not exists(select 1 from jsonb_array_elements(payload->'rows') v where v->>'id'=grade_id::text and v->>'code'=old_id) then raise exception 'TEST secretary review';end if;
  failed:=false;begin perform public.publish_reviewed_grades(array[grade_id,gen_random_uuid()]);exception when others then failed:=true;end;
  if not failed or exists(select 1 from public.grades where id=grade_id and published) then raise exception 'TEST invalid publication partial write';end if;
  if public.publish_reviewed_grades(array[grade_id])<>1 then raise exception 'TEST secretary publication';end if;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  perform public.manage_school_member(member,'role','surveillant');
  perform set_config('request.jwt.claim.sub',teacher::text,true);
  if public.publish_reviewed_grades(array[grade_id])<>0 then raise exception 'TEST repeat publication';end if;
  perform set_config('request.jwt.claim.sub',outsider::text,true);
  -- The fixture outsider is a director of this school and may review.
  perform public.grade_publication_review();
  perform set_config('request.jwt.claim.sub',owner_b::text,true);
  failed:=false;begin perform public.publish_reviewed_grades(array[grade_id]);exception when others then failed:=true;end;
  if not failed then raise exception 'TEST external school publication';end if;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  activation:=public.issue_student_activation(child1);
  set local role anon;
  device:=public.student_device_login(old_id,'Corrected One',activation,'648239');
  if public.student_portal_overview('invalid') is not null then raise exception 'TEST forged overview';end if;
  payload:=public.student_portal_overview(device->>'token');
  if payload->'student'->>'class_name'<>'Class A' or payload->'student'->>'academic_year'<>'Verification' or jsonb_array_length(payload->'grades')<>1 then raise exception 'TEST profile or published bulletin';end if;
  if not exists(select 1 from jsonb_array_elements(payload->'periods') p where p->>'exam_start'='2026-02-01') then raise exception 'TEST exam dates';end if;
  reset role;
  update public.students set photo_url='other-school/other-photo.jpg' where id=child1;
  set local role anon;
  payload:=public.student_portal_overview(device->>'token');
  if payload->'student'->>'photo_path' is not null then raise exception 'TEST unsafe photo path';end if;
  reset role;

  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  set local role authenticated;
  perform public.assign_subject_to_class(cls,other_subject,null);
  update public.grades set score=240,max_score=300 where id=grade_id;
  perform public.create_grade(child1,other_subject,cls,'Points',50,100,null,period);
  payload:=public.get_report_card(child1);
  if (payload->'cards'->0->>'complete')::boolean or payload->'cards'->0->>'average' is not null then raise exception 'TEST draft must make report incomplete';end if;
  perform public.publish_reviewed_grades(array(select id from public.grades where student_id=child1 and class_id=cls));
  payload:=public.get_report_card(child1);
  if abs((payload->'cards'->0->>'average')::numeric-7.25)>0.00001 or (payload->'cards'->0->>'status')<>'passed' then raise exception 'TEST points-weighted average 290/400';end if;
  if payload->'cards'->0->>'position' is not null then raise exception 'TEST incomplete cohort ranked';end if;
  perform public.create_grade(child2,subject,cls,'Points',270,300,null,period);
  perform public.create_grade(child2,other_subject,cls,'Points',90,100,null,period);
  perform public.publish_reviewed_grades(array(select id from public.grades where student_id=child2 and class_id=cls));
  payload:=public.get_report_card(child1);
  if (payload->'cards'->0->>'position')::int<>2 or (payload->'cards'->0->>'class_size')::int<>2 then raise exception 'TEST class rank';end if;
  if public.get_report_card(child2)->'cards'->0->>'status'<>'excellent' then raise exception 'TEST excellent boundary';end if;
  update public.grades set score=max_score*0.6 where student_id=child1 and class_id=cls;
  if public.get_report_card(child1)->'cards'->0->>'status'<>'passed' then raise exception 'TEST pass boundary';end if;
  update public.grades set score=max_score*0.59 where student_id=child1 and class_id=cls;
  if public.get_report_card(child1)->'cards'->0->>'status'<>'not_passed' then raise exception 'TEST fail boundary';end if;
  update public.grades set score=max_score*0.3 where student_id=child1 and class_id=cls;
  if public.get_report_card(child1)->'cards'->0->>'status'<>'parent_meeting' then raise exception 'TEST parent meeting boundary';end if;
  update public.grades set score=max_score*0.9 where student_id=child1 and class_id=cls;
  if (public.get_report_card(child1)->'cards'->0->>'position')::int<>1 or (public.get_report_card(child2)->'cards'->0->>'position')::int<>1 then raise exception 'TEST tied rank';end if;
  spare:=public.create_subject('Missing active subject','MISSING');
  perform public.assign_subject_to_class(cls,spare,null);
  if (public.get_report_card(child1)->'cards'->0->>'complete')::boolean then raise exception 'TEST missing active subject ignored';end if;
  update public.subjects set active=false where id=spare;
  if not (public.get_report_card(child1)->'cards'->0->>'complete')::boolean then raise exception 'TEST inactive subject included';end if;
  perform public.create_grade(child1,subject,cls,'Additional control',0,100,null,period);
  update public.grades set assessment_weight=50 where student_id=child1 and assessment_name='Additional control';
  perform public.publish_reviewed_grades(array(select id from public.grades where student_id=child1 and class_id=cls));
  if abs((public.get_report_card(child1)->'cards'->0->>'average')::numeric-8)>0.00001 then raise exception 'TEST multiple assessments weighted points';end if;
  perform public.staff_mark_attendance(child1,cls,'late');
  perform public.staff_mark_attendance(child2,cls,'absent');
  payload:=public.get_report_card(child1);
  if jsonb_array_length(payload->'attendance')<>1 or payload->'attendance'->0->>'status'<>'late' then raise exception 'TEST attendance isolation';end if;
  perform set_config('request.jwt.claim.sub',guardian::text,true);
  payload:=public.get_report_card(child1);
  if payload->'student'->>'id'<>child1::text or payload->'cards'->0->>'exam_start'<>'2026-02-01' then raise exception 'TEST parent report exam dates';end if;
  failed:=false;begin perform public.get_report_card(other_child);exception when others then failed:=true;end;
  if not failed then raise exception 'TEST parent reads unrelated report';end if;
  failed:=false;begin perform public.report_students();exception when others then failed:=true;end;
  if not failed then raise exception 'TEST parent lists school roster';end if;
  perform set_config('request.jwt.claim.sub',owner_b::text,true);
  failed:=false;begin perform public.get_report_card(child1);exception when others then failed:=true;end;
  if not failed then raise exception 'TEST other school reads report';end if;
  set local role anon;
  payload:=public.student_portal_overview(device->>'token')->'report';
  if payload->'student'->>'id'<>child1::text or (payload->'cards'->0->>'average')::numeric<>8 then raise exception 'TEST student shared calculation';end if;
  if exists(select 1 from jsonb_array_elements(payload->'cards') c where c ? 'students') then raise exception 'TEST report exposes classmates';end if;
  reset role;
  raise exception using errcode='ZX001',message='Fixture rollback';
 exception when sqlstate 'ZX001' then null;
 end;
end $test$;
