do $test$
declare owner_id uuid:=gen_random_uuid();director_id uuid:=gen_random_uuid();reviewer uuid:=gen_random_uuid();teacher uuid:=gen_random_uuid();secretary_id uuid:=gen_random_uuid();outside_id uuid:=gen_random_uuid();sid uuid;mid uuid;inv jsonb;rid uuid;denied boolean;result text;workspace jsonb;reviewer_member uuid;yr uuid;cls uuid;subject_id uuid;
begin begin
 insert into auth.users(id,email,email_confirmed_at,role,aud) select id,id::text||'@example.invalid',now(),'authenticated','authenticated' from unnest(array[owner_id,director_id,reviewer,teacher,secretary_id,outside_id]) id;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);set local role authenticated;
 sid:=public.create_school_onboarding('Approval fixture',gen_random_uuid()::text);
 inv:=public.create_school_invitation(director_id::text||'@example.invalid','Director','director');
 perform set_config('request.jwt.claim.sub',director_id::text,true);perform public.accept_school_invitation(inv->>'token');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);inv:=public.create_school_invitation(reviewer::text||'@example.invalid','Censeur','censeur');
 perform set_config('request.jwt.claim.sub',reviewer::text,true);perform public.accept_school_invitation(inv->>'token');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);inv:=public.create_school_invitation(teacher::text||'@example.invalid','Teacher','teacher');
 perform set_config('request.jwt.claim.sub',teacher::text,true);perform public.accept_school_invitation(inv->>'token');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);inv:=public.create_school_invitation(secretary_id::text||'@example.invalid','Secretary','secretary');
 perform set_config('request.jwt.claim.sub',secretary_id::text,true);perform public.accept_school_invitation(inv->>'token');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);select id into mid from public.school_members where school_id=sid and user_id=teacher and role='teacher';
 yr:=public.create_academic_year('Approval year','2026-01-01','2026-12-31',true);cls:=public.create_class(yr,'Approval class','AF1');subject_id:=public.create_subject('Approval subject','APP');perform public.assign_subject_to_class(cls,subject_id,teacher);
 denied:=false;begin perform public.manage_school_member(mid,'disable');exception when others then denied:=sqlerrm='teacher_access_requires_two_approvals';end;if not denied then raise exception 'TEST old disable bypass';end if;
 denied:=false;begin perform public.manage_school_member(mid,'role','director');exception when others then denied:=sqlerrm='teacher_access_requires_two_approvals';end;if not denied then raise exception 'TEST role bypass';end if;
 denied:=false;begin perform public.manage_school_member(mid,'remove');exception when others then denied:=sqlerrm='teacher_access_requires_two_approvals';end;if not denied then raise exception 'TEST remove bypass';end if;
 rid:=public.request_teacher_access_change(mid,'disable','Fixture decision');
 if not exists(select 1 from public.school_members where id=mid and enabled) then raise exception 'TEST request disabled teacher';end if;
 result:=public.review_school_approval(rid,'approve');if result<>'pending' then raise exception 'TEST one approval applied';end if;
 if not exists(select 1 from public.school_members where id=mid and enabled) then raise exception 'TEST first approval disabled teacher';end if;
 denied:=false;begin perform public.review_school_approval(rid,'approve');exception when others then denied:=sqlerrm='already_voted';end;if not denied then raise exception 'TEST repeat voter';end if;
 perform set_config('request.jwt.claim.sub',secretary_id::text,true);
 denied:=false;begin perform public.review_school_approval(rid,'approve');exception when others then denied:=sqlerrm='not_authorized';end;if not denied then raise exception 'TEST secretary vote';end if;
 denied:=false;begin perform public.school_approval_workspace();exception when others then denied:=sqlerrm='not_authorized';end;if not denied then raise exception 'TEST secretary confidential audit';end if;
 perform set_config('request.jwt.claim.sub',teacher::text,true);
 denied:=false;begin perform public.review_school_approval(rid,'approve');exception when others then denied:=sqlerrm='not_authorized';end;if not denied then raise exception 'TEST target vote';end if;
 perform set_config('request.jwt.claim.sub',reviewer::text,true);result:=public.review_school_approval(rid,'approve');if result<>'applied' then raise exception 'TEST second approval missing';end if;
 perform set_config('request.jwt.claim.sub',teacher::text,true);
 if private.teaches(cls,subject_id) then raise exception 'TEST disabled teacher retained subject access';end if;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 if exists(select 1 from public.school_members where id=mid and enabled) then raise exception 'TEST final not disabled';end if;
 workspace:=public.school_approval_workspace();
 if (workspace->'requests'->0->>'status')<>'applied' or jsonb_array_length(workspace->'requests'->0->'votes')<>2 then raise exception 'TEST audit votes';end if;
 denied:=false;begin update public.school_approval_votes set decision='reject' where request_id=rid;exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'TEST direct vote overwrite';end if;
 perform public.manage_school_member(mid,'enable');
 rid:=public.request_teacher_access_change(mid,'disable','Removed voter fixture');
 perform set_config('request.jwt.claim.sub',reviewer::text,true);perform public.review_school_approval(rid,'approve');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);select id into reviewer_member from public.school_members where school_id=sid and user_id=reviewer and role='censeur';perform public.manage_school_member(reviewer_member,'disable');
 perform set_config('request.jwt.claim.sub',director_id::text,true);result:=public.review_school_approval(rid,'approve');if result<>'pending' then raise exception 'TEST revoked approver counted';end if;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);result:=public.review_school_approval(rid,'approve');if result<>'applied' then raise exception 'TEST valid replacement approver';end if;
 perform public.manage_school_member(mid,'enable');perform public.manage_school_member(reviewer_member,'enable');
 rid:=public.request_teacher_access_change(mid,'disable','Cancellation fixture');perform public.review_school_approval(rid,'cancel','No longer needed');
 if not exists(select 1 from public.school_members where id=mid and enabled) then raise exception 'TEST cancellation modified access';end if;
 rid:=public.request_teacher_access_change(mid,'disable','Reject fixture');
 perform set_config('request.jwt.claim.sub',director_id::text,true);perform public.review_school_approval(rid,'reject','Do not proceed');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 if not exists(select 1 from public.school_members where id=mid and enabled) then raise exception 'TEST rejection changed access';end if;
 rid:=public.request_teacher_access_change(mid,'role','Role fixture','parent');perform public.review_school_approval(rid,'approve');
 perform set_config('request.jwt.claim.sub',director_id::text,true);perform public.review_school_approval(rid,'approve');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 if not exists(select 1 from public.school_members where id=mid and role='parent' and enabled) or not exists(select 1 from public.parents where school_id=sid and user_id=teacher) then raise exception 'TEST approved parent role';end if;
 perform set_config('request.jwt.claim.sub',outside_id::text,true);perform public.create_school_onboarding('Outside approval school',gen_random_uuid()::text);
 denied:=false;begin perform public.review_school_approval(rid,'approve');exception when others then denied:=sqlerrm='not_authorized';end;if not denied then raise exception 'TEST cross school decision';end if;
 reset role;raise exception using errcode='ZX004',message='fixtures passed';exception when sqlstate 'ZX004' then null;end;
end $test$;
select 'PASS two distinct approval votes, no request/first-vote deactivation, old disable/role/delete bypass blocked, secretary/target/cross-school denied, reject preserves access, approved parent role, immutable votes, revoked approver excluded, cancellation and disabled subject access; fixtures rolled back' as result;
