-- Isolated fixtures: the deliberate final exception rolls back this entire
-- subtransaction. Any failed assertion propagates and aborts the migration.
do $test$
declare owner_a uuid:=gen_random_uuid(); owner_b uuid:=gen_random_uuid(); teacher uuid:=gen_random_uuid(); guardian uuid:=gen_random_uuid(); learner uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid();
 other_subject uuid; activation text; device jsonb; payload jsonb; next_year uuid; next_class uuid; request_id uuid; a uuid; b uuid; yr uuid; cls uuid; other_cls uuid; subject uuid; child1 uuid; child2 uuid; other_child uuid; member uuid; invitation jsonb; invited jsonb; pid uuid; period uuid; n integer; rowcount integer; old_id text; failed boolean;
begin
 begin
  insert into auth.users(id,email,email_confirmed_at,role,aud) select id,id::text||'@example.invalid',now(),'authenticated','authenticated' from unnest(array[owner_a,owner_b,teacher,guardian,learner,outsider])id;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  set local role authenticated;
  a:=public.create_school_onboarding('Verification A',gen_random_uuid()::text);
  if not exists(select 1 from public.schools where id=a and owner_user_id=owner_a) then raise exception 'TEST owner creation'; end if;
  yr:=public.create_academic_year('Verification',date '2026-01-01',date '2026-12-31',true);
  perform public.activate_school_section(yr,'preschool');
  perform public.activate_school_section(yr,'preschool');
  if (select count(*) from public.classes where school_id=a and academic_year_id=yr)<>3 then raise exception 'TEST section activation duplicated classes'; end if;
  perform public.activate_school_section(yr,'preschool',false);
  if exists(select 1 from public.classes where school_id=a and enabled) then raise exception 'TEST section deactivation'; end if;
  period:=public.activate_grading_period(yr,'Verification period','V1','2026-01-01','2026-03-31',array['fundamental']);
  if public.activate_grading_period(yr,'Verification period','V1','2026-01-01','2026-03-31',array['fundamental'])<>period then raise exception 'TEST period duplicated'; end if;
  cls:=public.create_class(yr,'Class A','AF7');
  update public.classes set student_portal_allowed=true where id=cls;
  other_cls:=public.create_class(yr,'Class B','AF2');
  subject:=public.create_subject('Verification Mathematics','VERIFY');
  child1:=public.save_student_record(jsonb_build_object('first_name','Child','last_name','One','class_id',cls,'guardian_name','Guardian','guardian_email',guardian::text||'@example.invalid'));
  child2:=public.save_student_record(jsonb_build_object('first_name','Child','last_name','Two','class_id',cls,'guardian_name','Guardian','guardian_email',guardian::text||'@example.invalid'));
  other_child:=public.save_student_record(jsonb_build_object('first_name','Other','last_name','Child','class_id',other_cls));
  if (select count(*) from public.parents where school_id=a)<>1 then raise exception 'TEST guardian deduplication'; end if;
  select r->>'atechos_id' into old_id from public.get_student_records(child1) r;
  perform public.save_student_record(jsonb_build_object('first_name','Corrected','last_name','One','class_id',cls,'date_of_birth','2013-02-10','place_of_birth','Verification city','address','Verification address','sex','F'),child1);
  if not exists(select 1 from public.students where id=child1 and date_of_birth='2013-02-10' and place_of_birth='Verification city' and address='Verification address' and sex='F') then raise exception 'TEST student demographics'; end if;
  if not exists(select 1 from public.get_student_records(child1) r where r->>'atechos_id'=old_id and r->>'photo_url' is null) then raise exception 'TEST stable ID and optional photo'; end if;
  perform public.save_student_record(jsonb_build_object('first_name','Corrected','last_name','One','class_id',other_cls),child1);
  if not exists(select 1 from public.enrollments where student_id=child1 and class_id=cls and status='transferred') or not exists(select 1 from public.enrollments where student_id=child1 and class_id=other_cls and status='active') then raise exception 'TEST transfer did not move active class'; end if;
  perform public.save_student_record(jsonb_build_object('first_name','Corrected','last_name','One','class_id',cls,'date_of_birth','2013-02-10','place_of_birth','Verification city','address','Verification address','sex','F'),child1);
  if not exists(select 1 from public.students where id=child1 and date_of_birth='2013-02-10' and place_of_birth='Verification city' and address='Verification address' and sex='F') then raise exception 'TEST student demographics'; end if;
  if (select count(*) from public.enrollments where student_id=child1 and status='active')<>1 then raise exception 'TEST duplicate active class'; end if;
  if not exists(select 1 from public.get_student_records(child1) r where r ? 'nis') then raise exception 'TEST admin NIS access'; end if;
  invitation:=public.create_school_invitation(outsider::text||'@example.invalid','Director','director');
  perform set_config('request.jwt.claim.sub',outsider::text,true);
  perform public.accept_school_invitation(invitation->>'token');
  pid:=public.save_parent_for_student(child1,'Guardian',guardian::text||'@example.invalid');
  if public.save_parent_for_student(child2,'Guardian',guardian::text||'@example.invalid')<>pid then raise exception 'TEST duplicate parent'; end if;
  invitation:=public.create_school_invitation(guardian::text||'@example.invalid','Guardian','parent',null,pid);
  failed:=false; begin perform public.create_school_invitation(teacher::text||'@example.invalid','Teacher','teacher'); exception when others then failed:=true; end;
  if not failed then raise exception 'TEST director grants staff'; end if;
  perform set_config('request.jwt.claim.sub',guardian::text,true);
  perform public.accept_school_invitation(invitation->>'token');
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  invitation:=public.create_school_invitation(teacher::text||'@example.invalid','Teacher','teacher');
  perform set_config('request.jwt.claim.sub',outsider::text,true);
  failed:=false;
  begin perform public.accept_school_invitation(invitation->>'token'); exception when others then failed:=true; end;
  if not failed then raise exception 'TEST wrong email accepted'; end if;
  perform set_config('request.jwt.claim.sub',teacher::text,true);
  perform public.accept_school_invitation(invitation->>'token');
  failed:=false;
  begin perform public.accept_school_invitation(invitation->>'token'); exception when others then failed:=true; end;
  if not failed then raise exception 'TEST invitation replay'; end if;
  if exists(select 1 from public.students where school_id=a) then raise exception 'TEST unassigned teacher sees students'; end if;
  perform set_config('request.jwt.claim.sub',owner_a::text,true);
  perform public.assign_subject_to_class(cls,subject,teacher);
  invitation:=public.create_school_invitation(guardian::text||'@example.invalid','Guardian','parent',null,(select id from public.parents where school_id=a));
  invited:=public.create_school_invitation(learner::text||'@example.invalid','Learner','student',child1);
  perform set_config('request.jwt.claim.sub',teacher::text,true);
  if (select count(*) from public.students where school_id=a)<>2 then raise exception 'TEST assigned teacher scope'; end if;
  failed:=false; begin perform nis from public.students where id=child1; exception when insufficient_privilege then failed:=true; end;
  if not failed then raise exception 'TEST teacher reads NIS'; end if;
  if exists(select 1 from public.get_student_records(child1) r where r ? 'nis') then raise exception 'TEST teacher RPC exposes NIS'; end if;

  request_id:=public.create_assignment(cls,subject,'Teacher task',null,now()+interval '1 day',null,null,null);
  if exists(select 1 from jsonb_array_elements(public.assignment_roster(request_id)) r where r->>'code' is not null) then raise exception 'TEST teacher assignment ID';end if;
  perform public.create_grade(child1,subject,cls,'Test',8,10,null,period);
  if exists(select 1 from public.get_student_records(child1) r where r ? 'atechos_id' or r ? 'student_code') then raise exception 'TEST teacher RPC reveals ID';end if;
  failed:=false;begin perform atechos_id from public.students where id=child1;exception when insufficient_privilege then failed:=true;end;
  if not failed then raise exception 'TEST teacher direct ID';end if;
  failed:=false;begin perform student_code from public.students where id=child1;exception when insufficient_privilege then failed:=true;end;
  if not failed then raise exception 'TEST teacher school code alias';end if;
  failed:=false;begin perform private.mark_missing_attendance('2026-09-25 09:00 America/Port-au-Prince');exception when insufficient_privilege then failed:=true;end;
  if not failed then raise exception 'TEST teacher runs automatic attendance';end if;
  reset role;
  perform private.mark_missing_attendance('2026-09-25 08:59:59 America/Port-au-Prince');
  if exists(select 1 from public.attendance where student_id=child1) then raise exception 'TEST before 9AM';end if;
  perform private.mark_missing_attendance('2026-09-25 09:00 America/Port-au-Prince');
  if not exists(select 1 from public.attendance where student_id=child1 and attendance_date='2026-09-25' and status='absent' and check_in_at is null) then raise exception 'TEST 9AM absence';end if;
  perform private.mark_missing_attendance('2026-09-25 10:00 America/Port-au-Prince');
  if (select count(*) from public.attendance_events where student_id=child1 and source='SYSTEM')<>1 then raise exception 'TEST duplicate event';end if;
  perform private.mark_missing_attendance('2026-09-26 09:00 America/Port-au-Prince');
  if exists(select 1 from public.attendance where student_id=child1 and attendance_date='2026-09-26') then raise exception 'TEST Saturday absence';end if;
  insert into public.school_closures values(a,'2026-09-28','Approved school closure');
  perform private.mark_missing_attendance('2026-09-28 09:00 America/Port-au-Prince');
  if exists(select 1 from public.attendance where student_id=child1 and attendance_date='2026-09-28') then raise exception 'TEST approved closure absence';end if;
  insert into public.attendance(school_id,student_id,class_id,attendance_date,status,check_in_at) values(a,child1,cls,'2026-09-29','late','2026-09-29 07:55 America/Port-au-Prince');
  perform private.mark_missing_attendance('2026-09-29 09:00 America/Port-au-Prince');
  if not exists(select 1 from public.attendance where student_id=child1 and attendance_date='2026-09-29' and status='late' and check_in_at is not null) then raise exception 'TEST existing check-in overwritten';end if;
  perform private.mark_missing_attendance('2027-01-01 09:00 America/Port-au-Prince');
  if exists(select 1 from public.attendance where student_id=child1 and attendance_date='2027-01-01') then raise exception 'TEST outside school year';end if;
  raise exception using errcode='ZX001',message='fixtures passed';
 exception when sqlstate 'ZX001' then null;end;
end $test$;
select 'PASS teacher privacy and 9AM automatic absence, weekend, closure, duplicates, existing presence, academic dates' as result;
