'use client'
import { T } from '@/components/translation-provider'
import { useState,type FormEvent } from 'react'
import { studentLogin } from './actions'
export default function StudentLogin() {
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[activation,setActivation]=useState(false)
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try {const result=await studentLogin(new FormData(e.currentTarget));if(result?.error)setError(result.error)}finally{setBusy(false)}}
 return <main className="mx-auto max-w-lg p-6"><h1 className="text-3xl font-bold"><T text="Student portal"/></h1><p className="my-4"><T text="Use your AtechOS ID and full name. For your first visit, ask the school for a private activation code."/></p><form onSubmit={submit} className="space-y-4"><label className="block">AtechOS ID<input required name="code" autoComplete="username" className="block w-full rounded border p-3" /></label><label className="block"><T text="Full name"/><input required name="name" className="block w-full rounded border p-3" /></label><label className="block"><input type="checkbox" checked={activation} onChange={e=>setActivation(e.target.checked)} /> <T text="First activation / reset"/></label><label className="block"><T text={activation?'Private activation code':'PIN'}/><input required name="secret" type="password" autoComplete="current-password" className="block w-full rounded border p-3" /></label>{activation && <label className="block"><T text="Create PIN (optional, 6–12 digits)"/><input name="pin" type="password" inputMode="numeric" pattern="[0-9]{6,12}" autoComplete="new-password" className="block w-full rounded border p-3" /><span className="text-sm"><T text="Without a PIN, access remains on this browser for 14 days. You will need a new school activation code on another device or after signing out."/></span></label>}{error && <p role="alert" className="text-red-700">{error}</p>}<button disabled={busy} className="rounded bg-blue-600 p-3 text-white"><T text="Sign in"/></button></form></main>
}
