'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {createClient} from '@/lib/supabase/client'
import {schoolSections} from '@/lib/school-catalog'
type Row={id:string;student:string;code:string;class_id:string;class:string;section:string;year_id:string;year:string;period_id:string;period:string;subject_id:string;subject:string;teacher_id:string;teacher:string;assessment:string;score:number;max_score:number;published:boolean}
type Period={id:string;name:string;year:string}
type Deadline={period_id:string;section:string;deadline:string;exam_start:string|null;exam_end:string|null}
export default function Publication(){
 const [rows,setRows]=useState<Row[]>([]),[periods,setPeriods]=useState<Period[]>([]),[deadlines,setDeadlines]=useState<Deadline[]>([]),[filters,setFilters]=useState<Record<string,string>>({}),[search,setSearch]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState<string[]|null>(null)
 const [period,setPeriod]=useState(''),[section,setSection]=useState('preschool'),[deadline,setDeadline]=useState(''),[examStart,setExamStart]=useState(''),[examEnd,setExamEnd]=useState('')
 async function load(){const {data,error}=await createClient().rpc('grade_publication_review');if(error){setError('Accès refusé ou chargement impossible.');return}setRows(data.rows||[]);setPeriods(data.periods||[]);setDeadlines(data.deadlines||[])}
 useEffect(()=>{void load()},[])
 const filtered=rows.filter(r=>Object.entries(filters).every(([k,v])=>!v||String(r[k as keyof Row]??'')===v)&&(!search||`${r.student} ${r.code}`.toLowerCase().includes(search.toLowerCase())))
 const pending=filtered.filter(r=>!r.published&&r.period_id)
 return <main className="mx-auto max-w-7xl space-y-5 p-6"><Link href="/dashboard">← Tableau de bord</Link><Link href="/dashboard/bulletins" className="ml-4 underline">Voir les carnets scolaires</Link><h1 className="text-3xl font-bold">Révision et publication des bulletins</h1><p>Les filtres déterminent les notes à publier. « Tout » inclut toutes les lignes correspondantes. Les notes déjà publiées sont conservées.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}{message&&<p role="status">{message}</p>}
 <section className="grid gap-3 rounded border p-4 md:grid-cols-3">{([['year_id','year','Année'],['period_id','period','Période'],['section','section','Catégorie'],['class_id','class','Classe'],['subject_id','subject','Matière'],['teacher_id','teacher','Professeur'],['published','published','Publication']] as const).map(([key,label,title])=><label key={key}>{title}<select className="block w-full rounded border p-2" value={filters[key]||''} onChange={e=>{setFilters({...filters,[key]:e.target.value});setReview(null)}}><option value="">Tout</option>{Array.from(new Map(rows.filter(r=>r[key]!==null).map(r=>[String(r[key]),key==='published'?(r.published?'Publié':'Brouillon'):key==='section'?(schoolSections.find(s=>s.code===r.section)?.name||r.section):String(r[label]||'Non renseigné')])).entries()).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>)}<label>Élève / AtechOS ID<input value={search} onChange={e=>{setSearch(e.target.value);setReview(null)}} className="block w-full rounded border p-2"/></label></section>
 <p>{filtered.length} notes affichées · {pending.length} à publier</p><button disabled={busy||!pending.length} onClick={()=>setReview(pending.map(r=>r.id))} className="rounded bg-blue-600 p-3 text-white disabled:opacity-40">Publier les notes filtrées</button>{review&&<div className="rounded border border-amber-400 p-4"><p>Confirmer la publication de {review.length} notes affichées ? Les élèves et leurs parents pourront les consulter.</p><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const {data,error}=await createClient().rpc('publish_reviewed_grades',{p_ids:review});if(error)setError(error.message);else{setMessage(`${data} notes publiées.`);setReview(null);await load()}}finally{setBusy(false)}}} className="mr-3 rounded bg-blue-600 p-2 text-white">Confirmer</button><button onClick={()=>setReview(null)}>Annuler</button></div>}
 <div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{['Élève / ID','Classe','Matière','Professeur','Période','Évaluation','Note','Statut'].map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t"><td className="p-2">{r.student}<div>{r.code}</div></td><td>{r.class}</td><td>{r.subject}</td><td>{r.teacher||'—'}</td><td>{r.period||'Période manquante'}</td><td>{r.assessment}</td><td>{r.score}/{r.max_score}</td><td>{r.published?'Publié':'Brouillon'}</td></tr>)}</tbody></table></div>
 <form className="space-y-3 rounded border p-4" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const {error}=await createClient().rpc('set_category_grade_deadline',{p_period:period,p_section:section,p_deadline:new Date(deadline).toISOString(),p_exam_start:examStart||null,p_exam_end:examEnd||null});if(error)setError(error.message);else{setMessage('Dates enregistrées.');await load()}}finally{setBusy(false)}}}><h2 className="text-xl font-bold">Date limite des notes et dates d’examens</h2><p>Choisissez une période et une catégorie. La date limite bloque la saisie/modification des notes des professeurs. Les dates d’examens sont visibles par les élèves concernés.</p><div className="grid gap-3 md:grid-cols-3"><label>Période<select required value={period} onChange={e=>setPeriod(e.target.value)} className="block w-full border p-2"><option value="">Choisir</option>{periods.map(p=><option key={p.id} value={p.id}>{p.year} · {p.name}</option>)}</select></label><label>Catégorie<select value={section} onChange={e=>setSection(e.target.value)} className="block w-full border p-2">{schoolSections.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select></label><label>Date limite (heure de cet appareil)<input required type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)} className="block w-full border p-2"/></label><label>Début des examens<input type="date" value={examStart} onChange={e=>setExamStart(e.target.value)} className="block border p-2"/></label><label>Fin des examens<input type="date" min={examStart} value={examEnd} onChange={e=>setExamEnd(e.target.value)} className="block border p-2"/></label></div><button disabled={busy} className="rounded border p-3">Enregistrer les dates</button>{deadlines.map(d=><p key={d.period_id+d.section}>{periods.find(p=>p.id===d.period_id)?.name} · {schoolSections.find(s=>s.code===d.section)?.name} · limite : {new Date(d.deadline).toLocaleString()} · examens : {d.exam_start||'—'} → {d.exam_end||'—'}</p>)}</form>
 </main>
}
