'use client'
import {useCallback,useEffect,useState} from 'react'
import {T,useLocale} from '@/components/translation-provider'
import {translate} from '@/lib/translations'
import {gradeStates,gradeError} from '@/lib/grade-workflow'
import Link from 'next/link'
import GradeHistory from '@/components/grade-history'
import GradeCorrections from '@/components/grade-corrections'
import BulletinPublication from '@/components/bulletin-publication'
import SchoolDateInput from '@/components/school-date-input'
import {schoolDateTime,schoolDateTimeToISO} from '@/lib/school-date'
import {createClient} from '@/lib/supabase/client'
import {schoolSections} from '@/lib/school-catalog'
type Row={workflow_state:string;id:string;student:string;code:string;class_id:string;class:string;section:string;year_id:string;year:string;period_id:string;period:string;subject_id:string;subject:string;teacher_id:string;teacher:string;assessment:string;score:number;max_score:number;published:boolean}
type Period={id:string;name:string;year:string}
type Deadline={period_id:string;section:string;deadline:string;exam_start:string|null;exam_end:string|null}
export default function Publication(){
 const locale=useLocale();const t=(text:string)=>translate(text,locale)
 const [rows,setRows]=useState<Row[]>([]),[periods,setPeriods]=useState<Period[]>([]),[deadlines,setDeadlines]=useState<Deadline[]>([]),[filters,setFilters]=useState<Record<string,string>>({}),[search,setSearch]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState<string[]|null>(null)
 const [reason,setReason]=useState('')
 async function reviewBatch(action:string){const ids=filtered.filter(r=>r.workflow_state==='submitted').map(r=>r.id);if(!ids.length||!window.confirm(t('Confirm this decision for the filtered submitted grades?')))return;setBusy(true);setError('');try{const {error}=await createClient().rpc('review_grades',{p_ids:ids,p_action:action,p_reason:reason||null});if(error)throw error;setReason('');await load()}catch(e){setError(gradeError(e))}finally{setBusy(false)}}
 const [period,setPeriod]=useState(''),[section,setSection]=useState('preschool'),[deadline,setDeadline]=useState('')
 const load=useCallback(async()=>{try{const {data,error}=await createClient().rpc('grade_publication_review');if(error)throw error;setRows(data.rows||[]);setPeriods(data.periods||[]);setDeadlines(data.deadlines||[])}catch{setRows([]);setPeriods([]);setDeadlines([]);setError('Unable to load review records. Verify your access.')}},[])
 useEffect(()=>{void load()},[load])
 const filtered=rows.filter(r=>Object.entries(filters).every(([k,v])=>!v||String(r[k as keyof Row]??'')===v)&&(!search||`${r.student} ${r.code}`.toLowerCase().includes(search.toLowerCase())))
 const pending=filtered.filter(r=>r.workflow_state==='reviewed'&&r.period_id)
 return <main className="mx-auto max-w-7xl space-y-5 p-6"><Link href="/dashboard"><T text="← Dashboard"/></Link><Link href="/dashboard/bulletins" className="ml-4 underline"><T text="View report cards"/></Link><h1 className="text-3xl font-bold"><T text="Grade review and publication"/></h1><p><T text="Filters define the selected grades. Only approved grades can be published. Existing published grades remain visible."/></p>{error&&<p role="alert" className="text-red-700"><T text={error}/></p>}{message&&<p role="status"><T text={message}/></p>}
 <section className="grid gap-3 rounded border p-4 md:grid-cols-3">{([['year_id','year','Academic year'],['period_id','period','Period'],['section','section','Section'],['class_id','class','Class'],['subject_id','subject','Subject'],['teacher_id','teacher','Teacher'],['workflow_state','workflow_state','Status']] as const).map(([key,label,title])=><label key={key}><T text={title}/><select className="block w-full rounded border p-2" value={filters[key]||''} onChange={e=>{setFilters({...filters,[key]:e.target.value});setReview(null)}}><option value=""><T text="All"/></option>{Array.from(new Map(rows.filter(r=>r[key]!==null).map(r=>[String(r[key]),key==='workflow_state'?t(gradeStates[r.workflow_state]||r.workflow_state):key==='section'?(schoolSections.find(s=>s.code===r.section)?.name||r.section):String(r[label]||t('Not specified'))])).entries()).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>)}<label><T text="Student / AtechOS ID"/><input value={search} onChange={e=>{setSearch(e.target.value);setReview(null)}} className="block w-full rounded border p-2"/></label></section>
 <section className="flex flex-wrap items-end gap-3 rounded-xl border bg-white p-4"><label><T text="Return reason"/><input value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000} className="block rounded border p-2"/></label><button disabled={busy||!filtered.some(r=>r.workflow_state==='submitted')} onClick={()=>reviewBatch('approve')} className="rounded bg-emerald-700 p-3 text-white disabled:opacity-40"><T text="Approve filtered submitted grades"/></button><button disabled={busy||reason.trim().length<3||!filtered.some(r=>r.workflow_state==='submitted')} onClick={()=>reviewBatch('return')} className="rounded border p-3 disabled:opacity-40"><T text="Return for correction"/></button></section><p>{filtered.length} <T text="grades displayed"/> · {pending.length} <T text="ready to publish"/></p><button disabled={busy||!pending.length} onClick={()=>setReview(pending.map(r=>r.id))} className="rounded bg-blue-600 p-3 text-white disabled:opacity-40"><T text="Publish filtered reviewed grades"/></button>{review&&<div className="rounded border border-amber-400 p-4"><p><T text="Confirm publication of selected grades? Families will be able to view them."/> ({review.length})</p><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const {error}=await createClient().rpc('publish_reviewed_grades',{p_ids:review});if(error)setError(gradeError(error));else{setMessage('Selected grades published.');setReview(null);await load()}}catch(e){setError(gradeError(e))}finally{setBusy(false)}}} className="mr-3 rounded bg-blue-600 p-2 text-white"><T text="Confirm"/></button><button onClick={()=>setReview(null)}><T text="Cancel"/></button></div>}
 <div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{['Student / AtechOS ID','Class','Subject','Teacher','Period','Assessment','Score','Status','History'].map(x=><th key={x} className="p-2"><T text={x}/></th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t"><td className="p-2">{r.student}<div>{r.code}</div></td><td>{r.class}</td><td>{r.subject}</td><td>{r.teacher||'—'}</td><td>{r.period||t('Missing period')}</td><td>{r.assessment}</td><td>{r.score}/{r.max_score}</td><td><T text={gradeStates[r.workflow_state]||r.workflow_state}/></td><td className="p-2 align-top"><GradeHistory gradeId={r.id}/></td></tr>)}</tbody></table></div>
 <GradeCorrections onChange={load}/><form className="space-y-3 rounded border p-4" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const {error}=await createClient().rpc('save_grade_deadline',{p_period:period,p_section:section,p_deadline:schoolDateTimeToISO(deadline)});if(error)setError(gradeError(error));else{setMessage('Deadline saved.');await load()}}catch(e){setError(gradeError(e))}finally{setBusy(false)}}}><h2 className="text-xl font-bold"><T text="Grade entry deadline"/></h2><p><T text="Choose a period and section. After the deadline, teachers cannot enter or change grades."/></p><div className="grid gap-3 md:grid-cols-3"><label><T text="Period"/><select required value={period} onChange={e=>setPeriod(e.target.value)} className="block w-full border p-2"><option value=""><T text="Choose"/></option>{periods.map(p=><option key={p.id} value={p.id}>{p.year} · {p.name}</option>)}</select></label><label><T text="Section"/><select value={section} onChange={e=>setSection(e.target.value)} className="block w-full border p-2">{schoolSections.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select></label><label><T text="Deadline (Haiti time)"/><SchoolDateInput required type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)} className="block w-full border p-2"/></label></div><button disabled={busy} className="rounded border p-3"><T text="Save deadline"/></button>{deadlines.map(d=><p key={d.period_id+d.section}>{periods.find(p=>p.id===d.period_id)?.name} · {schoolSections.find(s=>s.code===d.section)?.name} · <T text="Deadline"/> : {schoolDateTime(d.deadline)}</p>)}</form>
 <BulletinPublication/></main>
}
