import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import vm from 'node:vm'
import ts from 'typescript'
const exports={}
vm.runInNewContext(ts.transpileModule(readFileSync('src/lib/school-date.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{exports,Intl,Date})
assert.equal(exports.schoolDate('2026-09-25'),'25 Septanm 2026')
assert.equal(exports.schoolDate('2026-09-25T02:00:00Z'),'24 Septanm 2026')
assert.equal(exports.schoolTime('2026-09-25T13:00:00Z'),'09:00 AM')
assert.equal(exports.schoolTime('2026-12-25T18:00:00Z'),'01:00 PM')
assert.equal(exports.parseDateInput('25/09/2026'),'2026-09-25')
assert.equal(exports.parseDateInput('31/02/2026'),'')
assert.equal(exports.parseDateInput('09/25/2026'),'')
assert.equal(exports.dateWithinRange('2026-09-25','2026-09-01','2027-06-30'),true)
assert.equal(exports.dateWithinRange('2026-08-31','2026-09-01','2027-06-30'),false)
assert.equal(exports.dateWithinRange('2027-07-01','2026-09-01','2027-06-30'),false)
assert.equal(exports.dateWithinRange('2027-06-30T13:00','2026-09-01','2027-06-30'),true)
const picker=readFileSync('src/components/school-date-input.tsx','utf8')
assert.ok(picker.includes('months[locale]')&&picker.includes('weekdays[locale]'),'date picker exposes localized month and weekday choices')
assert.ok(picker.includes('datetime-local')&&picker.includes('AM / PM'),'date-time picker supports Haiti local AM/PM time')
assert.ok(picker.includes('disabled={!dateWithin(day,minDay,maxDay)}'),'days outside the selected year or period cannot be chosen')
assert.ok(picker.includes("placeholder={datetime?'DD/MM/YYYY hh:mm AM/PM':'DD/MM/YYYY'}"),'manual date entry preserves DD/MM/YYYY format')
assert.ok(picker.includes('name={undefined} value={text}')&&picker.includes('type="hidden" name={name} value={iso}'),'forms submit the ISO value while users see the localized date')
const exam=readFileSync('src/components/exam-calendar.tsx','utf8'),periods=readFileSync('src/app/dashboard/grading-periods/page.tsx','utf8'),assignments=readFileSync('src/app/dashboard/assignments/page.tsx','utf8'),publication=readFileSync('src/app/dashboard/publication/page.tsx','utf8'),attendance=readFileSync('src/app/dashboard/attendance/page.tsx','utf8')
assert.ok(exam.includes('min={selectedPeriod?.start_date||cls?.year_start}')&&exam.includes('max={selectedPeriod?.end_date||cls?.year_end}'),'exam dates are bounded to their selected period and academic year')
assert.ok(periods.includes('min={selectedYear?.start_date} max={selectedYear?.end_date}'),'grading periods stay inside the selected academic year')
assert.ok(assignments.includes('min={selectedPeriod?.start_date||selectedClass?.year_start}')&&assignments.includes('schoolDateTimeToISO(dueAt)'),'assignment deadlines use school-year limits and Haiti local time')
assert.ok(publication.includes('min={periods.find(p=>p.id===period)?.start_date}'),'grade-entry deadlines are limited to their selected period')
assert.ok(attendance.includes('min={selectedClass?.year_start} max={selectedClass?.year_end}'),'attendance date selection follows its class academic year')
assert.equal(exports.schoolDateTimeToISO('2026-09-25T09:00'),'2026-09-25T13:00:00.000Z')
assert.equal(exports.schoolDateTimeToISO('2026-12-25T09:00'),'2026-12-25T14:00:00.000Z')
console.log('PASS Haiti date picker: DD/MM/YYYY, month selection, AM/PM, range limits, school-year constraints and Haiti time conversion.')
