'use client'
import { T } from '@/components/translation-provider'
import Link from 'next/link'
import { useEffect,useState } from 'react'
import { createClient } from '@/lib/supabase/client'
type Student={id:string;first_name:string;last_name:string};type ClassRow={id:string;name:string};type AttendanceRow={id:string;student_id:string;status:string;late_minutes:number;check_in_at:string|null;check_out_at:string|null;notes:string|null}
export default function AttendancePage(){let supabase: ReturnType<typeof createClient> | null = null
  const getSupabase = () => {
    if (!supabase) supabase = createClient()
    return supabase
  };const [classes,setClasses]=useState<ClassRow[]>([]),[students,setStudents]=useState<Student[]>([]),[records,setRecords]=useState<Record<string,AttendanceRow>>({});const [classId,setClassId]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[loading,setLoading]=useState(true),[error,setError]=useState('')
async function loadClasses(){const {data,error}=await getSupabase().from('classes').select('id,name').eq('enabled',true).order('name');if(error)setError(error.message);const rows=(data||[]) as ClassRow[];setClasses(rows);if(!classId&&rows[0])setClassId(rows[0].id)}
async function loadRoster(){if(!classId)return;setLoading(true);setError('');const [er,ar]=await Promise.all([getSupabase().from('enrollments').select('student_id').eq('class_id',classId).eq('status','active'),getSupabase().from('attendance').select('id,student_id,status,late_minutes,check_in_at,check_out_at,notes').eq('class_id',classId).eq('attendance_date',date)]);if(er.error||ar.error){setError((er.error||ar.error)?.message||'Could not load attendance');setLoading(false);return}const studentIds=(er.data||[]).map(e=>e.student_id);const sr=studentIds.length?await getSupabase().from('students').select('id,first_name,last_name').in('id',studentIds):{data:[],error:null};if(sr.error)setError(sr.error.message);setStudents((sr.data||[]) as Student[]);const map:Record<string,AttendanceRow>={};(ar.data||[]).forEach((r:AttendanceRow)=>{map[r.student_id]=r});setRecords(map);setLoading(false)}
useEffect(()=>{loadClasses()},[]);useEffect(()=>{loadRoster()},[classId,date])
return <main className="min-h-screen bg-slate-50 p-6 md:p-10"><div className="mx-auto max-w-7xl"><header><Link href="/onboarding" className="text-sm font-semibold text-blue-600">AtechOS</Link><h1 className="mt-1 text-3xl font-bold text-slate-900"><T text="Attendance"/></h1><p className="mt-1 text-slate-500"><T text="Attendance is read-only. Students record check-in and check-out at the kiosk."/></p><Link href="/kiosk" className="mt-3 inline-block text-blue-600"><T text="Attendance Kiosk"/></Link></header>{error&&<p className="mt-6 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium"><T text="Class"/><select value={classId} onChange={e=>setClassId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3">{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-sm font-medium">Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3"/></label></div></section><section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="font-semibold">Daily roster</h2><p className="mt-1 text-sm text-slate-500">{students.length} student{students.length===1?'':'s'}</p></div>{loading?<p className="p-5 text-slate-500"><T text="Loading..."/></p>:students.length===0?<p className="p-5 text-slate-500">No active students are enrolled in this class yet.</p>:<div className="divide-y divide-slate-100">{students.map(student=>{const r=records[student.id];return <div key={student.id} className="flex flex-col gap-3 p-5 md:flex-row md:items-center md:justify-between"><div><p className="font-semibold text-slate-900">{student.first_name} {student.last_name}</p><p className="text-xs text-slate-500">{r?.check_in_at?`Check-in ${new Date(r.check_in_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`:'No check-in'}{r?.check_out_at?` · Check-out ${new Date(r.check_out_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`:''}</p></div><div className="flex flex-wrap gap-2"><span className="rounded-lg bg-slate-100 px-3 py-2 text-sm"><T text={r?.status||'No check-in'}/></span></div></div>})}</div>}</section></div></main>}
