'use client'

import Link from 'next/link'
import { useParams } from 'next/navigation'
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Student = { id:string; atechos_id:string; first_name:string; last_name:string; photo_url:string|null; nis:string|null; student_code:string; active:boolean; notes:string|null }
export default function StudentProfile() {
 const {id}=useParams<{id:string}>(); const db=createClient(); const [student,setStudent]=useState<Student|null>(null); const [error,setError]=useState(''); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false)
 async function load(){const {data,error}=await db.from('students').select('id,atechos_id,first_name,last_name,photo_url,nis,student_code,active,notes').eq('id',id).single();if(error)setError(error.message);else setStudent(data as Student)}
 useEffect(()=>{void load()},[id])
 async function upload(){if(!file||!student)return; if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){setError('Use a JPG, PNG or WebP image smaller than 5 MB.');return} setBusy(true);setError('');const {data:schoolId,error:schoolError}=await db.rpc('get_my_school_id');if(schoolError||!schoolId){setError(schoolError?.message||'School was not found.');setBusy(false);return}const ext=file.name.split('.').pop()||'jpg';const path=`${schoolId}/${student.id}-${Date.now()}.${ext}`;const upload=await db.storage.from('student-photos').upload(path,file,{contentType:file.type});if(upload.error){setError(upload.error.message);setBusy(false);return}const update=await db.rpc('update_student_photo_url',{p_student_id:student.id,p_photo_url:path});if(update.error)setError(update.error.message);else await load();setBusy(false)}
 return <main className="min-h-screen bg-slate-50 p-6 md:p-10"><section className="mx-auto max-w-2xl rounded-2xl border bg-white p-6"><Link href="/dashboard/students" className="text-blue-700">← Students</Link>{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}{student&&<><h1 className="mt-4 text-3xl font-bold">{student.first_name} {student.last_name}</h1><p className="mt-1 font-mono text-sm text-slate-600">{student.atechos_id}</p><dl className="mt-6 grid gap-4 sm:grid-cols-2"><div><dt className="text-sm text-slate-500">NISU</dt><dd>{student.nis||'—'}</dd></div><div><dt className="text-sm text-slate-500">School code</dt><dd>{student.student_code}</dd></div><div><dt className="text-sm text-slate-500">Status</dt><dd>{student.active?'Active':'Inactive'}</dd></div><div><dt className="text-sm text-slate-500">Photo</dt><dd>{student.photo_url?'Saved':'Not added'}</dd></div></dl><section className="mt-8 rounded-xl border p-4"><h2 className="font-semibold">Add or replace photo</h2><p className="mt-1 text-sm text-slate-600">Optional. The current student record remains valid without it.</p><input className="mt-3 block" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/><button disabled={!file||busy} onClick={upload} className="mt-3 rounded-xl bg-blue-600 px-4 py-2 text-white disabled:opacity-50">{busy?'Uploading…':'Save photo'}</button></section><Link href="/dashboard/badges" className="mt-6 inline-block text-blue-700">Open badge module</Link></>}</section></main>
}

