'use client'

import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Student={id:string;atechos_id:string;nis:string|null;first_name:string;last_name:string;photo_url:string|null}
type School={name:string;code:string;address:string|null;phone:string|null;logo_url:string|null}
type Badge={badge_uid:string;badge_type:string;active:boolean}

export default function StudentBadgePage(){
 const supabase=createClient(); const [student,setStudent]=useState<Student|null>(null); const [school,setSchool]=useState<School|null>(null); const [badge,setBadge]=useState<Badge|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
 useEffect(()=>{async function load(){const id=new URLSearchParams(window.location.search).get('student');if(!id){setError('Student ID is required.');setLoading(false);return}const schoolId=(await supabase.rpc('get_my_school_id')).data;const [s,sc,b]=await Promise.all([supabase.from('students').select('id,atechos_id,nis,first_name,last_name,photo_url').eq('id',id).single(),schoolId?supabase.from('schools').select('name,code,address,phone,logo_url').eq('id',schoolId).single():Promise.resolve({data:null,error:null}),supabase.from('student_badges').select('badge_uid,badge_type,active').eq('student_id',id).eq('active',true).maybeSingle()]);if(s.error||sc.error||b.error)setError((s.error||sc.error||b.error)?.message||'Could not load badge');setStudent(s.data as Student|null);setSchool(sc.data as School|null);setBadge(b.data as Badge|null);setLoading(false)}load()},[])
 if(loading)return <main className="p-10 text-center">Loading badge...</main>
 if(error||!student)return <main className="p-10 text-center text-red-700">{error||'Student not found.'}</main>
 return <main className="min-h-screen bg-slate-100 p-8"><div className="mx-auto max-w-md"><div className="mb-5 flex justify-between print:hidden"><a href="/dashboard/students" className="font-semibold text-blue-600">← Students</a><button onClick={()=>window.print()} className="rounded-xl bg-blue-600 px-4 py-2 font-semibold text-white">Print badge</button></div><article className="badge-card overflow-hidden rounded-2xl border border-slate-300 bg-white shadow-xl print:shadow-none"><div className="bg-blue-900 p-4 text-center text-white"><div className="flex items-center justify-center gap-3">{school?.logo_url&&<img src={school.logo_url} alt="" className="h-12 w-12 rounded-full object-contain bg-white"/>}<div><p className="text-xs font-semibold tracking-widest">{school?.code||'SCHOOL'}</p><h1 className="text-lg font-bold">{school?.name||'School'}</h1></div></div><p className="mt-2 text-xs tracking-wide">STUDENT IDENTIFICATION CARD</p></div><div className="p-5"><div className="flex gap-5"><div className="flex h-28 w-24 shrink-0 items-center justify-center overflow-hidden rounded-xl border border-slate-300 bg-slate-100">{student.photo_url?<img src={student.photo_url} alt="Student" className="h-full w-full object-cover"/>:<span className="text-xs text-slate-400">PHOTO</span>}</div><div className="min-w-0"><p className="text-xs uppercase tracking-wide text-slate-500">Student</p><h2 className="mt-1 text-xl font-bold text-slate-900">{student.first_name} {student.last_name}</h2><p className="mt-3 text-xs uppercase tracking-wide text-slate-500">AtechOS ID</p><p className="font-mono text-lg font-bold text-blue-800">{student.atechos_id}</p>{student.nis&&<p className="mt-1 text-xs text-slate-500">NISU: {student.nis}</p>}</div></div><div className="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-3 text-center"><p className="text-xs text-slate-500">Badge UID</p><p className="font-mono font-semibold">{badge?.badge_uid||'Not assigned'}</p><p className="mt-1 text-[10px] uppercase tracking-widest text-slate-400">{badge?.badge_type||'badge'}</p></div></div><div className="border-t border-slate-200 px-5 py-3 text-center text-[10px] text-slate-500">Property of {school?.name||'school'} · Present this card at the attendance kiosk.</div></article></div><style jsx global>{`@media print{@page{size:85.6mm 54mm;margin:0}.badge-card{width:85.6mm;height:54mm;border-radius:0}.badge-card img{print-color-adjust:exact;-webkit-print-color-adjust:exact}body{background:#fff!important}.badge-card{box-shadow:none!important}}`}</style></main>
}
