'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type ClassItem={id:string;name:string}
type Subject={id:string;name:string;code:string|null}
type Student={id:string;first_name:string;last_name:string;student_code:string|null}
type Grade={id:string;student_id:string;subject_id:string;class_id:string;assessment_name:string;score:number;max_score:number;note:string|null;grading_period_id:string|null;assessment_weight:number;graded_at?:string|null}
type Period={id:string;name:string;code:string;start_date:string;end_date:string;weight:number;is_active:boolean}
type GradingSettings={controls_per_period:number;passing_average:number}

export default function GradesPage(){
 const supabase=createClient();const [classes,setClasses]=useState<ClassItem[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[students,setStudents]=useState<Student[]>([]),[grades,setGrades]=useState<Grade[]>([]),[periods,setPeriods]=useState<Period[]>([])
 const [settings,setSettings]=useState<GradingSettings>({controls_per_period:4,passing_average:5})
 const [classId,setClassId]=useState(''),[subjectId,setSubjectId]=useState(''),[periodId,setPeriodId]=useState(''),[assessment,setAssessment]=useState(''),[maxScore,setMaxScore]=useState('10'),[assessmentWeight,setAssessmentWeight]=useState('100')
 const [scores,setScores]=useState<Record<string,string>>({}),[notes,setNotes]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 async function loadClasses(){const {data,error}=await supabase.from('classes').select('id,name').order('name');if(error)setError(error.message);setClasses((data||[]) as ClassItem[])}
 async function loadPeriods(){const {data,error}=await supabase.rpc('get_grading_periods');if(error)setError(error.message);const active=((data||[]) as Period[]).filter(p=>p.is_active);setPeriods(active);setPeriodId(v=>v||active[0]?.id||'')}
 async function loadSettings(){const {data,error}=await supabase.rpc('get_grading_settings');if(error)setError(error.message);const row=(Array.isArray(data)?data[0]:data) as GradingSettings|undefined;if(row)setSettings({controls_per_period:Number(row.controls_per_period)||4,passing_average:Number(row.passing_average)||5})}
 async function loadClass(id:string){setLoading(true);const [e,a]=await Promise.all([supabase.from('enrollments').select('student_id,students(id,first_name,last_name,student_code)').eq('class_id',id).eq('status','active').order('student_id'),supabase.from('class_subjects').select('subject_id,subjects(id,name,code)').eq('class_id',id).order('subject_id')]);if(e.error||a.error)setError((e.error||a.error)?.message||'Could not load class');setStudents(((e.data||[]) as Array<{students:Student|null}>).map(x=>x.students).filter(Boolean) as Student[]);setSubjects(((a.data||[]) as Array<{subjects:Subject|null}>).map(x=>x.subjects).filter(Boolean) as Subject[]);setSubjectId('');setGrades([]);setScores({});setNotes({});setLoading(false)}
 async function loadGrades(){if(!classId||!subjectId){setGrades([]);return}let q=supabase.from('grades').select('id,student_id,subject_id,class_id,assessment_name,score,max_score,note,grading_period_id,assessment_weight,graded_at').eq('class_id',classId).eq('subject_id',subjectId).order('graded_at',{ascending:false});if(periodId)q=q.eq('grading_period_id',periodId);const {data,error}=await q;if(error)setError(error.message);setGrades((data||[]) as Grade[])}
 useEffect(()=>{Promise.all([loadClasses(),loadPeriods(),loadSettings()]).finally(()=>setLoading(false))},[]);useEffect(()=>{if(classId)loadClass(classId)},[classId]);useEffect(()=>{loadGrades()},[classId,subjectId,periodId])
 function existing(id:string){return grades.find(g=>g.student_id===id&&g.assessment_name.trim().toLowerCase()===assessment.trim().toLowerCase())}
 function loadExisting(){if(!assessment)return;const g=grades.find(x=>x.assessment_name.trim().toLowerCase()===assessment.trim().toLowerCase());if(g){setAssessmentWeight(String(g.assessment_weight||100));setMaxScore(String(g.max_score||10))}const ns:Record<string,string>={},nn:Record<string,string>={};students.forEach(s=>{const x=existing(s.id);if(x){ns[s.id]=String(x.score);nn[s.id]=x.note||''}});setScores(ns);setNotes(nn)}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError('');setMessage('');if(!classId||!subjectId||!periodId||!assessment.trim()){setError('Select a class, subject, grading period and assessment.');setSaving(false);return}const normalizedAssessment=assessment.trim().toLowerCase();const currentControls=new Set(grades.map(g=>g.assessment_name.trim().toLowerCase()));const editing=currentControls.has(normalizedAssessment);if(!editing&&currentControls.size>=settings.controls_per_period){setError(`This period already has ${settings.controls_per_period} controls, which is the school limit.`);setSaving(false);return}const max=Number(maxScore),weight=Number(assessmentWeight);if(!Number.isFinite(max)||max<=0){setError('Max score must be greater than 0.');setSaving(false);return}if(!Number.isFinite(weight)||weight<=0){setError('Assessment weight must be greater than 0.');setSaving(false);return}const entries=students.filter(s=>scores[s.id]!==undefined&&scores[s.id]!=='').map(s=>({s,score:Number(scores[s.id])}));for(const x of entries){if(!Number.isFinite(x.score)||x.score<0||x.score>max){setError(`Invalid score for ${x.s.first_name} ${x.s.last_name}.`);setSaving(false);return}}for(const x of entries){const old=existing(x.s.id);const result=old?await supabase.rpc('update_grade',{p_grade_id:old.id,p_score:x.score,p_max_score:max,p_note:notes[x.s.id]||null,p_assessment_name:assessment.trim(),p_grading_period_id:periodId,p_assessment_weight:weight}):await supabase.rpc('create_grade',{p_student_id:x.s.id,p_subject_id:subjectId,p_class_id:classId,p_assessment_name:assessment.trim(),p_score:x.score,p_max_score:max,p_note:notes[x.s.id]||null,p_grading_period_id:periodId,p_assessment_weight:weight});if(result.error){setError(result.error.message);setSaving(false);return}}await loadGrades();setMessage(`${entries.length} grade(s) saved.`);setSaving(false)}
 const averages=useMemo(()=>students.map(s=>{const rows=grades.filter(g=>g.student_id===s.id);const totalW=rows.reduce((n,g)=>n+Number(g.assessment_weight||100),0);const weighted=rows.reduce((n,g)=>n+(Number(g.score)/Number(g.max_score))*Number(g.assessment_weight||100),0);return {...s,average:totalW?weighted/totalW*10:null,count:rows.length}}),[students,grades]);const classAverage=useMemo(()=>{const v=averages.map(x=>x.average).filter((x):x is number=>x!==null);return v.length?v.reduce((a,b)=>a+b,0)/v.length:null},[averages]);const controls=new Set(grades.map(g=>g.assessment_name.trim().toLowerCase())).size
 return <main className="min-h-screen bg-slate-50 p-6 md:p-10"><div className="mx-auto max-w-7xl"><header><p className="text-sm font-semibold text-blue-600">AtechOS</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Grades</h1><p className="mt-1 text-slate-500">Enter grades for your assigned subjects. Scores accumulate automatically into the subject average.</p></header>{error&&<p className="mt-6 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{message&&<p className="mt-6 rounded-xl bg-green-50 px-4 py-3 text-sm text-green-700">{message}</p>}
 <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-medium">Class<select value={classId} onChange={e=>setClassId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3"><option value="">Select class...</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-sm font-medium">Subject<select value={subjectId} onChange={e=>setSubjectId(e.target.value)} disabled={!classId} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3"><option value="">Select subject...</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}{s.code?` · ${s.code}`:''}</option>)}</select></label><label className="text-sm font-medium">Grading period<select value={periodId} onChange={e=>setPeriodId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3"><option value="">Select period...</option>{periods.map(p=><option key={p.id} value={p.id}>{p.name} · {p.code} ({p.weight}%)</option>)}</select></label></div><div className="mt-4 grid gap-4 md:grid-cols-4"><label className="text-sm font-medium">Control / assessment<input value={assessment} onChange={e=>setAssessment(e.target.value)} onBlur={loadExisting} placeholder="Control 1" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3"/></label><label className="text-sm font-medium">Max score<input type="number" min="1" step="0.01" value={maxScore} onChange={e=>setMaxScore(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3"/></label><label className="text-sm font-medium">Weight<input type="number" min="0.01" step="0.01" value={assessmentWeight} onChange={e=>setAssessmentWeight(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3"/><span className="mt-1 block text-xs text-slate-500">Default 100; higher weight counts more.</span></label><div className="flex items-end"><button type="button" onClick={loadExisting} disabled={!assessment||!subjectId||!periodId} className="w-full rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold">Load existing</button></div></div></section>
 <section className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">Controls</p><p className="mt-1 text-2xl font-bold">{controls} / {settings.controls_per_period}</p><p className="mt-1 text-xs text-slate-500">Maximum controls for this grading period</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">Class average / 10</p><p className="mt-1 text-2xl font-bold">{classAverage===null?'—':classAverage.toFixed(2)}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">Selected period</p><p className="mt-1 text-lg font-bold">{periods.find(p=>p.id===periodId)?.name||'—'}</p><p className="mt-1 text-xs text-slate-500">Passing average: {settings.passing_average.toFixed(2)} / 10</p></div></section>
 <form onSubmit={save} className="mt-6"><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50"><tr><th className="px-4 py-3">Student</th><th className="px-4 py-3">Code</th><th className="px-4 py-3 w-40">Score / {maxScore||'—'}</th><th className="px-4 py-3">Note</th></tr></thead><tbody>{students.map(s=><tr key={s.id} className="border-b border-slate-100 last:border-0"><td className="px-4 py-3 font-medium">{s.first_name} {s.last_name}</td><td className="px-4 py-3 text-slate-500">{s.student_code||'—'}</td><td className="px-4 py-3"><input type="number" min="0" max={maxScore} step="0.01" value={scores[s.id]||''} onChange={e=>setScores(v=>({...v,[s.id]:e.target.value}))} className="w-full rounded-lg border border-slate-300 px-3 py-2"/></td><td className="px-4 py-3"><input value={notes[s.id]||''} onChange={e=>setNotes(v=>({...v,[s.id]:e.target.value}))} className="w-full rounded-lg border border-slate-300 px-3 py-2" placeholder="Optional"/></td></tr>)}</tbody></table>{!loading&&!students.length&&<p className="p-6 text-slate-500">Select a class with enrolled students.</p>}</div><div className="mt-4 flex justify-end"><button disabled={saving||!classId||!subjectId||!periodId||!students.length} className="rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white">{saving?'Saving...':'Save grades'}</button></div></form>
 <section className="mt-8 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="text-xl font-bold">Grade history</h2><p className="mt-1 text-sm text-slate-500">Only grades permitted for your role are shown.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="px-4 py-3">Student</th><th className="px-4 py-3">Control</th><th className="px-4 py-3">Score</th><th className="px-4 py-3">Weight</th><th className="px-4 py-3">Mark / 10</th><th className="px-4 py-3">Date</th></tr></thead><tbody>{grades.map(g=>{const s=students.find(x=>x.id===g.student_id);const mark=Number(g.max_score)>0?Number(g.score)/Number(g.max_score)*10:0;return <tr key={g.id} className="border-t border-slate-100"><td className="px-4 py-3 font-medium">{s?`${s.first_name} ${s.last_name}`:'—'}</td><td className="px-4 py-3">{g.assessment_name}</td><td className="px-4 py-3">{g.score} / {g.max_score}</td><td className="px-4 py-3">{g.assessment_weight||100}</td><td className="px-4 py-3">{mark.toFixed(2)}</td><td className="px-4 py-3 text-slate-500">{g.graded_at?new Date(g.graded_at).toLocaleDateString():'—'}</td></tr>})}</tbody></table>{!grades.length&&<p className="p-6 text-slate-500">No grades recorded for this selection yet.</p>}</div></section></div></main>
}
