'use client'
import { T } from '@/components/translation-provider'
import QRScanner from '@/components/qr-scanner'
import Link from 'next/link'

import { useEffect, useRef, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type ClassRow = { id: string; name: string }
type ScanResult = { action: string; attendance_id: string; student_id: string; first_name: string; last_name: string; status: string; check_in_at: string | null; check_out_at: string | null }

export default function AttendanceKioskPage() {
  const busy=useRef(false); const [classes,setClasses]=useState<ClassRow[]>([]); const [classId,setClassId]=useState(''); const [badgeUid,setBadgeUid]=useState(''); const [lastScan,setLastScan]=useState<ScanResult|null>(null); const [message,setMessage]=useState('Ready to scan'); const [error,setError]=useState(''); const inputRef=useRef<HTMLInputElement>(null)
  useEffect(()=>{const supabase=createClient();supabase.from('classes').select('id,name').eq('enabled',true).order('name').then(({data,error})=>{if(error)setError(error.message);const rows=(data||[]) as ClassRow[];setClasses(rows);if(rows[0])setClassId(rows[0].id)})},[]); useEffect(()=>{inputRef.current?.focus()},[lastScan,message])
  async function scan(event?:React.FormEvent,code?:string){event?.preventDefault();if(busy.current)return;setError('');const uid=(code||badgeUid).trim();if(!classId){setError('Select a class first.');return}if(!uid){setError('Scan a QR code or enter the AtechOS ID.');return}busy.current=true;try {const supabase=createClient();const {data,error}=await supabase.rpc('scan_student_code',{p_code:uid,p_class:classId});busy.current=false;if(error){setError(error.message.replace('badge_not_found','Badge not found').replace('student_not_enrolled_in_class','Student is not enrolled in this class'));setMessage('Scan rejected');setBadgeUid('');inputRef.current?.focus();return}const result=(data||null) as ScanResult|null;setLastScan(result);setMessage(result?.action==='check_in'?'CHECK-IN enregistré':result?.action==='check_out'?'CHECK-OUT enregistré':result?.action==='duplicate_scan'?'Duplicate scan ignored. Wait at least one minute before check-out.':'Attendance already complete');setBadgeUid('');inputRef.current?.focus()}catch{setError('Unable to record attendance. Please try again.')}finally{busy.current=false}}
  return <main className="min-h-screen bg-slate-950 p-6 text-white md:p-10"><div className="mx-auto max-w-4xl"><header className="text-center"><Link href="/onboarding" className="text-sm font-semibold text-blue-300">AtechOS</Link><h1 className="mt-2 text-4xl font-bold"><T text="Attendance Kiosk"/></h1><p className="mt-2 text-slate-300"><T text="Scan student badge for automatic check-in / check-out."/></p></header><section className="mx-auto mt-8 max-w-xl rounded-3xl bg-white p-6 text-slate-900 shadow-2xl"><label className="block text-sm font-semibold"><T text="Class"/><select value={classId} onChange={e=>setClassId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3">{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><QRScanner onRead={code=>{setBadgeUid(code);void scan(undefined,code)}} /><form onSubmit={scan} className="mt-5"><label className="block text-sm font-semibold">AtechOS ID<input ref={inputRef} autoFocus value={badgeUid} onChange={e=>setBadgeUid(e.target.value)} placeholder="AOS-..." className="mt-2 w-full rounded-xl border-2 border-blue-200 px-4 py-5 text-center text-xl font-mono outline-none focus:border-blue-500"/></label><button className="mt-4 w-full rounded-xl bg-blue-600 px-5 py-4 font-bold text-white"><T text="Scan"/></button></form>{error&&<p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<p className="mt-4 text-center text-sm font-semibold text-slate-600">{message}</p></section>{lastScan&&<section className="mx-auto mt-8 max-w-xl rounded-3xl bg-white p-8 text-center text-slate-900 shadow-2xl"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-blue-100 text-3xl">✓</div><h2 className="mt-5 text-3xl font-bold">{lastScan.first_name} {lastScan.last_name}</h2><p className="mt-4 text-xl font-bold uppercase">{lastScan.action.replace('_',' ')}</p><div className="mt-5 grid grid-cols-2 gap-4 text-left"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500"><T text="Check-in"/></p><p className="font-semibold">{lastScan.check_in_at?new Date(lastScan.check_in_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—'}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500"><T text="Check-out"/></p><p className="font-semibold">{lastScan.check_out_at?new Date(lastScan.check_out_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—'}</p></div></div></section>}<p className="mt-8 text-center text-xs text-slate-500"><T text="Use a QR reader that types the AtechOS ID, the camera, or manual entry. Repeated scans within one minute are ignored."/></p></div></main>
}
