'use client'

import { useEffect, useRef, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type ClassRow = { id: string; name: string }
type ScanResult = { action: string; attendance_id: string; student_id: string; first_name: string; last_name: string; status: string; check_in_at: string | null; check_out_at: string | null }

export default function AttendanceKioskPage() {
  const [classes,setClasses]=useState<ClassRow[]>([]); const [classId,setClassId]=useState(''); const [badgeUid,setBadgeUid]=useState(''); const [lastScan,setLastScan]=useState<ScanResult|null>(null); const [message,setMessage]=useState('Ready to scan'); const [error,setError]=useState(''); const inputRef=useRef<HTMLInputElement>(null)
  useEffect(()=>{const supabase=createClient();supabase.from('classes').select('id,name').order('name').then(({data,error})=>{if(error)setError(error.message);const rows=(data||[]) as ClassRow[];setClasses(rows);if(rows[0])setClassId(rows[0].id)})},[]); useEffect(()=>{inputRef.current?.focus()},[lastScan,message])
  async function scan(event?:React.FormEvent){event?.preventDefault();setError('');const uid=badgeUid.trim();if(!classId){setError('Select a class first.');return}if(!uid){setError('Scan a badge or enter its UID.');return}const supabase=createClient();const {data,error}=await supabase.rpc('scan_student_badge',{p_badge_uid:uid,p_class_id:classId,p_scan_at:new Date().toISOString(),p_late_minutes:0});if(error){setError(error.message.replace('badge_not_found','Badge not found').replace('student_not_enrolled_in_class','Student is not enrolled in this class'));setMessage('Scan rejected');setBadgeUid('');inputRef.current?.focus();return}const result=(data?.[0]||null) as ScanResult|null;setLastScan(result);setMessage(result?.action==='check_in'?'CHECK-IN enregistré':result?.action==='check_out'?'CHECK-OUT enregistré':'Attendance already complete');setBadgeUid('');inputRef.current?.focus()}
  return <main className="min-h-screen bg-slate-950 p-6 text-white md:p-10"><div className="mx-auto max-w-4xl"><header className="text-center"><p className="text-sm font-semibold text-blue-300">AtechOS</p><h1 className="mt-2 text-4xl font-bold">Attendance Kiosk</h1><p className="mt-2 text-slate-300">Scan student badge for automatic check-in / check-out.</p></header><section className="mx-auto mt-8 max-w-xl rounded-3xl bg-white p-6 text-slate-900 shadow-2xl"><label className="block text-sm font-semibold">Class<select value={classId} onChange={e=>setClassId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3">{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><form onSubmit={scan} className="mt-5"><label className="block text-sm font-semibold">Badge UID<input ref={inputRef} autoFocus value={badgeUid} onChange={e=>setBadgeUid(e.target.value)} placeholder="Tap RFID/NFC badge..." className="mt-2 w-full rounded-xl border-2 border-blue-200 px-4 py-5 text-center text-xl font-mono outline-none focus:border-blue-500"/></label><button className="mt-4 w-full rounded-xl bg-blue-600 px-5 py-4 font-bold text-white">Scan</button></form>{error&&<p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<p className="mt-4 text-center text-sm font-semibold text-slate-600">{message}</p></section>{lastScan&&<section className="mx-auto mt-8 max-w-xl rounded-3xl bg-white p-8 text-center text-slate-900 shadow-2xl"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-blue-100 text-3xl">✓</div><h2 className="mt-5 text-3xl font-bold">{lastScan.first_name} {lastScan.last_name}</h2><p className="mt-4 text-xl font-bold uppercase">{lastScan.action.replace('_',' ')}</p><div className="mt-5 grid grid-cols-2 gap-4 text-left"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Check-in</p><p className="font-semibold">{lastScan.check_in_at?new Date(lastScan.check_in_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—'}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Check-out</p><p className="font-semibold">{lastScan.check_out_at?new Date(lastScan.check_out_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—'}</p></div></div></section>}<p className="mt-8 text-center text-xs text-slate-500">RFID/NFC reader that acts like a keyboard can type the badge UID and submit automatically.</p></div></main>
}
