'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import SchoolDateInput from '@/components/school-date-input'
import {schoolDate} from '@/lib/school-date'
import {T} from '@/components/translation-provider'

type Year={id:string;name:string;start_date:string;end_date:string;is_current:boolean}
export default function AcademicYearCalendar({canManage}:{canManage:boolean}){
 const [rows,setRows]=useState<Year[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const [edit,setEdit]=useState(''),[name,setName]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[current,setCurrent]=useState(true)
 const [createOpen,setCreateOpen]=useState(false)
 async function load(){const {data,error}=await createClient().from('academic_years').select('id,name,start_date,end_date,is_current').order('start_date',{ascending:false});if(error)setError(error.message);else setRows((data||[]) as Year[])}
 useEffect(()=>{void load()},[])
 function beginEdit(year:Year){setEdit(year.id);setName(year.name);setStart(year.start_date);setEnd(year.end_date);setCurrent(year.is_current);setError('');setMessage('')}
 async function saveEdit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');const {error}=await createClient().rpc('update_academic_year',{p_id:edit,p_name:name,p_start_date:start,p_end_date:end,p_is_current:current});if(error)setError(error.message);else{setMessage('Academic year updated.');setEdit('');await load()}setBusy(false)}
 async function create(e:React.FormEvent){e.preventDefault();const form=new FormData(e.currentTarget as HTMLFormElement);setBusy(true);setError('');setMessage('');const firstStart=String(form.get('start')||''),firstEnd=String(form.get('end')||'');const {error}=await createClient().rpc('create_academic_year_with_successor',{p_name:String(form.get('name')||''),p_start_date:firstStart,p_end_date:firstEnd,p_is_current:form.get('current')==='on'});if(error)setError(error.message);else{setMessage('Academic year created. Review the next year dates below.');setCreateOpen(false);await load()}setBusy(false)}
 const firstEnd=rows[0]?.end_date
 return <section className="my-5 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold"><T text="Academic years"/></h2><p className="text-sm text-slate-600"><T text="Manage school-year dates and choose the active year. A successor year is prepared automatically from the configured end date."/></p></div>{canManage&&<button type="button" onClick={()=>setCreateOpen(v=>!v)} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white"><T text="+ Academic year"/></button>}</div>
 {error&&<p role="alert" className="mt-3 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message&&<p role="status" className="mt-3 rounded bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}
 {createOpen&&canManage&&<form onSubmit={create} className="mt-4 grid gap-3 rounded-xl border bg-slate-50 p-4 md:grid-cols-2"><label className="text-sm"><T text="Name"/><input name="name" required placeholder="2026/2027" className="mt-1 w-full rounded border bg-white p-2"/></label><label className="flex items-center gap-2 self-end pb-2 text-sm"><input name="current" type="checkbox" defaultChecked/><T text="Set as current academic year"/></label><label className="text-sm"><T text="Start date"/><SchoolDateInput name="start" type="date" required className="mt-1 block w-full rounded border bg-white p-2"/></label><label className="text-sm"><T text="End date"/><SchoolDateInput name="end" type="date" required min={firstEnd||undefined} className="mt-1 block w-full rounded border bg-white p-2"/></label><p className="text-sm text-slate-600 md:col-span-2"><T text="After saving, the next inactive year starts on this year's end date and uses the same length. Review or adjust it before activating it."/></p><button disabled={busy} className="rounded-lg bg-blue-600 p-2 font-semibold text-white disabled:opacity-50"><T text={busy?'Saving...':'Create year and prepare next year'}/></button></form>}
 {!rows.length?<p className="mt-4 text-sm text-slate-600"><T text="No academic year has been created yet."/></p>:<ul className="mt-4 grid gap-3 md:grid-cols-2">{rows.map(year=><li key={year.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{year.name} {year.is_current&&<span className="rounded-full bg-blue-50 px-2 py-1 text-xs text-blue-700"><T text="Current"/></span>}</p><p className="mt-1 text-sm text-slate-600">{schoolDate(year.start_date)} – {schoolDate(year.end_date)}</p></div>{canManage&&edit!==year.id&&<button type="button" onClick={()=>beginEdit(year)} className="text-sm text-blue-700 underline"><T text="Edit dates"/></button>}</div>
 {canManage&&edit===year.id&&<form onSubmit={saveEdit} className="mt-3 grid gap-3"><label className="text-sm"><T text="Name"/><input required value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded border p-2"/></label><div className="grid grid-cols-2 gap-3"><label className="text-sm"><T text="Start date"/><SchoolDateInput type="date" required value={start} onChange={e=>setStart(e.target.value)} className="mt-1 block w-full rounded border p-2"/></label><label className="text-sm"><T text="End date"/><SchoolDateInput type="date" required min={start} value={end} onChange={e=>setEnd(e.target.value)} className="mt-1 block w-full rounded border p-2"/></label></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={current} onChange={e=>setCurrent(e.target.checked)}/><T text="Set as current academic year"/></label><div className="flex gap-2"><button disabled={busy} className="rounded bg-blue-600 px-3 py-2 text-sm text-white"><T text="Save"/></button><button type="button" onClick={()=>setEdit('')} className="rounded border px-3 py-2 text-sm"><T text="Cancel"/></button></div></form>}</li>)}</ul>}
 </section>
}
