'use client'
import Link from 'next/link'
import {usePathname} from 'next/navigation'
import {useEffect,useState,type ReactNode} from 'react'
import {Bell,Search,Menu,X,LogOut,LayoutDashboard,Users,GraduationCap,BookOpen,CalendarDays,ClipboardCheck,Contact,FileText,Settings,ArrowUpRight,UserPlus,ChevronRight} from 'lucide-react'
import {createClient} from '@/lib/supabase/client'
import {permittedNavigation} from '@/lib/navigation'
import {schoolDateTime} from '@/lib/school-date'
import {translate} from '@/lib/translations'
import {T,useLocale} from '@/components/translation-provider'
import LanguageSelector from '@/components/language-selector'

type Notice={id:string;title:string;description:string;created_at:string;read_at:string|null;priority:string;href:string;type:string}
type SearchResult={kind:string;label:string;href:string}
const icons:Record<string,typeof Users>={dashboard:LayoutDashboard,students:GraduationCap,parents:Users,teachers:Users,classes:BookOpen,attendance:ClipboardCheck,badge:Contact,calendar:CalendarDays,grades:FileText,publication:ClipboardCheck,reports:FileText,assignments:BookOpen,progression:ArrowUpRight,requests:UserPlus,users:Users,settings:Settings}
const roleLabels:Record<string,string>={school_admin:'Administrator',director:'Director',secretary:'Secretary',teacher:'Teacher',accountant:'Accountant',surveillant:'Attendance supervisor',parent:'Parent',student:'Student',censeur:'Academic reviewer'}
export default function AppShell({children,school,name,avatar,roles,owner}:{children:ReactNode;school:string;name:string;avatar:string|null;roles:string[];owner:boolean}){
 const locale=useLocale();const t=(text:string)=>translate(text,locale);const path=usePathname();const items=permittedNavigation(roles,owner)
 const [menu,setMenu]=useState(false),[query,setQuery]=useState(''),[results,setResults]=useState<SearchResult[]>([]),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState(false)
 const [open,setOpen]=useState(false),[notices,setNotices]=useState<Notice[]>([]),[unread,setUnread]=useState<number|null>(null),[noticeError,setNoticeError]=useState(false),[busy,setBusy]=useState(false),[logoutError,setLogoutError]=useState(false)
 useEffect(()=>{let current=true;const timer=setTimeout(async()=>{if(query.trim().length<2){setResults([]);setSearching(false);return}setSearching(true);setSearchError(false);try{const {data,error}=await createClient().rpc('school_search',{p_query:query.trim()});if(current){setResults(error?[]:data||[]);setSearchError(Boolean(error))}}catch{if(current)setSearchError(true)}finally{if(current)setSearching(false)}},250);return()=>{current=false;clearTimeout(timer)}},[query])
 useEffect(()=>{let current=true;async function load(){try{const db=createClient();const [list,count]=await Promise.all([db.from('notifications').select('id,title,description,created_at,read_at,priority,href,type').order('created_at',{ascending:false}).limit(30),db.from('notifications').select('id',{count:'exact',head:true}).is('read_at',null)]);if(!current)return;setNoticeError(Boolean(list.error||count.error));if(!list.error)setNotices(list.data||[]);if(!count.error)setUnread(count.count||0)}catch{if(current)setNoticeError(true)}}void load();const timer=setInterval(load,60000);return()=>{current=false;clearInterval(timer)}},[open])
 async function read(n:Notice){if(n.read_at)return;const {error}=await createClient().rpc('mark_notification_read',{p_id:n.id});if(error){setNoticeError(true);return}setNotices(v=>v.map(x=>x.id===n.id?{...x,read_at:new Date().toISOString()}:x));setUnread(v=>v===null?null:Math.max(0,v-1))}
 async function logout(){setBusy(true);setLogoutError(false);try{const {error}=await createClient().auth.signOut({scope:'local'});if(error)throw error;window.location.replace('/login')}catch{setLogoutError(true);setBusy(false)}}
 return <div className="atechos-shell min-h-screen bg-slate-50 text-slate-900">{menu&&<button className="fixed inset-0 z-30 bg-slate-950/50 lg:hidden print:hidden" aria-label={t('Close navigation')} onClick={()=>setMenu(false)}/>}
 <aside className={`${menu?'translate-x-0':'-translate-x-full'} fixed inset-y-0 left-0 z-40 flex w-64 flex-col bg-[#101e38] text-slate-200 transition-transform lg:translate-x-0 print:hidden`}><Link href="/onboarding" className="flex items-center gap-3 border-b border-white/10 px-6 py-6"><span className="rounded-xl bg-blue-600 p-2 text-white"><GraduationCap/></span><span><strong className="block text-xl tracking-tight text-white">AtechOS</strong><span className="text-xs text-slate-400"><T text="School system"/></span></span></Link><button className="absolute right-2 top-2 p-2 lg:hidden" aria-label={t('Close navigation')} onClick={()=>setMenu(false)}><X size={18}/></button><p className="truncate px-6 pb-2 pt-5 text-xs text-slate-400" title={school}>{school}</p><nav aria-label={t('School modules')} className="flex-1 space-y-1 overflow-y-auto px-3 py-3">{items.map(item=>{const Icon=icons[item.icon]||FileText;const active=path===item.href||(item.href!=='/dashboard'&&path.startsWith(item.href+'/'));return <Link key={item.href} href={item.href} onClick={()=>{setMenu(false);setQuery('')}} aria-current={active?'page':undefined} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm transition-colors ${active?'bg-blue-600 font-semibold text-white shadow-sm':'hover:bg-white/10 hover:text-white'}`}><Icon size={19}/><T text={item.label}/>{active&&<ChevronRight size={16} className="ml-auto"/>}</Link>})}</nav><div className="border-t border-white/10 p-4"><button disabled={busy} onClick={logout} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm hover:bg-white/10"><LogOut size={18}/><T text={busy?'Signing out…':'Logout'}/></button>{logoutError&&<p role="alert" className="text-sm text-red-300"><T text="Unable to sign out. Please try again."/></p>}</div></aside>
 <div className="lg:pl-64 print:pl-0"><header className="relative z-20 flex flex-wrap items-center gap-3 border-b border-slate-200 bg-white px-4 py-4 shadow-sm md:px-6 print:hidden"><button className="rounded-lg border p-2 lg:hidden" aria-label={t('Open navigation')} aria-expanded={menu} onClick={()=>setMenu(!menu)}><Menu size={20}/></button><div className="relative order-last w-full min-w-0 md:order-none md:w-auto md:flex-1"><label className="flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2"><Search size={18} className="shrink-0 text-slate-400"/><span className="sr-only"><T text="Search students, parents, teachers…"/></span><input value={query} maxLength={100} onChange={e=>{setResults([]);setQuery(e.target.value)}} className="w-full min-w-0 bg-transparent text-sm outline-none" placeholder={t('Search students, parents, teachers…')}/></label>{query.trim().length>=2&&<div className="absolute left-0 right-0 top-full mt-2 max-h-80 overflow-auto rounded-xl border bg-white p-2 shadow-xl" role="region" aria-label={t('Search results')}>{searching?<p className="p-3"><T text="Loading..."/></p>:searchError?<p role="alert" className="p-3"><T text="Search unavailable. Please try again."/></p>:results.length?results.map((r,i)=><Link key={r.href+i} href={r.href} onClick={()=>setQuery('')} className="block rounded-lg p-3 hover:bg-blue-50"><span className="block text-sm font-semibold">{r.label}</span><span className="text-xs text-slate-500"><T text={r.kind==='student'?'Student':r.kind==='teacher'?'Teacher':r.kind==='parent'?'Parent':'Class'}/></span></Link>):<p className="p-3"><T text="No permitted results."/></p>}</div>}</div>
 <div className="relative"><button onClick={()=>setOpen(!open)} aria-label={t('Notifications')} aria-expanded={open} className="relative rounded-xl border border-slate-200 p-3 hover:bg-slate-50"><Bell size={20}/>{unread!==null&&unread>0&&<span className="absolute -right-1 -top-1 rounded-full bg-blue-600 px-1.5 text-xs font-bold text-white">{unread}</span>}</button>{open&&<section className="absolute right-0 top-full mt-3 w-80 max-w-[85vw] rounded-2xl border bg-white p-4 shadow-xl"><h2 className="mb-3 font-semibold"><T text="Notifications"/></h2>{noticeError&&<p role="alert"><T text="Unable to load notifications."/></p>}<div className="max-h-96 overflow-auto">{notices.map(n=><article key={n.id} className={`mb-2 rounded-xl border p-3 ${n.read_at?'bg-white':'border-blue-200 bg-blue-50'}`}><p className="flex items-center gap-2 text-sm font-semibold"><Bell size={15}/>{n.title}</p><p className="my-1 text-sm text-slate-600">{n.description}</p><p className="text-xs text-slate-500">{schoolDateTime(n.created_at)} · {n.priority}</p><div className="mt-2 flex gap-3 text-sm text-blue-700">{n.href.startsWith('/dashboard/')&&!n.href.includes('\\')&&<Link href={n.href} onClick={()=>{void read(n);setOpen(false)}}><T text="Open"/></Link>}{!n.read_at&&<button onClick={()=>void read(n)}><T text="Mark as read"/></button>}</div></article>)}{!noticeError&&!notices.length&&<p className="text-sm text-slate-500"><T text="No notifications yet."/></p>}</div></section>}</div>
 <div className="flex items-center gap-3 border-l border-slate-200 pl-3">{avatar?<img src={avatar} alt="" className="h-10 w-10 rounded-full object-cover"/>:<span className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-100 font-bold text-blue-700">{name.trim().slice(0,1).toUpperCase()||'A'}</span>}<div className="max-w-32"><p className="truncate text-sm font-semibold">{name}</p><p className="truncate text-xs text-slate-500">{roles.map((r,i)=><span key={r}>{i>0?' · ':''}<T text={roleLabels[r]||r}/></span>)}</p></div></div><div className="ml-auto text-xs"><LanguageSelector locale={locale}/></div></header><div className="min-w-0">{children}</div></div></div>
}
