'use client'
import {useState} from 'react'
import {createClient} from '@/lib/supabase/client'
type Receipt={id:string;name:string;code:string|null;received_at:string|null;response:string|null;source:string|null;status:string}
export default function AssignmentTracking({id,online}:{id:string;online:boolean}){
 const [enabled,setEnabled]=useState(online),[rows,setRows]=useState<Receipt[]|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function load(){const {data,error}=await createClient().rpc('assignment_roster',{p_assignment:id});if(error)setError(error.message);else setRows(data||[])}
 return <div className="mt-4 space-y-3 border-t pt-3"><label><input type="checkbox" checked={enabled} disabled={busy} onChange={async e=>{setBusy(true);setError('');const value=e.target.checked;try{const {error}=await createClient().rpc('set_assignment_online',{p_assignment:id,p_enabled:value});if(error)setError(error.message);else setEnabled(value)}finally{setBusy(false)}}}/> Autoriser la remise en ligne (facultatif, date limite obligatoire)</label><p className="text-sm">Les devoirs non reçus deviennent « Non remis » après la date limite. Les remises cochées après cette date sont en retard.</p><button type="button" onClick={load} className="rounded border p-2">Suivre les remises</button>{error&&<p role="alert" className="text-red-700">{error}</p>}{rows?.map(r=><div key={r.id} className="rounded border p-3"><label><input type="checkbox" checked={!!r.received_at} disabled={busy||r.source==='online'} onChange={async e=>{setBusy(true);setError('');try{const {error}=await createClient().rpc('mark_assignment_received',{p_assignment:id,p_student:r.id,p_received:e.target.checked});if(error)setError(error.message);else await load()}finally{setBusy(false)}}}/> {r.name}{r.code?` · ${r.code}`:null}</label><p>{({received:'Reçu',late:'Reçu en retard',missing:'Non remis',pending:'En attente'} as Record<string,string>)[r.status]}{r.received_at?' · '+new Date(r.received_at).toLocaleString():''}</p>{r.response&&<p className="mt-2 whitespace-pre-wrap">{r.response}</p>}</div>)}</div>
}
