'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import {schoolDateTime} from '@/lib/school-date'
import {T} from '@/components/translation-provider'
export type BadgeWorkspace={can_manage:boolean;payment_restricted?:boolean;qr:string|null;badges:{id:string;serial:string;state:string;issued_at:string;issued_by:string|null;revoked_at:string|null;reason:string|null}[];events:{id:string;action:string;actor_name:string|null;actor_role:string|null;reason:string|null;created_at:string}[];scans:{source:string;result:string;device_location:string|null;created_at:string}[]}
type ParentBadgeStudent={first_name:string;last_name:string;atechos_id:string}
const states:Record<string,string>={active:'Active',lost:'Lost',replaced:'Replaced',revoked:'Revoked'}
export function BadgeHistory({data}:{data:BadgeWorkspace}){return <section className="space-y-5"><article className="overflow-auto rounded-2xl border bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-bold"><T text="Badge history"/></h2><table className="w-full text-left text-sm"><thead><tr>{['Badge','Status','Issued','Issued by','Reason'].map(h=><th key={h} className="p-2"><T text={h}/></th>)}</tr></thead><tbody>{data.badges.map(b=><tr key={b.id} className="border-t"><td className="max-w-48 break-all p-2 font-mono text-xs">{b.serial}</td><td className="p-2"><span className={`rounded-full px-2 py-1 text-xs ${b.state==='active'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-800'}`}><T text={states[b.state]||b.state}/></span></td><td className="p-2">{schoolDateTime(b.issued_at)}</td><td className="p-2">{b.issued_by||'—'}</td><td className="p-2">{b.reason||'—'}</td></tr>)}</tbody></table>{!data.badges.length&&<p><T text="No badge issued."/></p>}<details className="mt-4"><summary><T text="Action history"/></summary>{data.events.map(e=><p key={e.id} className="my-2 border-t pt-2 text-sm">{schoolDateTime(e.created_at)} · {e.action} · {e.actor_name||'—'} ({e.actor_role||'—'}) · {e.reason}</p>)}</details></article><article className="overflow-auto rounded-2xl border bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-bold"><T text="Scan history"/></h2><table className="w-full text-left text-sm"><thead><tr>{['Date','Type','Device / location','Result'].map(h=><th key={h} className="p-2"><T text={h}/></th>)}</tr></thead><tbody>{data.scans.map((s,i)=><tr key={s.created_at+i} className="border-t"><td className="p-2">{schoolDateTime(s.created_at)}</td><td className="p-2">{s.source}</td><td className="p-2">{s.device_location||'—'}</td><td className="p-2">{s.result}</td></tr>)}</tbody></table>{!data.scans.length&&<p><T text="No scans recorded since history was enabled."/></p>}</article></section>}
export function ParentBadge({studentId,student,photoUrl}:{studentId:string;student:ParentBadgeStudent;photoUrl?:string}){
 const [data,setData]=useState<BadgeWorkspace|null>(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[storedPhotoUrl,setStoredPhotoUrl]=useState('')
 useEffect(()=>{let active=true;setData(null);createClient().rpc('badge_workspace',{p_student:studentId}).then(({data,error})=>{if(active){setData(data);setError(error?'Unable to load badge.':'')}});return()=>{active=false}},[studentId])
 useEffect(()=>{let active=true;if(photoUrl!==undefined){setStoredPhotoUrl(photoUrl);return()=>{active=false}}setStoredPhotoUrl('');const client=createClient();void(async()=>{const {data,error}=await client.from('students').select('photo_url').eq('id',studentId).maybeSingle();if(!active||error||!data?.photo_url)return;const path=data.photo_url;if(/^https?:\/\//i.test(path)){setStoredPhotoUrl(path);return}const {data:signed,error:signedError}=await client.storage.from('student-photos').createSignedUrl(path,3600);if(active&&!signedError)setStoredPhotoUrl(signed?.signedUrl||'')})();return()=>{active=false}},[photoUrl,studentId])
 const initials=`${student.first_name[0]||''}${student.last_name[0]||''}`
 const fullName=`${student.first_name} ${student.last_name}`
 const activeBadge=data?.badges.find(b=>b.state==='active')
 return <details className="my-5 overflow-hidden rounded-2xl border bg-white shadow-sm print:hidden"><summary className="flex cursor-pointer list-none flex-wrap items-center gap-4 p-4 sm:p-5"><span className="shrink-0">{storedPhotoUrl?<img src={storedPhotoUrl} alt={fullName} referrerPolicy="no-referrer" loading="lazy" className="h-16 w-16 rounded-xl object-cover ring-2 ring-blue-50"/>:<span aria-hidden="true" className="flex h-16 w-16 items-center justify-center rounded-xl bg-blue-50 text-lg font-bold text-blue-800">{initials}</span>}</span><span className="min-w-0 flex-1"><span className="block text-xs font-semibold uppercase tracking-wide text-blue-700"><T text="Student badge"/></span><span className="mt-1 block truncate text-lg font-bold text-slate-900">{fullName}</span><span className="mt-1 block font-mono text-xs text-slate-600">AtechOS ID · {student.atechos_id}</span>{activeBadge&&<span className="mt-2 inline-flex rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-800"><T text="Active"/> · {activeBadge.serial}</span>}</span><span aria-hidden="true" className="text-slate-500">⌄</span></summary><div className="border-t p-4 sm:p-5">{error&&<p role="alert"><T text={error}/></p>}{data&&<>{data.payment_restricted&&<p role="alert" className="my-3 rounded-lg border border-red-300 bg-red-50 p-3 font-semibold text-red-800"><T text="KIOS badge use is blocked because an overdue school fee still has a balance."/></p>}<p className="my-3"><T text="A lost badge stops working immediately. The school issues its replacement."/></p>{data.badges.some(b=>b.state==='active')&&<form className="mb-5 space-y-3" onSubmit={async e=>{e.preventDefault();if(!window.confirm('Déclarer le badge perdu ? / Deklare badge la pèdi?'))return;setBusy(true);setError('');try{const db=createClient();const {error}=await db.rpc('report_badge_lost',{p_student:studentId,p_reason:reason});if(error)throw error;const result=await db.rpc('badge_workspace',{p_student:studentId});if(result.error)throw result.error;setData(result.data);setReason('')}catch{setError('Unable to save. Please try again.')}finally{setBusy(false)}}}><label className="block"><T text="Reason"/><input required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} className="ml-2 rounded border p-2"/></label><button disabled={busy} className="rounded bg-red-700 px-4 py-2 text-white"><T text="Report lost badge"/></button></form>}<BadgeHistory data={data}/></>}</div></details>
}
