'use client'
import {useEffect,useState} from 'react'
import {BadgeBack,BadgeFront,type BadgeIdentity} from '@/components/badge-card'
import {T} from '@/components/translation-provider'
type View='3d'|'front'|'back'|'print'
export default function BadgePreview({identity,qr,origin}:{identity:BadgeIdentity;qr:string;origin:string}){
 const [view,setView]=useState<View>('3d'),[back,setBack]=useState(false),[zoom,setZoom]=useState(100),[expanded,setExpanded]=useState(false)
 useEffect(()=>{if(!expanded)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setExpanded(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[expanded])
 const content=<><div className="flex flex-wrap items-center gap-2 border-b pb-4" role="group" aria-label="Badge preview views">{([['3d','3D preview'],['front','Front'],['back','Back'],['print','Print preview']] as const).map(([id,label])=><button key={id} type="button" aria-pressed={view===id} onClick={()=>setView(id)} className={`rounded-lg px-3 py-2 ${view===id?'bg-blue-600 text-white':'bg-slate-100'}`}><T text={label}/></button>)}</div><div className="my-3 flex flex-wrap items-center gap-2"><button type="button" disabled={view!=='3d'} onClick={()=>setBack(!back)} className="rounded border p-2 disabled:opacity-40"><T text="Rotate badge"/></button><button type="button" disabled={zoom<=75} onClick={()=>setZoom(z=>Math.max(75,z-25))} className="rounded border p-2 disabled:opacity-40"><T text="Zoom out"/></button><output aria-live="polite" className="min-w-14 text-center">{zoom}%</output><button type="button" disabled={zoom>=175} onClick={()=>setZoom(z=>Math.min(175,z+25))} className="rounded border p-2 disabled:opacity-40"><T text="Zoom in"/></button><button type="button" onClick={()=>{setZoom(100);setBack(false)}} className="rounded border p-2"><T text="Reset preview"/></button><button type="button" onClick={()=>setExpanded(!expanded)} className="ml-auto rounded border p-2"><T text={expanded?'Close preview':'Expand preview'}/></button></div><div className="overflow-auto rounded-xl bg-gradient-to-br from-slate-100 to-blue-100 p-6" style={{minHeight:360*zoom/100+48}}><div className="mx-auto flex items-center justify-center" style={{minWidth:(view==='print'?460:240)*zoom/100,minHeight:340*zoom/100,perspective:'1000px'}}><div style={{transform:`scale(${zoom/100})`,transformOrigin:'center'}}>{view==='3d'?<div className="relative h-[85.6mm] w-[53.98mm]" style={{transformStyle:'preserve-3d',transform:`rotateY(${back?168:-12}deg) rotateX(4deg)`}}><div style={{backfaceVisibility:'hidden'}} aria-hidden={back}><BadgeFront identity={identity} qr={qr}/></div><div className="absolute inset-0" style={{backfaceVisibility:'hidden',transform:'rotateY(180deg)'}} aria-hidden={!back}><BadgeBack origin={origin}/></div></div>:view==='print'?<div className="flex gap-6"><BadgeFront identity={identity} qr={qr}/><BadgeBack origin={origin}/></div>:view==='front'?<BadgeFront identity={identity} qr={qr}/>:<BadgeBack origin={origin}/>}</div></div></div><p className="mt-4 text-center text-xs text-slate-500">CR80 · 53.98 × 85.60 mm · Portrait</p><p className="mt-2 text-center text-xs text-slate-500"><T text="Preview zoom does not change printed card dimensions. Print at 100% scale."/></p></>
 return <section className={expanded?'fixed inset-3 z-50 overflow-auto rounded-2xl border bg-white p-5 shadow-2xl':'rounded-2xl border bg-white p-6 shadow-sm'} aria-label="Badge preview">{content}</section>
}
