'use client'
import {QRCodeSVG} from 'qrcode.react'
export type BadgeIdentity={name:string;code:string;className:string;photo:string;school:string;logo:string|null}
export function BadgeFront({identity,qr}:{identity:BadgeIdentity;qr:string}){
 return <div className="badge-card flex h-[85.6mm] w-[53.98mm] shrink-0 flex-col overflow-hidden rounded-[3mm] relative border border-slate-200 bg-white text-center shadow-lg print:rounded-none print:border-0 print:shadow-none"><BadgeArtwork/><header className="relative flex min-h-[18mm] flex-col items-center justify-center gap-1 px-7 pt-3 text-[#082c59]">{identity.logo&&<img src={identity.logo} alt="" className="h-[8mm] w-[12mm] shrink-0 bg-white object-contain"/>}<h2 className="text-[10px] font-extrabold uppercase leading-tight">{identity.school}</h2></header><div className="relative mx-auto mt-[1mm] h-[24mm] w-[21mm] shrink-0 overflow-hidden rounded-lg border-2 border-[#082c59] bg-slate-100">{identity.photo?<img src={identity.photo} alt="" className="h-full w-full object-cover"/>:<span className="flex h-full items-center justify-center text-[9px] text-slate-400">PHOTO</span>}</div><h3 className="relative mx-3 mt-1 text-[11px] font-extrabold leading-tight text-[#082c59]">{identity.name}</h3><p className="relative mx-auto mt-1 max-w-[45mm] rounded bg-[#e8ad25] px-3 py-0.5 text-[9px] font-bold text-[#082c59]">{identity.className}</p><p className="relative mt-1 font-mono text-[7px]">{identity.code}</p><div className="relative mx-auto my-0.5 bg-white">{qr?<QRCodeSVG value={qr} size={76} marginSize={4}/>:<div className="flex h-[20mm] w-[20mm] items-center justify-center text-[8px] text-slate-400">QR non actif</div>}</div><footer className="absolute bottom-2 right-2"><BadgeBrand/></footer></div>
}
export function BadgeBack({origin}:{origin:string}){
 const links=[['Portail élève','/student/login'],['Portail parent','/login']]
 return <div className="badge-card flex h-[85.6mm] w-[53.98mm] shrink-0 flex-col overflow-hidden rounded-[3mm] relative border border-slate-200 bg-white px-[3mm] pb-[8mm] pt-[9mm] text-slate-700 shadow-lg print:rounded-none print:border-0 print:shadow-none"><BadgeArtwork back/><h2 className="relative bg-[#082c59] px-2 py-1 text-[9px] font-bold text-white">UTILISATION DU BADGE</h2><p className="relative mt-2 text-[8px] leading-snug">Ce badge sert à l’identification, à la présence et à la sortie. Ne le prêtez pas. En cas de perte, le parent doit le déclarer à l’école ou dans son portail.</p><h2 className="relative mt-3 bg-[#082c59] px-2 py-1 text-[9px] font-bold text-white">ITILIZASYON BADJ LA</h2><p className="relative mt-2 text-[8px] leading-snug">Badge sa a sèvi pou idantifikasyon, prezans ak sòti. Pa prete li. Si li pèdi, paran an dwe deklare sa nan lekòl la oswa nan pòtal li.</p><div className="relative mt-auto grid grid-cols-2 gap-2">{links.map(([label,path])=><div key={path} className="min-w-0 rounded-lg bg-blue-50 p-1 text-center"><p className="mb-1 text-[8px] font-bold">{label}</p>{origin&&<QRCodeSVG value={origin+path} size={64} marginSize={4} className="mx-auto max-w-full"/>}<p className="mt-1 break-all text-[6px]">{origin}{path}</p></div>)}</div><p className="absolute bottom-3 left-3 text-[5px] text-white">Connexion requise · Koneksyon obligatwa</p><div className="absolute bottom-2 right-2 rounded bg-white p-0.5"><BadgeBrand/></div></div>
}

function BadgeBrand(){return <span className="flex flex-col items-center text-[6px] font-bold leading-tight text-[#082c59]"><svg width="18" height="14" viewBox="0 0 30 23" fill="none" aria-hidden="true"><path d="M7 19H23a5 5 0 0 0 0-10 8 8 0 0 0-16-1 5.5 5.5 0 0 0 0 11Z" stroke="#087eff" strokeWidth="2.4"/><path d="M15 10v10m-4-4 4 4 4-4" stroke="#087eff" strokeWidth="2"/></svg>AtechOS</span>}
function BadgeArtwork({back=false}:{back?:boolean}){return <svg aria-hidden="true" viewBox="0 0 204 324" preserveAspectRatio="none" className="pointer-events-none absolute inset-0 h-full w-full">{back?<><path d="M0 0H204V35Q90 7 0 35Z" fill="#082c59"/><path d="M0 289Q110 305 204 279V324H0Z" fill="#082c59"/><path d="M0 287Q110 303 204 277" fill="none" stroke="#e8ad25" strokeWidth="3"/></>:<><path d="M0 0H83Q22 25 0 79Z" fill="#082c59"/><path d="M0 0H57Q19 20 0 52Z" fill="#087eff"/><path d="M150 0Q188 12 204 44V0Z" fill="#082c59"/><path d="M146 0Q188 15 204 47" fill="none" stroke="#e8ad25" strokeWidth="3"/><path d="M0 232Q18 285 82 324H0Z" fill="#082c59"/><path d="M0 240Q20 291 80 324" fill="none" stroke="#e8ad25" strokeWidth="4"/><path d="M0 250Q15 300 55 324H0Z" fill="#075fac"/></>}</svg>}
