'use client'
import {useCallback,useEffect,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import {schoolDate,schoolDateTime,schoolDateTimeToISO,SCHOOL_TIME_ZONE} from '@/lib/school-date'
import SchoolDateInput from '@/components/school-date-input'
import {T,useLocale} from '@/components/translation-provider'
import {translate} from '@/lib/translations'
import {useAcademicYear} from '@/components/academic-year-context'

type Exam={id:string;class_id:string;class:string;year_id:string;year:string;section:string;subject_id:string;subject:string;period_id:string;period:string;starts_at:string;ends_at:string;cancelled:boolean;scanned_at:string|null;version:number;published_at:string;revision_start:string|null;revision_end:string|null}
type Version={id:string;exam_id:string;class_id:string;subject_id:string;period_id:string;version:number;starts_at:string;ends_at:string;cancelled:boolean;revision_start:string|null;revision_end:string|null;reason:string;state:string;creator:string;publisher:string|null;created_at:string;published_at:string|null;snapshot:{class:string;year:string;subject:string;period:string};events:{id:string;action:string;actor_name:string;actor_role:string;reason:string;created_at:string;old_value:{starts_at?:string;ends_at?:string}|null;new_value:{starts_at?:string;ends_at?:string}|null}[]}
type OfficialExamDate={id:string;year_id:string;year:string;section:string;source_url:string;source_name:string;source_label:string;source_wording:string;category:'exam_period'|'official_exam';start_date:string;end_date:string;confirmed_at:string}
export type CalendarData={school_scope_id?:string|null;can_manage:boolean;can_publish:boolean;exams:Exam[];official_exam_dates?:OfficialExamDate[];versions?:Version[];closures:{day:string;title:string}[];classes:{id:string;name:string;year_id:string;year:string;section:string;year_start?:string;year_end?:string}[];subjects:{id:string;name:string;class_id:string}[];periods:{id:string;name:string;year_id:string;sections:string[];start_date:string;end_date:string}[]}
export function calendarWithConfirmedDates(workspace:CalendarData,schoolCalendar:CalendarData):CalendarData{
 return {...workspace,official_exam_dates:schoolCalendar.official_exam_dates||[]}
}
export function officialExamDatesForSelection(data:CalendarData,selectedYear:string,classId:string):OfficialExamDate[]{
 const selectedClass=data.classes.find(item=>item.id===classId)||data.exams.find(item=>item.class_id===classId)
 return (data.official_exam_dates||[]).filter(date=>(!selectedYear||date.year_id===selectedYear)&&(!classId||(selectedClass!==undefined&&date.year_id===selectedClass.year_id&&date.section===selectedClass.section)))
}
const errors:Record<string,string>={exam_time_conflict:'Another exam already uses this class time.',school_closed:'The school is closed on this date.',invalid_exam_time:'End time must follow start time on the same day.',invalid_revision_week:'Revision dates must be within the academic year and before the exam.',invalid_exam_scope_or_date:'Choose a subject and a date within the selected period.',not_authorized:'Access denied.',censeur_publication_required:'A Censeur must publish this schedule.',version_not_pending:'This version is no longer awaiting publication. Reload the calendar.',reason_required:'Provide a reason of at least three characters.'}
const states:Record<string,string>={pending:'Pending publication',published:'Published',returned:'Returned for correction',superseded:'Superseded draft'}
function localTime(value:string){return new Intl.DateTimeFormat('sv-SE',{timeZone:SCHOOL_TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(value)).replace(' ','T')}
export function CalendarView({data,onEdit,academicYearId}:{data:CalendarData;onEdit?:(exam:Exam)=>void;academicYearId?:string}){
 const locale=useLocale()
 const [year,setYear]=useState(''),[classId,setClassId]=useState(''),[period,setPeriod]=useState('')
 const selectedYear=academicYearId||year
 const rows=data.exams.filter(e=>(!selectedYear||e.year_id===selectedYear)&&(!classId||e.class_id===classId)&&(!period||e.period_id===period))
 const officialDates=officialExamDatesForSelection(data,selectedYear,classId)
 const yearOptions=Array.from(new Map([...data.classes.map(c=>[c.year_id,c.year] as const),...data.exams.map(e=>[e.year_id,e.year] as const),...(data.official_exam_dates||[]).map(date=>[date.year_id,date.year] as const)]).entries())
 const yearRange=data.classes.find(c=>c.year_id===selectedYear)
 const closures=data.closures.filter(c=>!selectedYear||!yearRange?.year_start||!yearRange?.year_end||(c.day>=yearRange.year_start&&c.day<=yearRange.year_end))
 return <section id="exam-calendar" className="my-5 space-y-4 rounded-2xl border bg-white p-5"><h2 className="text-2xl font-bold"><T text="Published exams and school calendar"/></h2>
  <div className="flex flex-wrap gap-3 print:hidden"><label><T text="Academic year"/><select className="ml-2 rounded border p-2" value={selectedYear} disabled={Boolean(academicYearId)} onChange={e=>setYear(e.target.value)}><option value=""><T text="All"/></option>{yearOptions.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>{([['Class',classId,setClassId,'class_id','class'],['Period',period,setPeriod,'period_id','period']] as const).map(([label,value,setValue,id,name])=><label key={label}><T text={label}/><select className="ml-2 rounded border p-2" value={value} onChange={e=>setValue(e.target.value)}><option value=""><T text="All"/></option>{Array.from(new Map(data.exams.filter(e=>!selectedYear||e.year_id===selectedYear).map(e=>[e[id],e[name]])).entries()).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>)}</div>
  <p className="text-sm"><T text="Times use Haiti time. Kiosk presence records arrival at school on the exam day."/></p>
  {rows.map(e=><article key={e.id} className="space-y-1 rounded-xl border p-4"><h3 className="font-semibold">{e.subject} · {e.class}</h3><p>{e.year} · {e.period}</p><p>{schoolDateTime(e.starts_at,locale)} → {schoolDateTime(e.ends_at,locale)}</p><p className="text-sm text-slate-600"><T text="Official version"/> {e.version} · {schoolDateTime(e.published_at,locale)}</p>{e.revision_start&&<p><T text="Revision week"/>: {schoolDate(e.revision_start,locale)} → {schoolDate(e.revision_end,locale)}</p>}{e.cancelled?<p className="font-semibold text-red-700"><T text="Exam cancelled"/></p>:e.scanned_at?<p className="text-emerald-700"><T text="Kiosk arrival"/>: {schoolDateTime(e.scanned_at,locale)}</p>:<p><T text="Exam scheduled"/></p>}{data.can_manage&&onEdit&&<button className="mt-2 text-blue-700 underline print:hidden" onClick={()=>onEdit(e)}><T text="Propose a schedule change"/></button>}</article>)}
  {!rows.length&&<p><T text="No exams announced for this selection."/></p>}
  <h3 className="font-semibold"><T text="Confirmed official exam dates"/></h3>
  {officialDates.map(date=><article key={date.id} className="rounded-xl border p-4"><p className="font-semibold"><T text={date.category==='official_exam'?'Official exam':'Exam period'}/> · <T text={date.section}/></p><p>{schoolDate(date.start_date,locale)} → {schoolDate(date.end_date,locale)}</p><p className="text-sm text-slate-700"><T text="Source wording"/>: {date.source_wording}</p><p className="text-xs text-slate-600">{date.source_name} · <a href={date.source_url} target="_blank" rel="noreferrer" className="text-blue-700 underline">{date.source_label}</a></p></article>)}
  {!officialDates.length&&<p><T text="No official exam dates confirmed for this selection."/></p>}
  <details><summary><T text="Period dates"/></summary>{data.periods.filter(p=>!selectedYear||p.year_id===selectedYear).map(p=><p key={p.id}>{p.name}: {schoolDate(p.start_date,locale)} → {schoolDate(p.end_date,locale)}</p>)}</details>
  <h3 className="font-semibold"><T text="Approved school closures"/></h3>{closures.map(c=><p key={c.day}>{schoolDate(c.day,locale)} · {c.title}</p>)}{!closures.length&&<p><T text="No approved closure dates."/></p>}
 </section>
}
export default function ExamCalendar({studentId}:{studentId?:string}){
 const {yearId:academicYearId}=useAcademicYear()
 const locale=useLocale(),t=(text:string)=>translate(text,locale)
 const [data,setData]=useState<CalendarData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const [exam,setExam]=useState<string|null>(null),[classId,setClassId]=useState(''),[subject,setSubject]=useState(''),[period,setPeriod]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[revisionStart,setRevisionStart]=useState(''),[revisionEnd,setRevisionEnd]=useState(''),[reason,setReason]=useState(''),[cancelled,setCancelled]=useState(false),[returnReason,setReturnReason]=useState('')
 const fetchCalendar=useCallback(async()=>{const db=createClient();const r=await db.rpc('school_calendar',{p_student:studentId||null});if(r.error)throw r.error;if(r.data?.can_manage){const workspace=await db.rpc('exam_schedule_workspace');if(workspace.error)throw workspace.error;const data=workspace.data as CalendarData;const yearIds=[...new Set(data.classes.map(c=>c.year_id))];const years=yearIds.length?await db.from('academic_years').select('id,start_date,end_date').in('id',yearIds):{data:[],error:null};if(years.error)throw years.error;return {...calendarWithConfirmedDates(data,r.data as CalendarData),classes:data.classes.map(c=>{const y=years.data?.find(y=>y.id===c.year_id);return {...c,year_start:y?.start_date,year_end:y?.end_date}})}}return r.data as CalendarData},[studentId])
 useEffect(()=>{let active=true;setData(null);setError('');fetchCalendar().then(d=>{if(active)setData(d)}).catch(()=>{if(active)setError('Unable to load the calendar.')});return()=>{active=false}},[fetchCalendar])
 const cls=data?.classes.find(c=>c.id===classId),selectedPeriod=data?.periods.find(p=>p.id===period&&p.year_id===cls?.year_id)
 useEffect(()=>{if(classId&&data&&!data.classes.some(c=>c.id===classId&&(!academicYearId||c.year_id===academicYearId)))reset()},[academicYearId,data])
 function edit(e:Exam|Version){setExam('exam_id'in e?e.exam_id:e.id);setClassId(e.class_id);setSubject(e.subject_id);setPeriod(e.period_id);setStart(localTime(e.starts_at));setEnd(localTime(e.ends_at));setRevisionStart(e.revision_start||'');setRevisionEnd(e.revision_end||'');setCancelled(e.cancelled);setReason('');setMessage('Editing a proposal. The official schedule remains unchanged.')}
 function reset(){setExam(null);setClassId('');setSubject('');setPeriod('');setStart('');setEnd('');setRevisionStart('');setRevisionEnd('');setCancelled(false);setReason('')}
 function failure(e:unknown){const code=e&&typeof e==='object'&&'message'in e?String(e.message):'';setError(errors[code]||'Unable to save. Please try again.')}
 async function decide(id:string,publish:boolean){if(!window.confirm(t(publish?'Publish this schedule version for the affected families and teachers?':'Return this proposal for correction?')))return;setBusy(true);setError('');try{const r=publish?await createClient().rpc('publish_exam_version',{p_version:id}):await createClient().rpc('return_exam_version',{p_version:id,p_reason:returnReason});if(r.error)throw r.error;setData(await fetchCalendar());setReturnReason('');setMessage(publish?'Official schedule published.':'Proposal returned.')}catch(e){failure(e)}finally{setBusy(false)}}
 return <div>{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-700"><T text={error}/></p>}{message&&<p role="status" className="rounded-xl bg-blue-50 p-3"><T text={message}/></p>}
  {data?.can_manage&&<form className="my-5 grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await createClient().rpc('save_exam',{p_class:classId,p_subject:subject,p_period:period,p_start:schoolDateTimeToISO(start),p_end:schoolDateTimeToISO(end),p_reason:reason,p_exam:exam,p_revision_start:revisionStart||null,p_revision_end:revisionEnd||null,p_cancelled:cancelled});if(r.error)throw r.error;setData(await fetchCalendar());reset();setMessage('Proposal saved. A Censeur must publish it before families see the change.')}catch(e){failure(e)}finally{setBusy(false)}}}>
   <h2 className="text-xl font-bold md:col-span-2"><T text={exam?'Propose a schedule change':'Schedule a class exam'}/></h2>
   <label><T text="Class"/><select required disabled={busy||Boolean(exam)} className="block w-full rounded border p-2" value={classId} onChange={e=>{setClassId(e.target.value);setSubject('');setPeriod('')}}><option value=""><T text="Choose"/></option>{data.classes.filter(c=>!academicYearId||c.year_id===academicYearId).map(c=><option key={c.id} value={c.id}>{c.year} · {c.name}</option>)}</select></label>
   <label><T text="Subject"/><select required disabled={busy||Boolean(exam)} className="block w-full rounded border p-2" value={subject} onChange={e=>setSubject(e.target.value)}><option value=""><T text="Choose"/></option>{data.subjects.filter(s=>s.class_id===classId).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
   <label><T text="Period"/><select required disabled={busy||Boolean(exam)} className="block w-full rounded border p-2" value={period} onChange={e=>setPeriod(e.target.value)}><option value=""><T text="Choose"/></option>{data.periods.filter(p=>cls&&p.year_id===cls.year_id&&p.sections.includes(cls.section)).map(p=><option key={p.id} value={p.id}>{p.name} · {schoolDate(p.start_date,locale)} → {schoolDate(p.end_date,locale)}</option>)}</select></label>
   <label><T text="Start date and time in Haiti"/><SchoolDateInput required type="datetime-local" min={selectedPeriod?.start_date||cls?.year_start} max={selectedPeriod?.end_date||cls?.year_end} value={start} onChange={e=>setStart(e.target.value)} className="block w-full rounded border p-2"/></label>
   <label><T text="End date and time in Haiti"/><SchoolDateInput required type="datetime-local" min={selectedPeriod?.start_date||cls?.year_start} max={selectedPeriod?.end_date||cls?.year_end} value={end} onChange={e=>setEnd(e.target.value)} className="block w-full rounded border p-2"/></label>
   <label><T text="Revision starts (optional)"/><SchoolDateInput min={cls?.year_start} max={start.slice(0,10)||cls?.year_end} value={revisionStart} onChange={e=>setRevisionStart(e.target.value)} className="block w-full rounded border p-2"/></label>
   <label><T text="Revision ends (optional)"/><SchoolDateInput min={revisionStart||cls?.year_start} max={start.slice(0,10)||cls?.year_end} value={revisionEnd} onChange={e=>setRevisionEnd(e.target.value)} className="block w-full rounded border p-2"/></label>
   {exam&&<label><input type="checkbox" checked={cancelled} onChange={e=>setCancelled(e.target.checked)}/> <T text="Propose cancellation"/></label>}
   <label className="md:col-span-2"><T text="Reason"/><textarea required minLength={3} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)} className="block w-full rounded border p-2"/></label>
   <button disabled={busy||!classId||!subject||!period||!start||!end||reason.trim().length<3} className="rounded-xl bg-blue-600 p-3 text-white disabled:opacity-40"><T text="Save proposal"/></button>{exam&&<button type="button" disabled={busy} onClick={reset} className="rounded border p-3"><T text="Cancel editing"/></button>}
  </form>}
  {data?.can_manage&&<section id="exam-calendar" className="my-5 space-y-4 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold"><T text="Schedule proposals and history"/></h2>{!data.can_publish&&<p><T text="A Censeur must publish this schedule."/></p>}<label className="block"><T text="Return reason"/><input value={returnReason} maxLength={2000} onChange={e=>setReturnReason(e.target.value)} className="ml-2 rounded border p-2"/></label>{!data.versions?.filter(v=>!academicYearId||v.snapshot.year===data.classes.find(c=>c.year_id===academicYearId)?.year).length&&<p><T text="No schedule proposals."/></p>}{data.versions?.filter(v=>!academicYearId||v.snapshot.year===data.classes.find(c=>c.year_id===academicYearId)?.year).map(v=><article key={v.id} className="space-y-2 rounded-xl border p-4"><h3 className="font-semibold">{v.snapshot.subject} · {v.snapshot.class} · <T text="Version"/> {v.version}</h3><p><T text={states[v.state]||v.state}/> · {v.creator} · {schoolDateTime(v.created_at,locale)}</p><p>{schoolDateTime(v.starts_at,locale)} → {schoolDateTime(v.ends_at,locale)}</p>{v.cancelled&&<p className="text-red-700"><T text="Proposed cancellation"/></p>}<p>{v.reason}</p><div className="flex flex-wrap gap-3">{v.state==='pending'&&<>{data.can_publish&&<button disabled={busy} onClick={()=>decide(v.id,true)} className="rounded bg-blue-600 p-2 text-white"><T text="Publish this version"/></button>}<button disabled={busy||returnReason.trim().length<3} onClick={()=>decide(v.id,false)} className="rounded border p-2 disabled:opacity-40"><T text="Return for correction"/></button></>}{v.state!=='superseded'&&<button disabled={busy} onClick={()=>edit(v)} className="text-blue-700 underline"><T text="Create revised proposal"/></button>}</div><details><summary><T text="History"/></summary>{v.events.map(e=><div key={e.id} className="mt-2 border-t pt-2 text-sm"><p>{e.actor_name} ({e.actor_role}) · <T text={e.action==='proposed'?'Proposed':e.action==='published'?'Published':'Returned for correction'}/> · {schoolDateTime(e.created_at,locale)}</p><p>{e.reason}</p>{e.old_value?.starts_at&&<p><T text="Previous time"/>: {schoolDateTime(e.old_value.starts_at,locale)} → {schoolDateTime(e.old_value.ends_at,locale)}</p>}{e.new_value?.starts_at&&<p><T text="Proposed time"/>: {schoolDateTime(e.new_value.starts_at,locale)} → {schoolDateTime(e.new_value.ends_at,locale)}</p>}</div>)}</details></article>)}</section>}
  {data?<CalendarView data={data} onEdit={busy?undefined:edit} academicYearId={academicYearId||undefined}/>:!error&&<p><T text="Loading calendar…"/></p>}
 </div>
}
