'use client'

import {useCallback,useEffect,useMemo,useState,type FormEvent} from 'react'
import {T,useLocale} from '@/components/translation-provider'
import {createClient} from '@/lib/supabase/client'
import {EMPTY_FINANCE_PAYMENT_METHODS,FINANCE_PAYMENT_METHODS,paymentMethodFieldLabel,type FinancePaymentMethod,type FinancePaymentMethods} from '@/lib/finance-payment-methods'
import {schoolDate} from '@/lib/school-date'

type Setup={payment_methods:FinancePaymentMethods;currency_code:string;moncash_payment_instructions?:string;natcash_payment_instructions?:string;bank_transfer_instructions?:string;general_payment_instructions?:string;brh_rate?:{date:string;rate:number;fetched_at:string;source_url:string}|null;latest_brh_date?:string|null}

function isRequired(key:keyof FinancePaymentMethods,method:FinancePaymentMethod,name:string){
 if(!method.enabled||name==='branch')return false
 if(name==='max_htg')return key==='moncash'||key==='natcash'
 if(key==='moncash'||key==='natcash')return name==='account_name'||name==='phone'
 if(key==='paypal')return name==='email'
 if(key==='zelle')return name==='account_name'||(name==='email'&&!method.phone)||(name==='phone'&&!method.email)
 return name==='bank_name'||name==='account_name'||name==='account_number'
}

export default function FinancePaymentMethodSettings({canManage,canRefreshRate,onRateStatus}:{canManage:boolean;canRefreshRate:boolean;onRateStatus?:(rate:Setup['brh_rate'],latestDate:string|null)=>void}){
 const db=useMemo(()=>createClient(),[]),locale=useLocale()
 const [methods,setMethods]=useState<FinancePaymentMethods>(EMPTY_FINANCE_PAYMENT_METHODS),[rate,setRate]=useState<Setup['brh_rate']>(null),[latestDate,setLatestDate]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const [legacyInstructions,setLegacyInstructions]=useState({moncash:'',natcash:'',bank:'',general:''})
 const load=useCallback(async()=>{const {data,error:loadError}=await db.rpc('finance_payment_setup');if(loadError)throw loadError;const value=(Array.isArray(data)?data[0]:data) as Setup|null;if(value){setMethods({...EMPTY_FINANCE_PAYMENT_METHODS,...value.payment_methods});setRate(value.brh_rate||null);setLatestDate(value.latest_brh_date||'');setLegacyInstructions({moncash:value.moncash_payment_instructions||'',natcash:value.natcash_payment_instructions||'',bank:value.bank_transfer_instructions||'',general:value.general_payment_instructions||''})}},[db])
 useEffect(()=>{void load().catch(()=>setError('Unable to load payment settings.')).finally(()=>setLoading(false))},[load])
 const field='w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-900'
 function update(key:keyof FinancePaymentMethods,field:keyof FinancePaymentMethod,value:string|boolean|number){setMethods(current=>({...current,[key]:{...current[key],[field]:value}}))}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError('');setNotice('');try{const {error:saveError}=await db.rpc('save_finance_payment_methods',{p_methods:methods});if(saveError)throw saveError;setNotice(locale==='fr'?'Les moyens de paiement ont été enregistrés.':'Metòd peman yo anrejistre.');await load()}catch(cause){setError(cause instanceof Error?cause.message:'Unable to save payment destinations.')}finally{setSaving(false)}}
 async function saveInstructions(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError('');setNotice('');try{const {error:saveError}=await db.rpc('save_finance_payment_instructions',{p_moncash:legacyInstructions.moncash,p_natcash:legacyInstructions.natcash,p_bank_transfer:legacyInstructions.bank,p_general:legacyInstructions.general});if(saveError)throw saveError;setNotice(locale==='fr'?'Les instructions générales ont été enregistrées.':'Enstriksyon jeneral yo anrejistre.');await load()}catch(cause){setError(cause instanceof Error?cause.message:'Unable to save payment instructions.')}finally{setSaving(false)}}
 async function refreshRate(){setRefreshing(true);setError('');setNotice('');try{const response=await fetch('/api/finance/brh-rate',{method:'POST'});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'brh_rate_refresh_failed');await load();const {data:statusData}=await db.rpc('finance_payment_setup');const status=(Array.isArray(statusData)?statusData[0]:statusData) as Setup|null;onRateStatus?.(status?.brh_rate||null,status?.latest_brh_date||null);const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Port-au-Prince'}).format(new Date());if(result.effective_date===today&&status?.brh_rate){setNotice(locale==='fr'?'Le taux BRH du jour a été confirmé.':'To BRH pou jodi a konfime.')}else{const publishedDate=schoolDate(status?.latest_brh_date||result.effective_date||'',locale);setNotice(locale==='fr'?`Le dernier taux publié est daté du ${publishedDate}. Les validations en USD restent bloquées jusqu’à la publication du taux du jour.`:`Dènye to BRH ki pibliye a date ${publishedDate}. Apwobasyon USD rete bloke jiskaske BRH pibliye to jodi a.`)}}catch(cause){setError(cause instanceof Error?cause.message:'Unable to refresh the BRH rate.')}finally{setRefreshing(false)}}
 if(loading)return <section className="rounded-2xl border border-slate-200 bg-white p-5"><T text="Loading..."/></section>
 return <div className="space-y-4">
  {canManage&&<form onSubmit={save} className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
   <div><h2 className="text-lg font-semibold"><T text="Payment destinations"/></h2><p className="mt-1 text-sm text-slate-600"><T text="Enable a method only after its receiving account is ready. Linked families see enabled destinations; digital payments require a reference and proof."/></p></div>
   {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800"><T text={error}/></p>}{notice&&<p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
   <div className="grid gap-3 xl:grid-cols-2">{FINANCE_PAYMENT_METHODS.map(method=>{const item=methods[method.key];return <fieldset key={method.key} className="space-y-3 rounded-xl border border-slate-200 p-4"><legend className="px-1 font-semibold"><T text={method.title}/></legend><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!item.enabled} onChange={event=>update(method.key,'enabled',event.target.checked)}/><T text="Enable this method"/></label>{method.fields.map(name=><label key={name} className="block text-sm"><T text={paymentMethodFieldLabel(name)}/><input className={`${field} mt-1`} type={name==='max_htg'?'number':name==='email'?'email':'text'} min={name==='max_htg'?'0.01':undefined} step={name==='max_htg'?'0.01':undefined} maxLength={name==='max_htg'?undefined:254} required={isRequired(method.key,item,name)} value={item[name]??''} onChange={event=>update(method.key,name,name==='max_htg'?(event.target.value?Number(event.target.value):''):event.target.value)}/></label>)}</fieldset>})}</div>
   <button disabled={saving} className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><T text={saving?'Saving...':'Save payment destinations'}/></button>
  </form>}
  <section className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold"><T text="BRH reference rate"/></h2><p className="mt-1 text-sm text-slate-600"><T text="USD payment approval is blocked until the BRH publishes a rate for today in Haiti. The approved payment stores the rate, date and source as an immutable snapshot."/></p></div>{canRefreshRate&&<button type="button" disabled={refreshing} onClick={()=>void refreshRate()} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-semibold disabled:opacity-50"><T text={refreshing?'Checking official source...':'Refresh BRH rate'}/></button>}</div>{rate?<p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-900">{new Intl.NumberFormat('fr-HT',{maximumFractionDigits:6}).format(Number(rate.rate))} HTG/USD · {schoolDate(rate.date,locale)} · <a href={rate.source_url} target="_blank" rel="noreferrer" className="underline"><T text="Official source"/></a></p>:<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900"><T text="No BRH rate has been confirmed for today yet."/> {latestDate&&<span><T text="Latest published rate date"/>: {schoolDate(latestDate,locale)}</span>}</p>}</section>
  {canManage&&<form onSubmit={saveInstructions} className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><h2 className="text-lg font-semibold"><T text="Payment location and notes"/></h2><p className="mt-1 text-sm text-slate-600"><T text="Add the school cashier location, opening hours or any extra payment instructions."/></p></div><textarea maxLength={1200} rows={3} className={field} value={legacyInstructions.general} onChange={event=>setLegacyInstructions(current=>({...current,general:event.target.value}))}/><button disabled={saving} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-semibold disabled:opacity-50"><T text="Save payment location"/></button></form>}
 </div>
}
