'use client'
import {useCallback,useEffect,useState} from 'react'
import {T} from '@/components/translation-provider'
import {schoolDateTime} from '@/lib/school-date'
import {createClient} from '@/lib/supabase/client'

type HomeArrival={student_id:string;student:string;class:string;check_out_at:string;confirmed_at:string|null;confirmed_as:'parent'|'student'|null}
type StaffWorkspace={enabled:boolean;can_manage:boolean;students:HomeArrival[]}

export function HomeArrivalStaffPanel(){
 const [data,setData]=useState<StaffWorkspace>({enabled:false,can_manage:false,students:[]}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const load=useCallback(async()=>{const {data,error}=await createClient().rpc('home_arrival_staff_workspace');if(error){setError('Unable to load the home-arrival status.');return}setData(data as StaffWorkspace)},[])
 useEffect(()=>{void load();const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void load()},20000);return()=>window.clearInterval(timer)},[load])
 async function toggle(){setBusy(true);setError('');setMessage('');const {error}=await createClient().rpc('set_home_arrival_enabled',{p_enabled:!data.enabled});setBusy(false);if(error){setError(error.message==='not_authorized'?'Only the Director can activate this feature.':'Unable to update this setting.');return}setMessage(data.enabled?'Home-arrival confirmation has been deactivated.':'Home-arrival confirmation is active for linked family and student accounts.');await load()}
 return <section className="mt-6 rounded-2xl border border-blue-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold"><T text="Home-arrival confirmation"/></h2><p className="mt-1 max-w-3xl text-sm text-slate-600"><T text="After a student checks out, the linked parent or student can confirm arrival at home. Only the Director can activate this feature for the school."/></p></div>{data.can_manage&&<button disabled={busy} onClick={()=>void toggle()} className={`rounded-lg px-4 py-2 font-semibold text-white ${data.enabled?'bg-slate-700':'bg-blue-700'}`}><T text={data.enabled?'Deactivate':'Activate'}/></button>}</div>{error&&<p role="alert" className="mt-3 text-sm text-red-700"><T text={error}/></p>}{message&&<p role="status" className="mt-3 text-sm text-green-800"><T text={message}/></p>}<p className="mt-3 text-sm"><strong><T text="Status"/>:</strong> <T text={data.enabled?'Active':'Inactive'}/></p>{data.enabled&&<div className="mt-4"><h3 className="font-semibold"><T text="Students checked out today"/></h3>{!data.students.length?<p className="mt-2 text-sm text-slate-500"><T text="No KIOS check-outs yet today."/></p>:<ul className="mt-2 divide-y">{data.students.map(s=><li key={s.student_id} className="flex flex-wrap justify-between gap-2 py-3"><span><strong>{s.student}</strong> · {s.class}<span className="block text-sm text-slate-600"><T text="Check-out"/> {schoolDateTime(s.check_out_at)}</span></span><span className="text-sm">{s.confirmed_at?<><T text="Home arrival confirmed"/> · <T text={s.confirmed_as==='student'?'Student':'Parent'}/> · {schoolDateTime(s.confirmed_at)}</>:<T text="Awaiting home-arrival confirmation"/>}</span></li>)}</ul>}</div>}</section>
}

export function FamilyHomeArrivalPanel({studentId}:{studentId:string}){
 const [data,setData]=useState<HomeArrival|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const load=useCallback(async()=>{if(!studentId){setData(null);setLoading(false);return}const {data,error}=await createClient().rpc('family_home_arrival_status',{p_student:studentId});if(error){setError('Unable to load the home-arrival status.');setData(null)}else{setError('');setData(data as HomeArrival|null)}setLoading(false)},[studentId])
 useEffect(()=>{setLoading(true);void load();const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void load()},20000);return()=>window.clearInterval(timer)},[load])
 async function confirm(){setBusy(true);setError('');setMessage('');const {error}=await createClient().rpc('confirm_family_home_arrival',{p_student:studentId});setBusy(false);if(error){setError(error.message==='student_not_checked_out'?'The student must check out through KIOS before confirming arrival.':'Unable to save the confirmation.');return}setMessage('Arrival at home confirmed.');await load()}
 if(!loading&&!data&&!error)return null
 return <section className="my-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 print:hidden"><h2 className="text-lg font-semibold"><T text="Home-arrival confirmation"/></h2>{loading?<p className="mt-2 text-sm"><T text="Loading..."/></p>:error?<p role="alert" className="mt-2 text-sm text-red-700"><T text={error}/></p>:data&&<><p className="mt-2 text-sm"><T text="KIOS check-out"/> · {schoolDateTime(data.check_out_at)}</p>{data.confirmed_at?<p role="status" className="mt-2 text-sm text-green-800"><T text="Home arrival confirmed"/> · {schoolDateTime(data.confirmed_at)} ({data.confirmed_as==='student'?<T text="Student"/>:<T text="Parent"/>})</p>:<><p className="mt-2 text-sm"><T text="Has the student arrived home safely?"/></p><button disabled={busy} onClick={()=>void confirm()} className="mt-3 rounded bg-emerald-700 px-4 py-2 font-semibold text-white disabled:opacity-50"><T text="Confirm arrival at home"/></button></>}{message&&<p role="status" className="mt-2 text-sm text-green-800"><T text={message}/></p>}</>}</section>
}
