'use client'
import {useCallback,useEffect,useState} from 'react'
import {T} from '@/components/translation-provider'
import {schoolTime} from '@/lib/school-date'
import {createClient} from '@/lib/supabase/client'

type Event={event_type:string;outcome:string|null;private_note:string|null;actor:string;role:string;created_at:string}
type Student={student_id:string;student:string;class:string;attendance_id:string;check_in_at:string;case_id:string|null;case_status:'pending_direction'|'active'|null;reason_category:string|null;private_note:string|null;opened_at:string|null;events:Event[]}
export default function KindergartenRelocationStaff(){
 const [students,setStudents]=useState<Student[]>([]),[canReview,setCanReview]=useState(false),[student,setStudent]=useState(''),[reason,setReason]=useState('needs_support'),[note,setNote]=useState(''),[contact,setContact]=useState('no_answer'),[contactNote,setContactNote]=useState(''),[reviewNotes,setReviewNotes]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const load=useCallback(async()=>{const {data,error}=await createClient().rpc('kindergarten_relocation_workspace');if(error){setError('Unable to load the private Preschool relocation list.');return}const rows=(data?.students||[]) as Student[];setStudents(rows);setCanReview(Boolean(data?.can_review_direction));if(!rows.some(s=>s.student_id===student&&!s.case_id))setStudent(rows.find(s=>!s.case_id)?.student_id||'')},[student])
 useEffect(()=>{void load()},[load])
 async function start(){if(!student)return;setBusy(true);setError('');setMessage('');const {error}=await createClient().rpc('start_kindergarten_relocation',{p_student:student,p_reason:reason,p_note:note.trim()||null});setBusy(false);if(error){setError(error.message==='student_not_on_campus'?'The student is no longer on campus.':error.message==='already_picked_up'?'This student has already been picked up today.':'Unable to request the private relocation.');return}setNote('');setMessage('Relocation request sent to Direction. Do not move the student until it is approved.');await load()}
 async function logContact(id:string){setBusy(true);setError('');const {error}=await createClient().rpc('record_kindergarten_parent_contact',{p_case:id,p_outcome:contact,p_note:contactNote.trim()||null});setBusy(false);if(error){setError('Unable to record the parent contact attempt.');return}setContactNote('');setMessage('Parent contact attempt recorded.');await load()}
 async function returnToClass(id:string){setBusy(true);setError('');const {error}=await createClient().rpc('return_kindergarten_student_to_class',{p_case:id,p_note:null});setBusy(false);if(error){setError(error.message==='student_not_on_campus'?'The student is no longer on campus.':'Unable to close the relocation.');return}setMessage('Student returned to class.');await load()}
 async function review(id:string,approve:boolean){setBusy(true);setError('');const {error}=await createClient().rpc('review_kindergarten_relocation',{p_case:id,p_approve:approve,p_note:reviewNotes[id]||null});setBusy(false);if(error){setError(error.message==='not_authorized'?'Only the Director can review a relocation.':error.message==='invalid_relocation_review'?'Enter a reason when rejecting the request.':'Unable to review the relocation request.');return}setMessage(approve?'Relocation approved. Staff may now move the student.':'Relocation request rejected.');await load()}
 const selected=students.find(s=>s.student_id===student&&!s.case_id)
 return <section className="my-6 rounded-xl border border-amber-300 bg-amber-50 p-5"><h2 className="text-xl font-semibold"><T text="Kindergarten private relocation"/></h2><p className="mt-1 text-sm text-slate-700"><T text="Request a private Preschool relocation. The student must remain with current staff until the Director approves; the family is asked to collect the child urgently."/></p>{error&&<p role="alert" className="mt-3 text-red-700"><T text={error}/></p>}{message&&<p role="status" className="mt-3 text-green-800"><T text={message}/></p>}
  {selected&&<div className="mt-4 grid gap-3 rounded-lg border bg-white p-4 md:grid-cols-2"><label className="text-sm"><T text="Student on campus"/><select value={student} onChange={e=>setStudent(e.target.value)} className="mt-1 w-full rounded border p-2">{students.filter(s=>!s.case_id).map(s=><option key={s.student_id} value={s.student_id}>{s.student} · {s.class}</option>)}</select></label><label className="text-sm"><T text="Reason category"/><select value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 w-full rounded border p-2"><option value="needs_support"><T text="Needs support"/></option><option value="safety"><T text="Safety concern"/></option><option value="other"><T text="Other"/></option></select></label><label className="text-sm md:col-span-2"><T text="Private staff note"/><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000} className="mt-1 w-full rounded border p-2" rows={2}/></label><button disabled={busy} onClick={()=>void start()} className="w-fit rounded bg-amber-800 px-4 py-2 text-white disabled:opacity-50"><T text="Request relocation review"/></button></div>}
  {!students.length&&<p className="mt-3 text-sm text-slate-600"><T text="No Preschool students are currently on campus."/></p>}
  <div className="mt-4 space-y-3">{students.filter(s=>s.case_id).map(s=><article key={s.case_id} className="rounded-lg border bg-white p-4"><div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-semibold">{s.student} · {s.class}</h3><p className="text-sm text-slate-600"><T text={s.case_status==='pending_direction'?'Awaiting Direction approval':'At school office since'}/> {schoolTime(s.opened_at||'')}</p><p className="text-sm"><T text={s.reason_category||''}/>{s.private_note?` · ${s.private_note}`:''}</p></div>{s.case_status==='pending_direction'&&canReview?<div className="grid gap-2"><input aria-label="Review note" value={reviewNotes[s.case_id!]||''} onChange={e=>setReviewNotes(current=>({...current,[s.case_id!]:e.target.value}))} placeholder="Reason required if rejecting" className="rounded border px-3 py-2"/><div className="flex gap-2"><button disabled={busy} onClick={()=>void review(s.case_id!,true)} className="rounded bg-green-700 px-3 py-2 text-white"><T text="Approve relocation"/></button><button disabled={busy||!(reviewNotes[s.case_id!]||'').trim()} onClick={()=>void review(s.case_id!,false)} className="rounded border border-red-300 px-3 py-2 text-red-800 disabled:opacity-50"><T text="Reject request"/></button></div></div>:s.case_status==='active'?<button disabled={busy} onClick={()=>void returnToClass(s.case_id!)} className="h-fit rounded border px-3 py-2"><T text="Return student to class"/></button>:<span className="h-fit rounded bg-amber-100 px-3 py-2 text-sm"><T text="Waiting for Direction; do not move the student"/></span>}</div>{s.case_status==='active'&&<div className="mt-3 grid gap-2 md:grid-cols-[1fr_2fr_auto]"><label className="text-sm"><T text="Contact result"/><select value={contact} onChange={e=>setContact(e.target.value)} className="mt-1 w-full rounded border p-2"><option value="reached"><T text="Reached"/></option><option value="no_answer"><T text="No answer"/></option><option value="message_left"><T text="Message left"/></option></select></label><label className="text-sm"><T text="Private contact note"/><input value={contactNote} onChange={e=>setContactNote(e.target.value)} maxLength={1000} className="mt-1 w-full rounded border p-2"/></label><button disabled={busy} onClick={()=>void logContact(s.case_id!)} className="self-end rounded bg-blue-700 px-3 py-2 text-white"><T text="Record contact attempt"/></button></div>}<ol className="mt-3 space-y-1 border-t pt-2 text-xs text-slate-600">{s.events.map((e,i)=><li key={`${e.event_type}-${e.created_at}-${i}`}>{schoolTime(e.created_at)} · <T text={e.event_type}/> · {e.actor} ({e.role}){e.outcome?` · `:''}{e.outcome&&<T text={e.outcome}/>} {e.private_note?`· ${e.private_note}`:''}</li>)}</ol></article>)}</div>
 </section>
}
