'use client'
import {useCallback,useEffect,useState} from 'react'
import {T} from '@/components/translation-provider'
import {schoolTime} from '@/lib/school-date'
import {createClient} from '@/lib/supabase/client'
type Child={student_id:string;student:string;class:string;authorization_status:string;picked_up:string|null;picked_up_by:string|null}
export default function KindergartenPickupFamily(){
 const [children,setChildren]=useState<Child[]>([]),[notes,setNotes]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(''),[message,setMessage]=useState('')
 const load=useCallback(async()=>{const {data,error}=await createClient().rpc('kindergarten_parent_pickup_status');if(error){setError('Unable to load Preschool pickup status.');return}setChildren((data||[]) as Child[])},[])
 useEffect(()=>{void load()},[load])
 async function notify(id:string,status:'on_the_way'|'delay'){setBusy(id);setError('');setMessage('');const {error}=await createClient().rpc('guardian_note_kindergarten_pickup',{p_student:id,p_status:status,p_note:notes[id]||null});setBusy('');if(error){setError(error.message==='already_picked_up'?'This student has already been picked up today.':error.message==='pickup_update_already_sent'?'You have already sent this pickup update today.':'Unable to send the pickup update.');return}setMessage('Your update was sent to authorized school staff.');setNotes(v=>({...v,[id]:''}));await load()}
 if(!children.length&&!error)return null
 return <section className="my-6 rounded-xl border bg-amber-50 p-5 print:hidden"><h2 className="text-xl font-bold"><T text="Preschool pickup status"/></h2><p className="mt-1 text-sm text-slate-700"><T text="Let the school know when you are on the way or delayed. Staff records the final pickup after scanning the child's badge."/></p>{error&&<p role="alert" className="mt-3 text-red-700"><T text={error}/></p>}{message&&<p role="status" className="mt-3 text-green-800"><T text={message}/></p>}<div className="mt-3 space-y-3">{children.map(c=><article key={c.student_id} className="rounded-lg border bg-white p-4"><p className="font-semibold">{c.student} · {c.class}</p><p className="mt-1 text-sm"><T text="Latest update"/>: <T text={c.authorization_status}/></p>{c.picked_up?<p className="mt-2 text-sm text-green-800"><T text="Picked up by"/> {c.picked_up_by} · {schoolTime(c.picked_up)}</p>:<><label className="block text-sm"><T text="Optional note"/><input value={notes[c.student_id]||''} onChange={e=>setNotes(v=>({...v,[c.student_id]:e.target.value}))} maxLength={500} className="mt-2 w-full rounded border p-2"/></label><div className="mt-2 flex flex-wrap gap-2"><button disabled={busy===c.student_id} onClick={()=>void notify(c.student_id,'on_the_way')} className="rounded bg-blue-700 px-3 py-2 text-white"><T text="On the way"/></button><button disabled={busy===c.student_id} onClick={()=>void notify(c.student_id,'delay')} className="rounded border px-3 py-2"><T text="Running late"/></button></div></>}</article>)}</div></section>
}
