'use client'
import {useCallback,useEffect,useState,type FormEvent} from 'react'
import {T} from '@/components/translation-provider'
import {schoolDateTime} from '@/lib/school-date'
import {createClient} from '@/lib/supabase/client'

type Protocol={id:string;date:string;activated_at:string;activated_name:string;activated_role:string;reason:string}
type Workspace={date:string;active:boolean;can_activate:boolean;protocol:Protocol|null}

export default function SchoolReleaseProtocolPanel(){
 const [data,setData]=useState<Workspace|null>(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const load=useCallback(async()=>{const {data,error}=await createClient().rpc('school_release_protocol_workspace');if(error){setError('Unable to load the school-release protocol.');return}setData(data as Workspace)},[])
 useEffect(()=>{void load();const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void load()},20000);return()=>window.clearInterval(timer)},[load])
 async function activate(event:FormEvent){event.preventDefault();if(!confirmed||reason.trim().length<3)return;setBusy(true);setError('');setMessage('');const {data:next,error}=await createClient().rpc('activate_school_release_protocol',{p_reason:reason.trim()});setBusy(false);if(error){setError(error.message==='not_authorized'?'Only school Direction, the school administrator, or the secretary can activate this protocol.':error.message==='reason_required'?'Enter a reason of at least three characters.':'Unable to activate the school-release protocol.');return}setData(next as Workspace);setMessage('The school-release protocol is active for today. KIOS will allow checked-in non-Preschool students to check out. Preschool students must be collected through the pickup workflow.');setReason('');setConfirmed(false)}
 return <section className="mt-6 rounded-2xl border border-amber-300 bg-amber-50 p-5 shadow-sm"><div><h2 className="text-xl font-semibold"><T text="School release protocol"/></h2><p className="mt-1 max-w-4xl text-sm text-slate-700"><T text="Activate an authorized school-wide dismissal for today. Checked-in students outside Preschool may check out at KIOS. Preschool students must be collected through the Preschool pickup workflow. Finance and GUARD restrictions remain active."/></p></div>{error&&<p role="alert" className="mt-3 text-sm text-red-700"><T text={error}/></p>}{message&&<p role="status" className="mt-3 rounded bg-green-100 p-3 text-sm text-green-900"><T text={message}/></p>}{data?.active&&data.protocol?<div className="mt-4 rounded-xl border border-amber-300 bg-white p-4"><p className="font-semibold"><T text="School release protocol is active today"/></p><p className="mt-1 text-sm"><T text="Activated by"/>: {data.protocol.activated_name} · <T text={data.protocol.activated_role}/></p><p className="text-sm"><T text="Activated at"/>: {schoolDateTime(data.protocol.activated_at)}</p><p className="text-sm"><T text="Reason"/>: {data.protocol.reason}</p></div>:data?.can_activate&&<form onSubmit={activate} className="mt-4 space-y-3 rounded-xl border border-amber-200 bg-white p-4"><label className="block text-sm font-semibold"><T text="Reason for school dismissal"/><textarea required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} className="mt-2 block min-h-20 w-full rounded-lg border border-slate-300 p-3 font-normal"/></label><label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} required className="mt-1"/><span><T text="I confirm that school Direction is dismissing all students except Preschool, who must be collected through the pickup workflow. Finance and GUARD restrictions remain in effect."/></span></label><button disabled={busy||!confirmed||reason.trim().length<3} className="rounded-lg bg-amber-800 px-4 py-2 font-semibold text-white disabled:opacity-50"><T text={busy?'Saving…':'Activate school release protocol'}/></button></form>}{data&&!data.can_activate&&!data.active&&<p className="mt-3 text-sm text-slate-600"><T text="Only school Direction, the school administrator, or the secretary can activate this protocol."/></p>}</section>
}
