'use client'
import {useEffect,useMemo,useState} from 'react'
import {T} from '@/components/translation-provider'
import {createClient} from '@/lib/supabase/client'
import QRScanner from '@/components/qr-scanner'

type Student={id:string;name:string;atechos_id:string|null;class:string|null}
type ClassItem={id:string;name:string}
type SanctionType={id:string;name:string;active:boolean;action_code:string;action_duration_days:number|null}
type Settings={school_entry_time:string;school_departure_time:string}|null
type Action=(name:string,args:Record<string,unknown>,success:string)=>Promise<boolean>

export default function StudentCollectiveSanctions({students,classes,types,settings,action,busy}:{students:Student[];classes:ClassItem[];types:SanctionType[];settings:Settings;action:Action;busy:boolean}){
 const [entry,setEntry]=useState(''),[departure,setDeparture]=useState(''),[mode,setMode]=useState<'students'|'class'>('students')
 const [typeId,setTypeId]=useState(''),[incident,setIncident]=useState(''),[reason,setReason]=useState('')
 const [query,setQuery]=useState(''),[open,setOpen]=useState(false),[scanner,setScanner]=useState(false),[ids,setIds]=useState<string[]>([])
 const [classId,setClassId]=useState(''),[attendees,setAttendees]=useState<Student[]>([]),[localError,setLocalError]=useState('')
 useEffect(()=>{setEntry(settings?.school_entry_time?.slice(0,5)||'');setDeparture(settings?.school_departure_time?.slice(0,5)||'')},[settings])
 const matches=useMemo(()=>students.filter(s=>!ids.includes(s.id)&&`${s.name} ${s.atechos_id||''} ${s.class||''}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).slice(0,8),[students,ids,query])
 const queue=(s:Student)=>{setIds(current=>current.includes(s.id)?current:[...current,s.id]);setQuery('');setOpen(false);setScanner(false);setLocalError('')}
 async function scan(qr:string){setScanner(false);setLocalError('');const {data,error}=await createClient().rpc('lookup_student_for_followup_badge',{p_qr:qr.trim()});if(error){setLocalError(error.message);return}queue(data as Student)}
 async function preview(){setLocalError('');if(!classId||!incident){setLocalError('Choose a class and incident date first.');return}const {data,error}=await createClient().rpc('student_followup_class_attendees',{p_class:classId,p_day:incident.slice(0,10)});if(error){setLocalError(error.message);return}const presentIds=(data as {id:string}[]).map(s=>s.id);setAttendees(students.filter(s=>presentIds.includes(s.id)))}
 async function submit(){setLocalError('');if(!typeId||!incident||reason.trim().length<3){setLocalError('Complete the sanction type, date, and reason.');return}const args={p_type:typeId,p_reason:reason.trim(),p_incident_at:new Date(incident).toISOString()};const ok=await action(mode==='class'?'create_class_student_sanctions':'create_student_sanctions_bulk',mode==='class'?{...args,p_class:classId}:{...args,p_students:ids},'Collective sanction recorded.');if(ok){setIds([]);setAttendees([]);setReason('')}}
 return <section className="grid gap-6 xl:grid-cols-2">
  <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold"><T text="School hours for sanction meetings"/></h2><p className="mt-1 text-sm text-slate-600"><T text="Parents can choose a meeting time within these school hours. Configure the school's entry and departure times first."/></p><form className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]" onSubmit={e=>{e.preventDefault();void action('save_student_sanction_hours',{p_entry:entry,p_departure:departure},'School hours saved.')}}><label className="text-sm"><T text="School entry time"/><input required type="time" value={entry} onChange={e=>setEntry(e.target.value)} className="mt-1 block w-full rounded-lg border p-2"/></label><label className="text-sm"><T text="School departure time"/><input required type="time" value={departure} onChange={e=>setDeparture(e.target.value)} className="mt-1 block w-full rounded-lg border p-2"/></label><button disabled={busy||!entry||!departure} className="self-end rounded-lg bg-blue-700 px-4 py-2 font-medium text-white disabled:opacity-50"><T text="Save school hours"/></button></form></article>
  <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-semibold"><T text="Collective sanction"/></h2><span className="rounded-full bg-blue-50 px-3 py-1 text-sm text-blue-900"><T text="One type, date, and reason for all selected students"/></span></div><p className="mt-1 text-sm text-slate-600"><T text="Choose students one by one by badge or name, or apply the sanction to students recorded present in a class on that date."/></p>
   <div className="mt-4 flex gap-2"><button type="button" onClick={()=>{setMode('students');setAttendees([])}} className={`rounded-lg px-3 py-2 text-sm ${mode==='students'?'bg-blue-700 text-white':'border'}`}><T text="Selected students"/></button><button type="button" onClick={()=>{setMode('class');setIds([])}} className={`rounded-lg px-3 py-2 text-sm ${mode==='class'?'bg-blue-700 text-white':'border'}`}><T text="Present students by class"/></button></div>
   <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm"><T text="Sanction type"/><select required value={typeId} onChange={e=>setTypeId(e.target.value)} className="mt-1 w-full rounded-lg border p-2"><option value=""><T text="Choose a sanction"/></option>{types.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="text-sm"><T text="Incident date and time"/><input required type="datetime-local" value={incident} onChange={e=>{setIncident(e.target.value);setAttendees([])}} className="mt-1 w-full rounded-lg border p-2"/></label></div>
   <label className="mt-3 block text-sm"><T text="Reason"/><textarea required minLength={3} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)} rows={2} className="mt-1 w-full rounded-lg border p-2"/></label>
   {mode==='students'?<div className="mt-3 space-y-3"><div className="grid gap-2 sm:grid-cols-[1fr_auto]"><div className="relative"><label className="text-sm"><T text="Find a student"/><input type="search" value={query} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true)}} className="mt-1 w-full rounded-lg border p-3" placeholder="Nom, prénom ou AOS-…"/></label>{open&&matches.length>0&&<ul role="listbox" className="absolute z-20 mt-1 max-h-52 w-full overflow-auto rounded-lg border bg-white shadow-lg">{matches.map(s=><li key={s.id}><button type="button" role="option" onClick={()=>queue(s)} className="w-full px-3 py-2 text-left hover:bg-blue-50"><span className="block font-medium">{s.name}</span><span className="text-sm text-slate-600">{s.atechos_id||'—'}{s.class?` · ${s.class}`:''}</span></button></li>)}</ul>}</div><button type="button" onClick={()=>setScanner(v=>!v)} className="self-end rounded-lg border border-blue-700 px-4 py-3 text-blue-800"><T text={scanner?'Close badge scanner':'Scan badge to add student'}/></button></div>{scanner&&<div className="rounded-lg bg-slate-50 p-3"><QRScanner onRead={value=>void scan(value)}/></div>}<ul className="flex flex-wrap gap-2">{ids.map(id=>{const s=students.find(item=>item.id===id);return s?<li key={id} className="flex items-center gap-2 rounded-full bg-blue-50 px-3 py-1 text-sm"><span>{s.name} · {s.atechos_id||'—'}</span><button type="button" aria-label="Remove student" onClick={()=>setIds(current=>current.filter(x=>x!==id))} className="font-bold">×</button></li>:null})}</ul></div>:<div className="mt-3 space-y-3"><div className="grid gap-2 sm:grid-cols-[1fr_auto]"><label className="text-sm"><T text="Class"/><select required value={classId} onChange={e=>{setClassId(e.target.value);setAttendees([])}} className="mt-1 w-full rounded-lg border p-2"><option value=""><T text="Choose a class"/></option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button type="button" disabled={busy||!classId||!incident} onClick={()=>void preview()} className="self-end rounded-lg border px-4 py-2 disabled:opacity-50"><T text="Preview present students"/></button></div><p className="text-sm text-slate-600"><T text="Only students with a present or late attendance record for this class and date are included."/></p>{attendees.length>0&&<ul className="flex flex-wrap gap-2">{attendees.map(s=><li key={s.id} className="rounded-full bg-emerald-50 px-3 py-1 text-sm">{s.name}</li>)}</ul>}</div>}
   {localError&&<p role="alert" className="mt-3 text-sm text-red-700"><T text={localError}/></p>}<button type="button" disabled={busy||!typeId||!incident||reason.trim().length<3||(mode==='students'?!ids.length:!classId)} onClick={()=>void submit()} className="mt-4 rounded-lg bg-blue-700 px-5 py-3 font-semibold text-white disabled:opacity-50"><T text="Apply collective sanction"/></button>
  </article>
 </section>
}
