'use client'
import { useCallback,useEffect,useMemo,useState } from 'react'
import { T } from '@/components/translation-provider'
import { createClient } from '@/lib/supabase/client'
import { schoolDateTime } from '@/lib/school-date'

type Student={id:string;name:string;class:string|null}
type SanctionType={id:string;name:string;active:boolean}
type Sanction={id:string;student_id:string;student:string;sanction_type_id:string;incident_at:string;reason:string;status:'active'|'resolved';resolution:string|null;created_role:string}
type Contact={id:string;student_id:string;full_name:string;relationship:string;phone:string|null;active:boolean}
type Release={id:string;student_id:string;student:string;kind:'medical'|'exceptional';reason:string;contact_name:string;contact_relationship:string;status:'pending'|'approved'|'rejected'|'released'|'returned';decision_reason:string|null;requested_at:string;expected_return_at:string|null}
type Workspace={students:Student[];sanction_types:SanctionType[];sanctions:Sanction[];contacts:Contact[];releases:Release[]}
function explainError(message:string){const known:Record<string,string>={not_authorized:'You do not have permission to manage these records.',invalid_sanction_type:'Enter a sanction type name.',sanction_type_exists:'This sanction type already exists.',student_not_found:'Choose an active student from your school.',sanction_type_not_found:'Choose an active sanction type.',invalid_sanction:'Check the incident date and reason.',release_contact_not_authorized:'Choose an active authorized contact for this student.',invalid_release_contact:'Enter the contact name and relationship.',release_contact_exists:'An active contact with this name already exists.',invalid_release:'Choose a departure type and enter its reason.',decision_reason_required:'Enter a reason when rejecting a request.',release_not_pending:'This request has already been reviewed.',release_not_approved:'Approve the request before recording departure.',invalid_expected_return:'Choose a future expected return time.',student_not_released:'Record a departure before confirming return.'};return known[message]||'The action could not be completed. Refresh the page and try again.'}
export default function SanctionsPage(){
 const [data,setData]=useState<Workspace>({students:[],sanction_types:[],sanctions:[],contacts:[],releases:[]}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[authorized,setAuthorized]=useState(true)
 const [typeName,setTypeName]=useState(''),[student,setStudent]=useState(''),[typeId,setTypeId]=useState(''),[reason,setReason]=useState(''),[incident,setIncident]=useState('')
 const [contactStudent,setContactStudent]=useState(''),[contactName,setContactName]=useState(''),[relationship,setRelationship]=useState(''),[phone,setPhone]=useState(''),[resolutions,setResolutions]=useState<Record<string,string>>({})
 const [releaseStudent,setReleaseStudent]=useState(''),[releaseKind,setReleaseKind]=useState<'medical'|'exceptional'>('medical'),[contactId,setContactId]=useState(''),[releaseReason,setReleaseReason]=useState(''),[comments,setComments]=useState<Record<string,string>>({}),[returnTimes,setReturnTimes]=useState<Record<string,string>>({})
 const load=useCallback(async()=>{setLoading(true);setError('');const {data:result,error:problem}=await createClient().rpc('student_followup_workspace');if(problem){setAuthorized(problem.message!=='not_authorized');setError(explainError(problem.message))}else{setAuthorized(true);setData(result as Workspace)}setLoading(false)},[])
 useEffect(()=>{void load()},[load])
 const activeStudents=useMemo(()=>data.students,[data.students]),activeTypes=data.sanction_types.filter(t=>t.active),activeContacts=data.contacts.filter(c=>c.active&&c.student_id===releaseStudent)
 const action=async(name:string,args:Record<string,unknown>,success:string)=>{setBusy(true);setError('');setMessage('');const {error:problem}=await createClient().rpc(name,args);if(problem)setError(explainError(problem.message));else{setMessage(success);await load()}setBusy(false)}
 if(!loading&&!authorized)return <main className="mx-auto max-w-5xl p-6"><h1 className="text-3xl font-bold"><T text="Sanctions and student departures"/></h1><p role="alert" className="mt-4 rounded-lg bg-red-50 p-4 text-red-800"><T text="You do not have permission to manage these records."/></p></main>
 return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6 lg:p-8"><header><h1 className="text-3xl font-bold tracking-tight text-slate-900"><T text="Sanctions and student departures"/></h1><p className="mt-2 max-w-3xl text-slate-600"><T text="Manage school-defined sanctions, authorized emergency contacts, and reviewed medical or exceptional departures."/></p></header>
 {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}{message&&<p role="status" className="rounded-lg bg-green-50 p-3 text-green-800">{message}</p>}
 {loading?<p><T text="Loading..."/></p>:<>
 <section className="grid gap-6 xl:grid-cols-2">
  <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold"><T text="School sanction catalog"/></h2><p className="mt-1 text-sm text-slate-600"><T text="Add the sanction types your school uses. You can deactivate a type without deleting its history."/></p>
   <form className="mt-4 flex flex-col gap-3 sm:flex-row" onSubmit={e=>{e.preventDefault();void action('save_student_sanction_type',{p_type:null,p_name:typeName,p_active:true},'Sanction type saved.').then(()=>setTypeName(''))}}><label className="sr-only" htmlFor="sanction-type"><T text="Sanction name"/></label><input id="sanction-type" required minLength={2} maxLength={120} value={typeName} onChange={e=>setTypeName(e.target.value)} className="min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2" placeholder="Suspension, warning…"/><button disabled={busy} className="rounded-lg bg-blue-700 px-4 py-2 font-medium text-white disabled:opacity-60"><T text="Add sanction type"/></button></form>
   <ul className="mt-4 divide-y divide-slate-100">{data.sanction_types.map(t=><li key={t.id} className="flex items-center justify-between py-2"><span>{t.name}</span><button disabled={busy} onClick={()=>void action('save_student_sanction_type',{p_type:t.id,p_name:t.name,p_active:!t.active},t.active?'Sanction type deactivated.':'Sanction type activated.')} className="rounded-full bg-slate-100 px-3 py-1 text-sm"><T text={t.active?'Active':'Inactive'}/></button></li>)}</ul>
   <form className="mt-5 grid gap-3" onSubmit={e=>{e.preventDefault();void action('create_student_sanction',{p_student:student,p_type:typeId,p_reason:reason,p_incident_at:new Date(incident||Date.now()).toISOString()},'Sanction recorded.').then(()=>setReason(''))}}><h3 className="font-semibold"><T text="Record a sanction"/></h3><label className="text-sm"><T text="Student"/><select required value={student} onChange={e=>setStudent(e.target.value)} className="mt-1 w-full rounded-lg border p-2"><option value=""><T text="Choose a student"/></option>{activeStudents.map(s=><option key={s.id} value={s.id}>{s.name}{s.class?` · ${s.class}`:''}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm"><T text="Sanction type"/><select required value={typeId} onChange={e=>setTypeId(e.target.value)} className="mt-1 w-full rounded-lg border p-2"><option value=""><T text="Choose a sanction"/></option>{activeTypes.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="text-sm"><T text="Incident date and time"/><input type="datetime-local" value={incident} onChange={e=>setIncident(e.target.value)} className="mt-1 w-full rounded-lg border p-2"/></label></div><label className="text-sm"><T text="Reason"/><textarea required minLength={3} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)} rows={3} className="mt-1 w-full rounded-lg border p-2"/></label><button disabled={busy||!activeTypes.length} className="justify-self-start rounded-lg bg-blue-700 px-4 py-2 font-medium text-white disabled:opacity-60"><T text="Save sanction"/></button></form>
  </article>
  <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold"><T text="Authorized release contacts"/></h2><p className="mt-1 text-sm text-slate-600"><T text="Only school administrators, directors, and secretaries can register or deactivate an alternate adult."/></p><form className="mt-4 grid gap-3" onSubmit={e=>{e.preventDefault();void action('save_student_release_contact',{p_student:contactStudent,p_contact:null,p_name:contactName,p_relationship:relationship,p_phone:phone||null,p_active:true},'Authorized contact saved.').then(()=>{setContactName('');setRelationship('');setPhone('')})}}><label className="text-sm"><T text="Student"/><select required value={contactStudent} onChange={e=>setContactStudent(e.target.value)} className="mt-1 w-full rounded-lg border p-2"><option value=""><T text="Choose a student"/></option>{activeStudents.map(s=><option key={s.id} value={s.id}>{s.name}{s.class?` · ${s.class}`:''}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm"><T text="Authorized adult name"/><input required minLength={2} maxLength={160} value={contactName} onChange={e=>setContactName(e.target.value)} className="mt-1 w-full rounded-lg border p-2"/></label><label className="text-sm"><T text="Relationship to student"/><input required minLength={2} maxLength={80} value={relationship} onChange={e=>setRelationship(e.target.value)} className="mt-1 w-full rounded-lg border p-2"/></label></div><label className="text-sm"><T text="Phone (optional)"/><input type="tel" maxLength={40} value={phone} onChange={e=>setPhone(e.target.value)} className="mt-1 w-full rounded-lg border p-2"/></label><button disabled={busy} className="justify-self-start rounded-lg bg-blue-700 px-4 py-2 font-medium text-white"><T text="Register authorized adult"/></button></form><ul className="mt-5 space-y-2">{data.contacts.map(c=><li key={c.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-50 p-3"><span><strong>{c.full_name}</strong> · {c.relationship}{c.phone?` · ${c.phone}`:''}<small className="block text-slate-600">{activeStudents.find(s=>s.id===c.student_id)?.name||''}</small></span><button disabled={busy} onClick={()=>void action('save_student_release_contact',{p_student:c.student_id,p_contact:c.id,p_name:c.full_name,p_relationship:c.relationship,p_phone:c.phone,p_active:!c.active},c.active?'Contact deactivated.':'Contact reactivated.')} className="rounded border px-3 py-1"><T text={c.active?'Deactivate':'Reactivate'}/></button></li>)}</ul></article>
 </section>
 <section className="grid gap-6 xl:grid-cols-2">
  <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold"><T text="Medical or exceptional departure"/></h2><p className="mt-1 text-sm text-slate-600"><T text="A responsible staff member must review the request before departure. Record the adult, reason, departure, and expected return."/></p><form className="mt-4 grid gap-3" onSubmit={e=>{e.preventDefault();void action('request_student_release',{p_student:releaseStudent,p_kind:releaseKind,p_contact:contactId,p_reason:releaseReason},'Departure request sent for staff review.').then(()=>setReleaseReason(''))}}><label className="text-sm"><T text="Student"/><select required value={releaseStudent} onChange={e=>{setReleaseStudent(e.target.value);setContactId('')}} className="mt-1 w-full rounded-lg border p-2"><option value=""><T text="Choose a student"/></option>{activeStudents.map(s=><option key={s.id} value={s.id}>{s.name}{s.class?` · ${s.class}`:''}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm"><T text="Departure type"/><select value={releaseKind} onChange={e=>setReleaseKind(e.target.value as 'medical'|'exceptional')} className="mt-1 w-full rounded-lg border p-2"><option value="medical"><T text="Medical"/></option><option value="exceptional"><T text="Exceptional"/></option></select></label><label className="text-sm"><T text="Authorized adult"/><select required value={contactId} onChange={e=>setContactId(e.target.value)} className="mt-1 w-full rounded-lg border p-2"><option value=""><T text="Choose an authorized adult"/></option>{activeContacts.map(c=><option key={c.id} value={c.id}>{c.full_name} · {c.relationship}</option>)}</select></label></div><label className="text-sm"><T text="Reason"/><textarea required minLength={3} maxLength={2000} value={releaseReason} onChange={e=>setReleaseReason(e.target.value)} rows={3} className="mt-1 w-full rounded-lg border p-2"/></label><button disabled={busy||!activeContacts.length} className="justify-self-start rounded-lg bg-blue-700 px-4 py-2 font-medium text-white disabled:opacity-60"><T text="Submit for review"/></button></form></article>
  <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold"><T text="Departure requests"/></h2><ul className="mt-4 space-y-3">{data.releases.length===0?<li className="rounded-lg bg-slate-50 p-4 text-slate-600"><T text="No departure requests."/></li>:data.releases.map(r=><li key={r.id} className="rounded-lg border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-2"><div><strong>{r.student}</strong> · <T text={r.kind==='medical'?'Medical':'Exceptional'}/><p className="text-sm text-slate-600">{schoolDateTime(r.requested_at)} · {r.contact_name} ({r.contact_relationship})</p></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-sm"><T text={r.status}/></span></div><p className="mt-2"><strong><T text="Reason"/>:</strong> {r.reason}</p>{r.decision_reason&&<p className="mt-1 text-sm"><strong><T text="Review note"/>:</strong> {r.decision_reason}</p>}{r.expected_return_at&&<p className="mt-1 text-sm"><T text="Expected return"/>: {schoolDateTime(r.expected_return_at)}</p>}<div className="mt-3 flex flex-wrap gap-2">{r.status==='pending'&&<><input aria-label="Review note" value={comments[r.id]||''} onChange={e=>setComments(v=>({...v,[r.id]:e.target.value}))} placeholder="Rejection reason (required when rejecting)" className="min-w-52 flex-1 rounded border px-3 py-2"/><button disabled={busy} onClick={()=>void action('review_student_release',{p_case:r.id,p_approve:true,p_comment:comments[r.id]||null},'Departure approved.')} className="rounded bg-green-700 px-3 py-2 text-white"><T text="Approve"/></button><button disabled={busy||!(comments[r.id]||'').trim()} onClick={()=>void action('review_student_release',{p_case:r.id,p_approve:false,p_comment:comments[r.id]},'Decision saved.')} className="rounded border border-red-300 px-3 py-2 text-red-800 disabled:opacity-50"><T text="Reject"/></button></>}{r.status==='approved'&&<><label className="text-sm"><T text="Expected return"/><input aria-label="Expected return" type="datetime-local" value={returnTimes[r.id]||''} onChange={e=>setReturnTimes(v=>({...v,[r.id]:e.target.value}))} className="mt-1 block rounded border px-3 py-2"/></label><button disabled={busy||!returnTimes[r.id]} onClick={()=>void action('record_student_release',{p_case:r.id,p_expected_return_at:new Date(returnTimes[r.id]).toISOString()},'Departure recorded.')} className="self-end rounded bg-blue-700 px-3 py-2 text-white"><T text="Record student departure"/></button></>}{r.status==='released'&&<button disabled={busy} onClick={()=>void action('confirm_student_return',{p_case:r.id},'Student return recorded.')} className="rounded bg-blue-700 px-3 py-2 text-white"><T text="Confirm student return"/></button>}</div></li>)}</ul></article>
 </section>
 <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold"><T text="Sanction history"/></h2>{data.sanctions.length===0?<p className="mt-3 text-slate-600"><T text="No sanctions recorded."/></p>:<ul className="mt-3 divide-y divide-slate-100">{data.sanctions.map(s=><li key={s.id} className="flex flex-col gap-2 py-3 sm:flex-row sm:items-center sm:justify-between"><span><strong>{s.student}</strong> · {data.sanction_types.find(t=>t.id===s.sanction_type_id)?.name||'—'} <span className="text-sm text-slate-500">· {schoolDateTime(s.incident_at)} · {s.created_role}</span><span className="block text-sm">{s.reason}</span>{s.resolution&&<span className="block text-sm text-slate-600">{s.resolution}</span>}</span>{s.status==='active'&&<form className="flex gap-2" onSubmit={e=>{e.preventDefault();void action('resolve_student_sanction',{p_sanction:s.id,p_resolution:resolutions[s.id]||''},'Sanction resolved.').then(()=>setResolutions(v=>({...v,[s.id]:''})))}}><label className="min-w-0 flex-1 text-sm"><T text="Resolution"/><input required minLength={3} maxLength={2000} value={resolutions[s.id]||''} onChange={e=>setResolutions(v=>({...v,[s.id]:e.target.value}))} aria-label="Resolution" className="mt-1 block w-full rounded border px-3 py-2"/></label><button disabled={busy} className="rounded border px-3 py-2"><T text="Resolve"/></button></form>}</li>)}</ul>}</section>
 </>}
 </main>
}
