'use client'
import {useCallback,useEffect,useState} from 'react'
import {T} from '@/components/translation-provider'
import QRScanner from '@/components/qr-scanner'
import {createClient} from '@/lib/supabase/client'
import {schoolTime} from '@/lib/school-date'

type AuthorizedPerson={id:string;name:string;relationship:string;phone?:string|null}
type Preview={student_id:string;student:string;class:string;checked_in:boolean;picked_up:boolean;authorized_people:AuthorizedPerson[]}
type Child={id:string;name:string;class:string;status:string;check_in_at:string;picked_up:boolean;pickup_at:string|null;picked_up_by:string|null;authorizations:AuthorizedPerson[]}
export default function KindergartenPickupPage(){
 const [students,setStudents]=useState<Child[]>([]),[canManage,setCanManage]=useState(false),[preview,setPreview]=useState<Preview|null>(null),[qr,setQr]=useState(''),[adult,setAdult]=useState(''),[reason,setReason]=useState(''),[name,setName]=useState(''),[relationship,setRelationship]=useState(''),[phone,setPhone]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[receipt,setReceipt]=useState<{student:string;class:string;adult:string;time:string}|null>(null)
 const load=useCallback(async()=>{const {data,error}=await createClient().rpc('kindergarten_pickup_workspace');if(error){setError('The Kindergarten pickup workspace is unavailable.');return}setStudents((data?.students||[]) as Child[]);setCanManage(Boolean(data?.can_manage_authorizations))},[])
 useEffect(()=>{void load()},[load])
 async function scan(value:string){setError('');setMessage('');setPreview(null);setAdult('');setQr(value.trim());setBusy(true);const {data,error}=await createClient().rpc('kindergarten_pickup_preview',{p_qr:value.trim()});setBusy(false);if(error){setError(error.message==='preschool_only'?'This badge is not assigned to a Preschool student.':'Badge not accepted for pickup. Verify the active badge and ask authorized school staff.');return}setPreview(data as Preview)}
 async function complete(){if(!preview||!adult)return;setBusy(true);setError('');setMessage('');setReceipt(null);const {data,error}=await createClient().rpc('complete_kindergarten_pickup',{p_qr:qr,p_authorization:adult,p_reason:reason||null});setBusy(false);if(error){setError(error.message==='already_picked_up'?'This student has already been picked up today.':error.message==='student_not_on_campus'?'Only a student checked in and still on campus can be picked up here.':'Pickup could not be recorded. Verify the authorized adult and try again.');return}setMessage('Pickup recorded.');setReceipt({student:data?.student||'',class:data?.class||'',adult:data?.picked_up_by||'',time:data?.pickup_at||''});setPreview(null);setQr('');setAdult('');setReason('');await load()}
 async function saveAuthorization(){if(!preview||!name.trim()||!relationship.trim())return;setBusy(true);setError('');const {error}=await createClient().rpc('save_kindergarten_pickup_authorization',{p_student:preview.student_id,p_authorization:null,p_name:name.trim(),p_relationship:relationship.trim(),p_phone:phone.trim()||null,p_active:true});setBusy(false);if(error){setError('Unable to add the authorized pickup person.');return}setName('');setRelationship('');setPhone('');await scan(qr)}
 async function deactivate(id:string){if(!preview)return;setBusy(true);setError('');const {error}=await createClient().rpc('save_kindergarten_pickup_authorization',{p_student:preview.student_id,p_authorization:id,p_name:'',p_relationship:'',p_phone:null,p_active:false});setBusy(false);if(error){setError('Unable to deactivate this pickup authorization.');return}await scan(qr)}
 return <main className="mx-auto max-w-5xl p-6 md:p-10"><header><p className="text-sm text-slate-600"><T text="Attendance"/> / <T text="Kindergarten pickup"/></p><h1 className="my-3 text-3xl font-bold"><T text="Kindergarten pickup"/></h1><p className="text-slate-600"><T text="Scan the student's active badge, verify the adult in person, and record pickup once for today."/></p></header>
 {error&&<p role="alert" className="my-4 rounded bg-red-50 p-3 text-red-800"><T text={error}/></p>}{message&&<p role="status" className="my-4 rounded bg-green-50 p-3 text-green-800"><T text={message}/>{receipt&&<> {receipt.student} · {receipt.class} · {receipt.adult} · {schoolTime(receipt.time)}</>}</p>}
 <section className="my-6 rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold"><T text="Scan student badge"/></h2><QRScanner onRead={value=>void scan(value)}/><label className="block text-sm font-medium"><T text="Paste scanned badge QR"/><input value={qr} onChange={e=>setQr(e.target.value)} maxLength={80} className="mt-1 w-full rounded border p-3 font-mono" placeholder="AOSQ1.…"/></label><button disabled={busy||!qr.trim()} onClick={()=>void scan(qr)} className="mt-3 rounded bg-blue-700 px-4 py-2 text-white disabled:opacity-50"><T text="Verify badge"/></button></section>
 {preview&&<section className="my-6 rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">{preview.student} · {preview.class}</h2><p className="mt-1 text-sm text-slate-600">{preview.picked_up?<T text="Already picked up today"/>:preview.checked_in?<T text="Checked in and on campus"/>:<T text="Student must be checked in before pickup"/>}</p>{!preview.picked_up&&preview.checked_in&&<><label className="mt-4 block text-sm font-medium"><T text="Adult collecting the child"/><select value={adult} onChange={e=>setAdult(e.target.value)} className="mt-1 w-full rounded border p-3"><option value=""><T text="Select an authorized adult"/></option>{preview.authorized_people.map(a=><option key={a.id} value={a.id}>{a.name} · {a.relationship}</option>)}</select></label><label className="mt-3 block text-sm font-medium"><T text="Pickup note (optional)"/><input value={reason} onChange={e=>setReason(e.target.value)} maxLength={500} className="mt-1 w-full rounded border p-3"/></label><button disabled={busy||!adult} onClick={()=>void complete()} className="mt-4 rounded bg-emerald-700 px-4 py-2 font-semibold text-white disabled:opacity-50"><T text="Confirm pickup"/></button></>}
 {canManage&&<details className="mt-5 rounded border p-4"><summary className="cursor-pointer font-semibold"><T text="Manage authorized pickup adults"/></summary><div className="mt-3 space-y-2">{preview.authorized_people.map(a=><div key={a.id} className="flex flex-wrap items-center justify-between gap-2 border-b py-2"><span>{a.name} · {a.relationship}{a.phone?` · ${a.phone}`:''}</span><button disabled={busy} onClick={()=>void deactivate(a.id)} className="text-sm text-red-700 underline"><T text="Deactivate"/></button></div>)}{!preview.authorized_people.length&&<p className="text-sm text-slate-600"><T text="No authorized adults are registered."/></p>}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-sm"><T text="Adult full name"/><input value={name} onChange={e=>setName(e.target.value)} maxLength={160} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm"><T text="Relationship to student"/><input value={relationship} onChange={e=>setRelationship(e.target.value)} maxLength={80} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm"><T text="Phone (optional)"/><input value={phone} onChange={e=>setPhone(e.target.value)} maxLength={40} className="mt-1 w-full rounded border p-2"/></label></div><button disabled={busy||!name.trim()||!relationship.trim()} onClick={()=>void saveAuthorization()} className="mt-3 rounded border px-4 py-2"><T text="Add authorized adult"/></button></details>}</section>}
 <section className="mt-8 rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold"><T text="Students checked in today"/></h2>{!students.length?<p className="mt-3 text-slate-600"><T text="No Preschool students are currently checked in."/></p>:<div className="mt-3 divide-y">{students.map(s=><article key={s.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-semibold">{s.name} · {s.class}</p><p className="text-sm text-slate-600"><T text="Check-in"/> {schoolTime(s.check_in_at)} · {s.picked_up?<T text="Picked up"/>:<T text="On campus"/>}</p></div>{s.picked_up&&<p className="text-sm">{s.picked_up_by} · {schoolTime(s.pickup_at||'')}</p>}</article>)}</div>}</section></main>
}
