'use client'
import { T } from '@/components/translation-provider'
import {useEffect,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
type Year={id:string;name:string};type Class={id:string;name:string;academic_year_id:string;grade_level:string};type Row={id:string;name:string;atechos_id:string;class_name:string;average:number|null;passing:number;recommended_grade:string|null;complete:boolean}
export default function ProgressionPage(){
 const [years,setYears]=useState<Year[]>([]),[classes,setClasses]=useState<Class[]>([]),[source,setSource]=useState(''),[target,setTarget]=useState(''),[rows,setRows]=useState<Row[]>([]),[choices,setChoices]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{const db=createClient();Promise.all([db.from('academic_years').select('id,name').order('start_date',{ascending:false}),db.from('classes').select('id,name,academic_year_id,grade_level').eq('enabled',true)]).then(([y,c])=>{setYears(y.data||[]);setClasses(c.data||[]);setTarget(y.data?.[0]?.id||'');setSource(y.data?.[1]?.id||'');if(y.error||c.error)setMessage('Unable to load school years.')})},[])
 async function preview(){setBusy(true);setMessage('');try{const {data,error}=await createClient().rpc('preview_student_progression',{p_source:source,p_target:target});if(error){setMessage(error.message);return}setRows(data||[]);const defaults:Record<string,string>={};for(const r of (data||[]) as Row[]){const matches=classes.filter(c=>c.academic_year_id===target && c.grade_level===r.recommended_grade);defaults[r.id]=matches.length===1?matches[0].id:''}setChoices(defaults)}finally{setBusy(false)}}
 async function apply(){setBusy(true);setMessage('');try{const decisions=rows.filter(r=>choices[r.id]).map(r=>({student_id:r.id,decision:choices[r.id]==='departed'?'departed':'placement',class_id:choices[r.id]==='departed'?null:choices[r.id]}));const {error}=await createClient().rpc('confirm_student_progression',{p_source:source,p_target:target,p_decisions:decisions});if(error){setMessage(error.message);return}setMessage('Selected decisions saved. Historical school records are preserved.');setRows([]);setChoices({})}finally{setBusy(false)}}
 return <main className="mx-auto max-w-6xl p-6"><h1 className="text-3xl font-bold"><T text="Academic progression"/></h1><p className="my-3"><T text="Review the proposed placements before confirming. Averages use published grades. Missing grades and multiple destination classes require a manual choice. Activate the destination classes in Classes first."/></p><div className="flex flex-wrap gap-4"><label><T text="Previous year"/><select value={source} onChange={e=>{setSource(e.target.value);setRows([])}} className="ml-2 rounded border p-3"><option value=""><T text="Select year"/></option>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><label><T text="New year"/><select value={target} onChange={e=>{setTarget(e.target.value);setRows([])}} className="ml-2 rounded border p-3"><option value=""><T text="Select year"/></option>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><button disabled={busy||!source||!target||source===target} onClick={preview} className="rounded border p-3"><T text="Prepare promotion list"/></button></div>{message&&<p role="status" className="my-4"><T text={message}/></p>}<div className="my-5 overflow-x-auto"><table className="w-full text-left"><thead><tr><th><T text="Student"/></th><th><T text="Current class"/></th><th><T text="Average / 10"/></th><th><T text="Decision"/></th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="py-3">{r.name}<small className="block">{r.atechos_id}</small></td><td>{r.class_name}</td><td>{r.average===null?'—':Number(r.average).toFixed(2)}{!r.complete && <small className="block text-amber-700"><T text="Incomplete"/></small>} / {r.passing} minimum</td><td><select value={choices[r.id]||''} onChange={e=>setChoices(v=>({...v,[r.id]:e.target.value}))} className="rounded border p-3"><option value=""><T text="Leave unchanged / review later"/></option>{classes.filter(c=>c.academic_year_id===target).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}<option value="departed"><T text="Ailleurs — left school (archive only)"/></option></select></td></tr>)}</tbody></table></div><button disabled={busy||!rows.length} onClick={apply} className="rounded bg-blue-600 p-3 text-white"><T text="Confirm selected placements"/></button><p className="my-3"><T text="Leaving school ends access to current school activity. The student and parents retain historical published bulletins up to the selected previous year."/></p></main>
}
